import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { getRecipeDetail, getScaledRecipe, addRecipeToShopping, RecipeDetail, ScaledRecipe } from '../../lib/recipe-detail-api';
import { useAppLocale } from '../../lib/i18n';

const copy={
 en:{back:'Back',loading:'Loading recipe…',servings:'Servings',ingredients:'Ingredients',nutrition:'Nutrition',scale:'Scale recipe',minus:'−',plus:'+',shopping:'Add missing ingredients to shopping list',added:'Added to shopping list',verified:'Verified',kcal:'kcal',protein:'protein',error:'Recipe unavailable.'},
 fa:{back:'برگشت',loading:'در حال بارگذاری دستور…',servings:'تعداد نفرات',ingredients:'مواد لازم',nutrition:'ارزش غذایی',scale:'تغییر مقدار',minus:'−',plus:'+',shopping:'افزودن مواد کمبود به لیست خرید',added:'به لیست خرید اضافه شد',verified:'تأییدشده',kcal:'کالری',protein:'پروتئین',error:'دستور غذا در دسترس نیست.'}
} as const;

export default function RecipeDetailScreen(){
 const locale=useAppLocale();const text=copy[locale];const {id}=useLocalSearchParams<{id?:string}>();const [recipe,setRecipe]=useState<RecipeDetail|null>(null);const [scaled,setScaled]=useState<ScaledRecipe|null>(null);const [servings,setServings]=useState(2);const [error,setError]=useState<string|null>(null);const [shopping,setShopping]=useState(false);
 useEffect(()=>{if(!id)return;void getRecipeDetail(String(id)).then(value=>{setRecipe(value);setServings(value.servings);}).catch(err=>setError(err instanceof Error?err.message:text.error));},[id,text.error]);
 useEffect(()=>{if(!recipe)return;const next=Math.max(1,Math.min(50,servings));void getScaledRecipe(recipe.id,next).then(setScaled).catch(()=>setScaled(null));},[recipe,servings]);
 const quantities=useMemo(()=>{const byId=new Map((scaled?.ingredients??[]).map(item=>[item.ingredientId,item]));return recipe?.ingredients.map(item=>({item,scaled:byId.get(item.foodId)??byId.get(item.id)}))??[]},[recipe,scaled]);
 if(!recipe&&!error)return <View style={styles.center}><ActivityIndicator size="large"/><Text style={styles.loading}>{text.loading}</Text></View>;
 if(error)return <SafeAreaView style={styles.safe}><Text style={styles.error}>{error}</Text><Pressable style={styles.button} onPress={()=>router.back()}><Text style={styles.buttonText}>{text.back}</Text></Pressable></SafeAreaView>;
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={()=>router.back()}><Text style={styles.back}>{locale==='fa'?'→':'←'} {text.back}</Text></Pressable>{recipe!.imageUrl?<Image source={{uri:recipe!.imageUrl}} style={styles.hero}/>:null}<View style={styles.titleRow}><Text style={styles.title}>{recipe!.name}</Text>{recipe!.verified?<Text style={styles.badge}>{text.verified}</Text>:null}</View>{recipe!.description?<Text style={styles.description}>{recipe!.description}</Text>:null}
   <View style={styles.nutrition}><Metric label={text.kcal} value={`${Math.round(recipe!.calories)}`}/><Metric label={text.protein} value={`${Math.round(recipe!.protein)}g`}/><Metric label={locale==='fa'?'کرب':'Carbs'} value={`${Math.round(recipe!.carbs)}g`}/><Metric label={locale==='fa'?'چربی':'Fat'} value={`${Math.round(recipe!.fat)}g`}/></View>
   <Text style={styles.section}>{text.servings}</Text><View style={styles.stepper}><Pressable onPress={()=>setServings(value=>Math.max(1,value-1))} style={styles.stepButton}><Text style={styles.stepText}>{text.minus}</Text></Pressable><Text style={styles.servings}>{servings}</Text><Pressable onPress={()=>setServings(value=>Math.min(50,value+1))} style={styles.stepButton}><Text style={styles.stepText}>{text.plus}</Text></Pressable></View>
   <Text style={styles.section}>{text.ingredients}</Text>{quantities.map(({item,scaled:scaledItem})=><View style={styles.ingredient} key={item.id}><Text style={styles.ingredientName}>{item.food.name}</Text><Text style={styles.quantity}>{scaledItem?.displayQuantity??scaledItem?.quantity??item.quantity} {scaledItem?.unit??item.unit}</Text></View>)}
   <Pressable disabled={shopping} onPress={()=>{setShopping(true);void addRecipeToShopping(recipe!.id,servings).then(()=>{}).finally(()=>setShopping(false));}} style={styles.shopping}><Text style={styles.shoppingText}>{shopping?'…':text.shopping}</Text></Pressable>
   <Pressable onPress={()=>router.push('/meal-builder')} style={styles.button}><Text style={styles.buttonText}>{locale==='fa'?'ثبت به‌عنوان وعده':'Log as meal'}</Text></Pressable>
 </ScrollView></SafeAreaView>;
}
function Metric({label,value}:{label:string;value:string}){return <View><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F8FA'},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F7F8FA'},loading:{marginTop:10,color:'#6B7280'},content:{padding:20,paddingBottom:40},back:{fontWeight:'900',color:'#111827',marginBottom:14},hero:{width:'100%',height:200,borderRadius:20,marginBottom:14},titleRow:{flexDirection:'row',alignItems:'center',gap:8},title:{flex:1,fontSize:29,fontWeight:'900',color:'#111827'},badge:{fontSize:9,fontWeight:'900',color:'#067647',backgroundColor:'#ECFDF3',paddingHorizontal:8,paddingVertical:5,borderRadius:9},description:{fontSize:13,color:'#6B7280',lineHeight:20,marginTop:7},nutrition:{backgroundColor:'#111827',borderRadius:20,padding:15,flexDirection:'row',gap:10,marginTop:15},metricLabel:{fontSize:9,color:'#D1D5DB'},metricValue:{fontSize:16,fontWeight:'900',color:'#FFF',marginTop:4},section:{fontSize:18,fontWeight:'900',color:'#111827',marginTop:22,marginBottom:10},stepper:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:20,backgroundColor:'#FFF',padding:10,borderRadius:16},stepButton:{width:42,height:42,borderRadius:21,backgroundColor:'#111827',alignItems:'center',justifyContent:'center'},stepText:{color:'#FFF',fontSize:24,fontWeight:'900'},servings:{fontSize:24,fontWeight:'900',color:'#111827'},ingredient:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',backgroundColor:'#FFF',borderRadius:13,paddingHorizontal:14,paddingVertical:12,marginBottom:8},ingredientName:{fontSize:13,fontWeight:'800',color:'#374151',flex:1},quantity:{fontSize:12,fontWeight:'900',color:'#111827'},shopping:{backgroundColor:'#0F766E',borderRadius:15,paddingVertical:14,alignItems:'center',marginTop:12},shoppingText:{color:'#FFF',fontWeight:'900'},button:{backgroundColor:'#111827',borderRadius:15,paddingVertical:14,alignItems:'center',marginTop:10},buttonText:{color:'#FFF',fontWeight:'900'},error:{margin:20,color:'#991B1B',fontWeight:'800'}});