import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { BrainOverview, getBrainOverview, hasAuthSession } from '../lib/api';
import { confirmNextBestAction, executeNextBestAction, recordBrainFeedback } from '../lib/brain-execution';
import { PREMIUM } from '../lib/premium-ui';
import { PremiumGlow } from '../components/PremiumGlow';
import { PremiumResultCard } from '../components/PremiumResultCard';
import { MotionPress } from '../lib/motion-components';

export default function BrainOverviewPremiumScreen(){
  const [data,setData]=useState<BrainOverview|null>(null); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [busy,setBusy]=useState<string|null>(null); const [token,setToken]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setError(null);setData(await getBrainOverview());}catch(e){setError(e instanceof Error?e.message:'Unable to load your assistant.');}finally{setLoading(false);setRefreshing(false);}},[]);
  useEffect(()=>{void hasAuthSession().then(ok=>{if(ok)void load();else{setError('Please sign in first.');setLoading(false);}})},[load]);
  const execute=useCallback(async()=>{try{setBusy('execute');setMessage(null);const receipt=await executeNextBestAction();if(receipt.status==='pending_confirmation'&&receipt.confirmationToken){setToken(receipt.confirmationToken);setMessage('One quick confirmation is needed before I do this.');}else if(receipt.status==='completed'){setMessage('Done. I updated your plan.');await load();}else setMessage(`${receipt.status}: ${receipt.reason}`);}catch(e){setError(e instanceof Error?e.message:'Unable to complete this action.');}finally{setBusy(null);}},[load]);
  const confirm=useCallback(async()=>{if(!token)return;try{setBusy('confirm');setMessage(null);const receipt=await confirmNextBestAction(token);setToken(null);if(receipt.status==='completed'){setMessage('Confirmed and completed.');await load();}else setMessage(`${receipt.status}: ${receipt.reason}`);}catch(e){setError(e instanceof Error?e.message:'Unable to confirm this action.');}finally{setBusy(null);}},[load,token]);
  const feedback=useCallback(async(outcome:'completed'|'skipped'|'dismissed')=>{const action=data?.nextAction?.action;if(!action)return;try{setBusy(outcome);await recordBrainFeedback({candidate:{id:action.id,domain:'schedule',action:'complete_life_task',priority:action.priority,source:'mobile_brain',durationMinutes:action.estimatedMinutes,confidence:1},outcome,note:outcome==='completed'?'User marked next action as done.':outcome==='dismissed'?'User marked next action as not useful.':'User deferred the next action.'});setMessage(outcome==='completed'?'Got it. I learned from that.':outcome==='dismissed'?'Got it. I’ll adjust future suggestions.':'Saved for later.');await load();}catch(e){setError(e instanceof Error?e.message:'Unable to save feedback.');}finally{setBusy(null);}},[data,load]);
  if(loading)return <View style={styles.loading}><PremiumGlow size={280} opacity={0.12} accent="mint"/><ActivityIndicator color={PREMIUM.colors.primaryBright}/><Text style={styles.loadingText}>Personal brain</Text></View>;
  const action=data?.nextAction?.action; const urgent=data?.nextAction?.mode==='urgent';
  return <SafeAreaView style={styles.safe}><View style={styles.bg}><PremiumGlow size={380} opacity={0.06} accent="mint"/></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.top}><Pressable onPress={()=>router.back()} style={styles.icon}><Ionicons name="arrow-back" size={18} color={PREMIUM.colors.inkSoft}/></Pressable><View style={styles.titleWrap}><Text style={styles.kicker}>PERSONAL BRAIN</Text><Text style={styles.title}>Mind & context</Text></View><Pressable onPress={()=>router.push('/assistant')} style={styles.icon}><Ionicons name="mic-outline" size={18} color={PREMIUM.colors.primaryBright}/></Pressable></View>
    <PremiumResultCard eyebrow="MYPA" title="The assistant is keeping the thread" accent="mint" detail="Plans, feedback and next actions stay connected behind the scenes so the interface can stay simple." />
    {error?<PremiumResultCard eyebrow="SYSTEM" title="Brain unavailable" detail={error} accent="rose" actions={[{label:'Retry',icon:'refresh',onPress:()=>void load()}]}/>:null}
    {message?<PremiumResultCard eyebrow="UPDATED" title="I heard you" detail={message} accent="cyan"/>:null}
    {action?<View style={styles.action}><View style={styles.actionHead}><View style={[styles.pill,urgent&&styles.pillUrgent]}><Text style={[styles.pillText,urgent&&styles.pillUrgentText]}>{urgent?'NEEDS ATTENTION':'NEXT FOR YOU'}</Text></View><Text style={styles.minutes}>{action.estimatedMinutes} min</Text></View><Text style={styles.actionTitle}>{action.title}</Text><Text style={styles.actionMeta}>{action.urgent?'Due now':`Priority ${action.priority}`}{action.reasons.length?` · ${action.reasons[0]}`:''}</Text>{!token?<MotionPress disabled={!!busy} onPress={()=>void execute()} style={styles.primary}><Text style={styles.primaryText}>{busy==='execute'?'Working…':'Do this for me'}</Text><Ionicons name="arrow-forward" size={16} color={PREMIUM.colors.ink}/></MotionPress>:<MotionPress disabled={!!busy} onPress={()=>void confirm()} style={styles.confirm}><Text style={styles.primaryText}>{busy==='confirm'?'Confirming…':'Confirm & do it'}</Text><Ionicons name="checkmark" size={17} color={PREMIUM.colors.ink}/></MotionPress>}<Text style={styles.feedbackLabel}>Not right?</Text><View style={styles.feedback}><Pressable disabled={!!busy} onPress={()=>void feedback('completed')} style={styles.feedbackButton}><Ionicons name="checkmark-circle-outline" size={16} color={PREMIUM.colors.mint}/><Text style={styles.feedbackText}>Done</Text></Pressable><Pressable disabled={!!busy} onPress={()=>void feedback('skipped')} style={styles.feedbackButton}><Ionicons name="time-outline" size={16} color={PREMIUM.colors.amber}/><Text style={styles.feedbackText}>Later</Text></Pressable><Pressable disabled={!!busy} onPress={()=>void feedback('dismissed')} style={styles.feedbackButton}><Ionicons name="close-circle-outline" size={16} color={PREMIUM.colors.rose}/><Text style={styles.feedbackText}>Nope</Text></Pressable></View></View>:<View style={styles.clear}><Ionicons name="sparkles-outline" size={26} color={PREMIUM.colors.primaryBright}/><Text style={styles.clearTitle}>You’re all caught up.</Text><Text style={styles.clearText}>There is nothing important waiting for you right now.</Text></View>}
    <Text style={styles.section}>WHAT MYPA IS NOTICING</Text>
    {data?<><PremiumResultCard title="Current plan" accent="cyan" detail={summarize(data.plan)}/><PremiumResultCard title="Coach signal" accent="mint" detail={summarize(data.coachNext)}/><PremiumResultCard title="Schedule health" accent="amber" detail={summarize(data.scheduleHealth)}/></>:null}
  </ScrollView></SafeAreaView>;
}
function summarize(v:unknown){if(v==null)return'Nothing to show yet.';if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')return String(v);if(Array.isArray(v))return v.length?`${v.length} signals available`:'Nothing to show yet.';if(typeof v==='object'){const o=v as Record<string,unknown>;for(const k of ['message','title','name','status','summary','recommendation','reason'])if(typeof o[k]==='string'&&o[k])return o[k] as string;return'Personalized information is available.';}return'Available';}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:PREMIUM.colors.canvas},bg:{...StyleSheet.absoluteFillObject,overflow:'hidden'},content:{padding:18,gap:15,paddingBottom:120},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:PREMIUM.colors.canvas},loadingText:{color:PREMIUM.colors.ink,fontSize:14,fontWeight:'900',marginTop:12},top:{flexDirection:'row',alignItems:'center',gap:10},icon:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:PREMIUM.colors.border,backgroundColor:'rgba(255,255,255,0.035)',alignItems:'center',justifyContent:'center'},titleWrap:{flex:1,alignItems:'center'},kicker:{color:PREMIUM.colors.muted,fontSize:8,fontWeight:'900',letterSpacing:1.4},title:{color:PREMIUM.colors.ink,fontSize:18,fontWeight:'900',marginTop:3},action:{borderRadius:26,padding:20,backgroundColor:PREMIUM.colors.surfaceElevated,borderWidth:1,borderColor:'rgba(98,230,181,0.22)'},actionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},pill:{backgroundColor:'rgba(98,230,181,0.12)',paddingHorizontal:10,paddingVertical:6,borderRadius:20},pillUrgent:{backgroundColor:'rgba(255,197,107,0.12)'},pillText:{color:PREMIUM.colors.mint,fontSize:8,fontWeight:'900',letterSpacing:1},pillUrgentText:{color:PREMIUM.colors.amber},minutes:{color:PREMIUM.colors.muted,fontSize:11,fontWeight:'800'},actionTitle:{color:PREMIUM.colors.ink,fontSize:23,fontWeight:'900',lineHeight:29,marginTop:14},actionMeta:{color:PREMIUM.colors.muted,fontSize:11,lineHeight:17,marginTop:6},primary:{marginTop:18,minHeight:48,borderRadius:24,backgroundColor:PREMIUM.colors.mint,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},confirm:{marginTop:18,minHeight:48,borderRadius:24,backgroundColor:PREMIUM.colors.amber,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},primaryText:{color:PREMIUM.colors.ink,fontWeight:'900',fontSize:12},feedbackLabel:{color:PREMIUM.colors.muted,fontSize:10,fontWeight:'800',marginTop:16},feedback:{flexDirection:'row',gap:8,marginTop:8},feedbackButton:{flex:1,minHeight:42,borderRadius:14,borderWidth:1,borderColor:PREMIUM.colors.border,backgroundColor:'rgba(255,255,255,0.025)',alignItems:'center',justifyContent:'center',gap:4,flexDirection:'row'},feedbackText:{color:PREMIUM.colors.inkSoft,fontSize:10,fontWeight:'800'},clear:{borderRadius:24,borderWidth:1,borderColor:PREMIUM.colors.border,backgroundColor:PREMIUM.colors.surfaceGlass,padding:28,alignItems:'center'},clearTitle:{color:PREMIUM.colors.ink,fontSize:19,fontWeight:'900',marginTop:9},clearText:{color:PREMIUM.colors.muted,fontSize:12,lineHeight:18,textAlign:'center',marginTop:5},section:{color:PREMIUM.colors.muted,fontSize:8,fontWeight:'900',letterSpacing:1.5,marginTop:4}});
