import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Link } from 'expo-router';
import { DailyCommandCenterResponse, generateSmartNotifications, getDailyCommandCenter, hasAuthSession } from '../lib/api';
import { colors, radius, spacing, typography, shadows } from '../lib/design-system';
import { AnimatedIn, MotionPress } from '../lib/motion-components';

export default function DailyCommandCenterScreen() {
  const [data, setData] = useState<DailyCommandCenterResponse | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setError(null); await generateSmartNotifications(); setData(await getDailyCommandCenter()); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load today'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void hasAuthSession().then((ok) => { if (ok) void load(); else setLoading(false); }); }, [load]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.ink} /></View>;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} />}>
    <AnimatedIn><View style={styles.nav}><Link href="/" asChild><MotionPress style={styles.navButton}><Text style={styles.back}>← Home</Text></MotionPress></Link><Link href="/calendar" asChild><MotionPress style={styles.navButton}><Text style={styles.navText}>📅 Calendar</Text></MotionPress></Link><Link href="/notifications" asChild><MotionPress style={styles.navButton}><Text style={styles.navText}>{data?.notifications.unread ? `🔔 ${data.notifications.unread}` : '🔔 Inbox'}</Text></MotionPress></Link></View></AnimatedIn>
    <AnimatedIn delay={80}><Text style={styles.eyebrow}>TODAY</Text><View style={styles.heroRow}><View style={styles.heroCopy}><Text style={styles.title}>Your Command Center</Text><Text style={styles.greeting}>{data?.greeting}</Text></View><Link href="/meals" asChild><MotionPress style={styles.mealsButton}><Text style={styles.mealsButtonText}>🍽️ Meals</Text></MotionPress></Link></View></AnimatedIn>
    {error ? <AnimatedIn delay={140}><View style={[styles.card, shadows.subtle]}><Text style={styles.cardTitle}>Today is unavailable</Text><Text style={styles.body}>{error}</Text><MotionPress onPress={() => void load()} style={styles.button}><Text style={styles.buttonText}>Retry</Text></MotionPress></View></AnimatedIn> : null}
    <AnimatedIn delay={160}><View style={[styles.card, shadows.subtle]}><Text style={styles.cardTitle}>🔥 Top priorities</Text>{data?.priorities.length ? data.priorities.map((item, index) => <AnimatedIn key={`${item}-${index}`} delay={220 + index * 50}><Text style={styles.priority}>{index + 1}. {item}</Text></AnimatedIn>) : <Text style={styles.body}>You are clear for now. Keep the streak going.</Text>}</View></AnimatedIn>
    <AnimatedIn delay={240}><View style={styles.grid}>{[['🍽️','Calories',`${data?.nutrition.calories}${data?.nutrition.calorieGoal ? ` / ${data.nutrition.calorieGoal}` : ''}`],['🥩','Protein',`${data?.nutrition.protein}g${data?.nutrition.proteinGoal ? ` / ${data.nutrition.proteinGoal}g` : ''}`],['💧','Water',`${data?.nutrition.waterMl}ml${data?.nutrition.waterGoalMl ? ` / ${data.nutrition.waterGoalMl}ml` : ''}`],['✅','Habits',`${data?.habits.completed} / ${data?.habits.total}`],['💊','Supplements',`${data?.supplements.taken} / ${data?.supplements.total}`],['⏰','Reminders',`${data?.reminders.pending} pending`]].map(([emoji,label,value], index) => <AnimatedIn key={label} delay={270 + index * 55} style={styles.metricWrap}><Link href={label === 'Calories' || label === 'Protein' ? '/meals' : '/daily'} asChild><MotionPress style={styles.metric}><Text style={styles.metricEmoji}>{emoji}</Text><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></MotionPress></Link></AnimatedIn>)}</View></AnimatedIn>
    <AnimatedIn delay={560}><View style={[styles.card, shadows.subtle]}><View style={styles.sectionHeader}><View><Text style={styles.cardTitle}>📅 Today's schedule</Text><Text style={styles.body}>Events from your assistant calendar.</Text></View><Link href="/calendar" asChild><MotionPress><Text style={styles.linkText}>Open calendar →</Text></MotionPress></Link></View>{data?.calendar.today.length ? data.calendar.today.map((event, index) => <AnimatedIn key={event.id} delay={600 + index * 60}><View style={styles.scheduleItem}><View style={styles.scheduleTime}><Text style={styles.time}>{new Date(event.scheduledAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text></View><View style={styles.scheduleCopy}><Text style={styles.scheduleTitle}>{event.title}</Text><Text style={styles.scheduleType}>{event.type}</Text></View></View></AnimatedIn>) : <Text style={styles.body}>Nothing scheduled today. Nice and clean. ✨</Text>}</View></AnimatedIn>
    <AnimatedIn delay={700}><View style={[styles.card, shadows.subtle]}><Text style={styles.cardTitle}>Next up</Text>{data?.calendar.next ? <Text style={styles.body}>📅 {data.calendar.next.title} · {new Date(data.calendar.next.scheduledAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text> : data?.reminders.next ? <Text style={styles.body}>⏰ {data.reminders.next.title} · {new Date(data.reminders.next.scheduledAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text> : <Text style={styles.body}>No upcoming schedule items.</Text>}{data?.workouts.latest ? <Text style={styles.body}>🏋️ Latest workout: {data.workouts.latest.name} · {data.workouts.latest.durationMinutes} min</Text> : <Text style={styles.body}>🏃 No workout logged yet today.</Text>}</View></AnimatedIn>
    <AnimatedIn delay={760}><View style={styles.links}>{[['/meals','🍽️ Meals & Nutrition →'],['/calendar','📅 Calendar →'],['/notifications','Notification Inbox →'],['/habits','Habits →'],['/supplements','Supplements →'],['/reminders','Reminders →']].map(([href,label]) => <Link key={href} href={href as any} asChild><MotionPress style={styles.link}><Text style={styles.linkText}>{label}</Text></MotionPress></Link>)}</View></AnimatedIn>
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:colors.paper},content:{padding:spacing.xl,gap:spacing.md,paddingBottom:36},nav:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:8},navButton:{paddingVertical:8,paddingHorizontal:8},back:{fontWeight:'800',color:colors.text},navText:{fontWeight:'900',color:colors.text,fontSize:11},eyebrow:{...typography.eyebrow,color:colors.textMuted},heroRow:{flexDirection:'row',alignItems:'flex-end',gap:12},heroCopy:{flex:1},title:{...typography.title1,color:colors.text},greeting:{...typography.body,color:colors.textMuted,marginTop:4},mealsButton:{backgroundColor:colors.ink,borderRadius:radius.md,paddingHorizontal:13,paddingVertical:11},mealsButtonText:{color:colors.surface,fontWeight:'900',fontSize:11},card:{backgroundColor:colors.surface,borderRadius:radius.xl,padding:18,gap:8,borderWidth:1,borderColor:colors.border},cardTitle:{fontSize:17,fontWeight:'900',color:colors.text},body:{fontSize:13,lineHeight:20,color:colors.textMuted},priority:{fontSize:14,lineHeight:22,color:colors.text,fontWeight:'700'},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},metricWrap:{width:'31.5%'},metric:{backgroundColor:colors.surface,borderRadius:radius.lg,padding:14,minHeight:112,borderWidth:1,borderColor:colors.border},metricEmoji:{fontSize:22},metricLabel:{fontSize:11,fontWeight:'700',color:colors.textMuted,marginTop:8},metricValue:{fontSize:15,fontWeight:'900',color:colors.text,marginTop:4},sectionHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:10},linkText:{color:colors.text,fontWeight:'900',fontSize:11},scheduleItem:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:7},scheduleTime:{width:72},time:{fontSize:14,fontWeight:'900',color:colors.text},scheduleCopy:{flex:1},scheduleTitle:{fontSize:14,fontWeight:'800',color:colors.text},scheduleType:{fontSize:10,color:colors.textMuted,fontWeight:'800',textTransform:'uppercase',marginTop:2},links:{gap:10},link:{backgroundColor:colors.ink,padding:14,borderRadius:radius.md},button:{alignSelf:'flex-start',backgroundColor:colors.ink,paddingHorizontal:14,paddingVertical:10,borderRadius:radius.md},buttonText:{color:colors.surface,fontWeight:'900'}});