import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Link } from 'expo-router';
import { DailyCommandCenterResponse, generateSmartNotifications, getDailyCommandCenter, hasAuthSession } from '../lib/api';
import { colors, radius, spacing, typography, shadows } from '../lib/design-system';
import { AnimatedIn, MotionPress } from '../lib/motion-components';
import { AppLocale, getStoredLocale, isRTL } from '../lib/i18n';

const copy = {
  en: {
    home:'← Home', calendar:'📅 Calendar', inbox:'🔔 Inbox', today:'TODAY', title:'Your Command Center', meals:'🍽️ Meals', unavailable:'Today is unavailable', retry:'Retry', priorities:'🔥 Top priorities', clear:'You are clear for now. Keep the streak going.', calories:'Calories', protein:'Protein', water:'Water', habits:'Habits', supplements:'Supplements', reminders:'Reminders', pending:'pending', schedule:"📅 Today's schedule", scheduleHint:'Events from your assistant calendar.', openCalendar:'Open calendar →', emptySchedule:'Nothing scheduled today. Nice and clean. ✨', next:'Next up', noUpcoming:'No upcoming schedule items.', latestWorkout:'🏋️ Latest workout', noWorkout:'🏃 No workout logged yet today.', linksMeals:'🍽️ Meals & Nutrition →', linksCalendar:'📅 Calendar →', linksNotifications:'Notification Inbox →', linksHabits:'Habits →', linksSupplements:'Supplements →', linksReminders:'Reminders →', loadError:'Unable to load today', loading:'Loading today', actionError:'Unable to load today.'
  },
  fa: {
    home:'خانه ←', calendar:'تقویم 📅', inbox:'صندوق اعلان 🔔', today:'امروز', title:'مرکز فرمان دستیار من', meals:'وعده‌ها 🍽️', unavailable:'امروز در دسترس نیست', retry:'تلاش دوباره', priorities:'🔥 اولویت‌های امروز', clear:'فعلاً مورد فوری‌ای نداری؛ روندت را ادامه بده.', calories:'کالری', protein:'پروتئین', water:'آب', habits:'عادت‌ها', supplements:'مکمل‌ها', reminders:'یادآوری‌ها', pending:'در انتظار', schedule:'📅 برنامه امروز', scheduleHint:'رویدادهای تقویم دستیار تو.', openCalendar:'باز کردن تقویم ←', emptySchedule:'امروز برنامه‌ای ثبت نشده؛ مرتب و تمیز. ✨', next:'بعدی', noUpcoming:'مورد زمان‌بندی‌شده‌ای باقی نمانده.', latestWorkout:'🏋️ آخرین تمرین', noWorkout:'🏃 امروز هنوز تمرینی ثبت نشده.', linksMeals:'🍽️ وعده‌ها و تغذیه ←', linksCalendar:'📅 تقویم ←', linksNotifications:'صندوق اعلان ←', linksHabits:'عادت‌ها ←', linksSupplements:'مکمل‌ها ←', linksReminders:'یادآوری‌ها ←', loadError:'بارگذاری امروز انجام نشد', loading:'در حال بارگذاری امروز', actionError:'بارگذاری امروز انجام نشد.'
  }
} as const;

export default function DailyCommandCenterScreen() {
  const [locale, setLocale] = useState<AppLocale>('en');
  const [data, setData] = useState<DailyCommandCenterResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    try { setError(null); await generateSmartNotifications(); setData(await getDailyCommandCenter()); }
    catch (err) { setError(err instanceof Error ? err.message : 'Unable to load today'); }
    finally { setLoading(false); setRefreshing(false); }
  }, []);

  useEffect(() => { void getStoredLocale().then((stored) => setLocale(stored ?? 'en')); void hasAuthSession().then((ok) => { if (ok) void load(); else setLoading(false); }); }, [load]);

  const text = copy[locale];
  const rtl = isRTL(locale);
  if (loading) return <View style={styles.center} accessibilityLabel={text.loading}><ActivityIndicator size="large" color={colors.ink} /></View>;

  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} />}>
    <AnimatedIn><View style={[styles.nav, rtl && styles.rtl]}><Link href="/" asChild><MotionPress style={styles.navButton}><Text style={styles.back}>{text.home}</Text></MotionPress></Link><Link href="/calendar" asChild><MotionPress style={styles.navButton}><Text style={styles.navText}>{text.calendar}</Text></MotionPress></Link><Link href="/notifications" asChild><MotionPress style={styles.navButton}><Text style={styles.navText}>{data?.notifications.unread ? `🔔 ${data.notifications.unread}` : text.inbox}</Text></MotionPress></Link></View></AnimatedIn>
    <AnimatedIn delay={80}><Text style={[styles.eyebrow, rtl && styles.rtlText]}>{text.today}</Text><View style={[styles.heroRow, rtl && styles.rtl]}><View style={styles.heroCopy}><Text style={[styles.title, rtl && styles.rtlText]}>{text.title}</Text><Text style={[styles.greeting, rtl && styles.rtlText]}>{data?.greeting}</Text></View><Link href="/meals" asChild><MotionPress style={styles.mealsButton}><Text style={styles.mealsButtonText}>{text.meals}</Text></MotionPress></Link></View></AnimatedIn>
    {error ? <AnimatedIn delay={140}><View style={[styles.card, shadows.subtle]}><Text style={[styles.cardTitle, rtl && styles.rtlText]}>{text.unavailable}</Text><Text style={[styles.body, rtl && styles.rtlText]}>{error || text.actionError}</Text><MotionPress onPress={() => void load()} style={styles.button}><Text style={styles.buttonText}>{text.retry}</Text></MotionPress></View></AnimatedIn> : null}
    <AnimatedIn delay={160}><View style={[styles.card, shadows.subtle]}><Text style={[styles.cardTitle, rtl && styles.rtlText]}>{text.priorities}</Text>{data?.priorities.length ? data.priorities.map((item, index) => <AnimatedIn key={`${item}-${index}`} delay={220 + index * 50}><Text style={[styles.priority, rtl && styles.rtlText]}>{index + 1}. {item}</Text></AnimatedIn>) : <Text style={[styles.body, rtl && styles.rtlText]}>{text.clear}</Text>}</View></AnimatedIn>
    <AnimatedIn delay={240}><View style={[styles.grid, rtl && styles.rtl]}>{[["🍽️",text.calories,`${data?.nutrition.calories}${data?.nutrition.calorieGoal ? ` / ${data.nutrition.calorieGoal}` : ''}`],["🥩",text.protein,`${data?.nutrition.protein}g${data?.nutrition.proteinGoal ? ` / ${data.nutrition.proteinGoal}g` : ''}`],["💧",text.water,`${data?.nutrition.waterMl}ml${data?.nutrition.waterGoalMl ? ` / ${data.nutrition.waterGoalMl}ml` : ''}`],["✅",text.habits,`${data?.habits.completed} / ${data?.habits.total}`],["💊",text.supplements,`${data?.supplements.taken} / ${data?.supplements.total}`],["⏰",text.reminders,`${data?.reminders.pending} ${text.pending}`]].map(([emoji,label,value], index) => <AnimatedIn key={label} delay={270 + index * 55} style={styles.metricWrap}><Link href={label === text.calories || label === text.protein ? '/meals' : '/daily'} asChild><MotionPress style={styles.metric}><Text style={styles.metricEmoji}>{emoji}</Text><Text style={[styles.metricLabel, rtl && styles.rtlText]}>{label}</Text><Text style={[styles.metricValue, rtl && styles.rtlText]}>{value}</Text></MotionPress></Link></AnimatedIn>)}</View></AnimatedIn>
    <AnimatedIn delay={560}><View style={[styles.card, shadows.subtle]}><View style={[styles.sectionHeader, rtl && styles.rtl]}><View style={styles.sectionCopy}><Text style={[styles.cardTitle, rtl && styles.rtlText]}>{text.schedule}</Text><Text style={[styles.body, rtl && styles.rtlText]}>{text.scheduleHint}</Text></View><Link href="/calendar" asChild><MotionPress><Text style={[styles.linkText, rtl && styles.rtlText]}>{text.openCalendar}</Text></MotionPress></Link></View>{data?.calendar.today.length ? data.calendar.today.map((event, index) => <AnimatedIn key={event.id} delay={600 + index * 60}><View style={[styles.scheduleItem, rtl && styles.rtl]}><View style={styles.scheduleTime}><Text style={styles.time}>{new Date(event.scheduledAt).toLocaleTimeString(locale === 'fa' ? 'fa-IR' : undefined, { hour: '2-digit', minute: '2-digit' })}</Text></View><View style={styles.scheduleCopy}><Text style={[styles.scheduleTitle, rtl && styles.rtlText]}>{event.title}</Text><Text style={[styles.scheduleType, rtl && styles.rtlText]}>{event.type}</Text></View></View></AnimatedIn>) : <Text style={[styles.body, rtl && styles.rtlText]}>{text.emptySchedule}</Text>}</View></AnimatedIn>
    <AnimatedIn delay={700}><View style={styles.card}><Text style={[styles.cardTitle, rtl && styles.rtlText]}>{text.next}</Text>{data?.calendar.next ? <Text style={[styles.body, rtl && styles.rtlText]}>📅 {data.calendar.next.title} · {new Date(data.calendar.next.scheduledAt).toLocaleTimeString(locale === 'fa' ? 'fa-IR' : undefined, { hour: '2-digit', minute: '2-digit' })}</Text> : data?.reminders.next ? <Text style={[styles.body, rtl && styles.rtlText]}>⏰ {data.reminders.next.title} · {new Date(data.reminders.next.scheduledAt).toLocaleTimeString(locale === 'fa' ? 'fa-IR' : undefined, { hour: '2-digit', minute: '2-digit' })}</Text> : <Text style={[styles.body, rtl && styles.rtlText]}>{text.noUpcoming}</Text>}{data?.workouts.latest ? <Text style={[styles.body, rtl && styles.rtlText]}>{text.latestWorkout}: {data.workouts.latest.name} · {data.workouts.latest.durationMinutes} min</Text> : <Text style={[styles.body, rtl && styles.rtlText]}>{text.noWorkout}</Text>}</View></AnimatedIn>
    <AnimatedIn delay={760}><View style={styles.links}>{[["/meals",text.linksMeals],["/calendar",text.linksCalendar],["/notifications",text.linksNotifications],["/habits",text.linksHabits],["/supplements",text.linksSupplements],["/reminders",text.linksReminders]].map(([href,label]) => <Link key={href} href={href as any} asChild><MotionPress style={styles.link}><Text style={[styles.linkText, rtl && styles.rtlText]}>{label}</Text></MotionPress></Link>)}</View></AnimatedIn>
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:colors.paper},content:{padding:spacing.xl,gap:spacing.md,paddingBottom:36},nav:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:8},rtl:{flexDirection:'row-reverse'},navButton:{paddingVertical:8,paddingHorizontal:8},back:{fontWeight:'800',color:colors.text},navText:{fontWeight:'900',color:colors.text,fontSize:11},eyebrow:{...typography.eyebrow,color:colors.textMuted},rtlText:{textAlign:'right',direction:'rtl'},heroRow:{flexDirection:'row',alignItems:'flex-end',gap:12},heroCopy:{flex:1},title:{...typography.title1,color:colors.text},greeting:{...typography.body,color:colors.textMuted,marginTop:4},mealsButton:{backgroundColor:colors.ink,borderRadius:radius.md,paddingHorizontal:13,paddingVertical:11},mealsButtonText:{color:colors.surface,fontWeight:'900',fontSize:11},card:{backgroundColor:colors.surface,borderRadius:radius.xl,padding:18,gap:8,borderWidth:1,borderColor:colors.border},cardTitle:{fontSize:17,fontWeight:'900',color:colors.text},body:{fontSize:13,lineHeight:20,color:colors.textMuted},priority:{fontSize:14,lineHeight:22,color:colors.text,fontWeight:'700'},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},metricWrap:{width:'31.5%'},metric:{backgroundColor:colors.surface,borderRadius:radius.lg,padding:14,minHeight:112,borderWidth:1,borderColor:colors.border},metricEmoji:{fontSize:22},metricLabel:{fontSize:11,fontWeight:'700',color:colors.textMuted,marginTop:8},metricValue:{fontSize:15,fontWeight:'900',color:colors.text,marginTop:4},sectionHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:10},sectionCopy:{flex:1},linkText:{color:colors.text,fontWeight:'900',fontSize:11},scheduleItem:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:7},scheduleTime:{width:72},time:{fontSize:14,fontWeight:'900',color:colors.text},scheduleCopy:{flex:1},scheduleTitle:{fontSize:14,fontWeight:'800',color:colors.text},scheduleType:{fontSize:10,color:colors.textMuted,fontWeight:'800',textTransform:'uppercase',marginTop:2},links:{gap:10},link:{backgroundColor:colors.ink,padding:14,borderRadius:radius.md},button:{alignSelf:'flex-start',backgroundColor:colors.ink,paddingHorizontal:14,paddingVertical:10,borderRadius:radius.md},buttonText:{color:colors.surface,fontWeight:'900'}});