import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Link } from 'expo-router';
import { DailyCommandCenterResponse, generateSmartNotifications, getDailyCommandCenter, hasAuthSession } from '../lib/api';
import { useAppLocale } from '../lib/i18n';
import { colors, radius, spacing, typography, shadows } from '../lib/design-system';
import { AnimatedIn, MotionPress } from '../lib/motion-components';

const copy = {
  en: { home:'Home', calendar:'Calendar', inbox:'Inbox', today:'TODAY', command:'Your Command Center', unavailable:'Today is unavailable', retry:'Retry', priorities:'🔥 Top priorities', clear:'You are clear for now. Keep the streak going.', calories:'Calories', protein:'Protein', water:'Water', habits:'Habits', supplements:'Supplements', reminders:'Reminders', pending:'pending', schedule:"📅 Today's schedule", scheduleHint:'Events from your assistant calendar.', openCalendar:'Open calendar →', emptySchedule:'Nothing scheduled today. Nice and clean. ✨', next:'Next up', none:'No upcoming schedule items.', latestWorkout:'Latest workout', noWorkout:'No workout logged yet today.', meals:'Meals & Nutrition →', notificationInbox:'Notification Inbox →', loading:'Loading' },
  fa: { home:'خانه', calendar:'تقویم', inbox:'اعلان‌ها', today:'امروز', command:'مرکز فرمان دستیار من', unavailable:'امروز در دسترس نیست', retry:'تلاش دوباره', priorities:'🔥 اولویت‌های امروز', clear:'فعلاً کار فوری‌ای نداری. همین روند خوبه.', calories:'کالری', protein:'پروتئین', water:'آب', habits:'عادت‌ها', supplements:'مکمل‌ها', reminders:'یادآوری‌ها', pending:'در انتظار', schedule:'📅 برنامه امروز', scheduleHint:'رویدادهای تقویم دستیار تو.', openCalendar:'باز کردن تقویم ←', emptySchedule:'امروز چیزی در برنامه نیست. عالیه ✨', next:'بعدی', none:'مورد برنامه‌ریزی‌شده‌ای برای بعد نداریم.', latestWorkout:'آخرین تمرین', noWorkout:'امروز هنوز تمرینی ثبت نکردی.', meals:'غذا و تغذیه ←', notificationInbox:'صندوق اعلان‌ها ←', loading:'در حال بارگذاری' },
} as const;

type DailyCopy = typeof copy.en;

export default function DailyCommandCenterScreen() {
  const locale = useAppLocale();
  const text = copy[locale] as DailyCopy;
  const rtl = locale === 'fa';
  const [data, setData] = useState<DailyCommandCenterResponse | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setError(null); await generateSmartNotifications(); setData(await getDailyCommandCenter()); } catch (err) { setError(err instanceof Error ? err.message : (locale === 'fa' ? 'بارگذاری امروز ناموفق بود.' : 'Unable to load today')); } finally { setLoading(false); setRefreshing(false); } }, [locale]);
  useEffect(() => { void hasAuthSession().then((ok) => { if (ok) void load(); else setLoading(false); }); }, [load]);
  const metrics = useMemo(() => [['🍽️',text.calories,`${data?.nutrition.calories ?? 0}${data?.nutrition.calorieGoal ? ` / ${data.nutrition.calorieGoal}` : ''}`,'/meals'],['🥩',text.protein,`${data?.nutrition.protein ?? 0}g${data?.nutrition.proteinGoal ? ` / ${data.nutrition.proteinGoal}g` : ''}`,'/meals'],['💧',text.water,`${data?.nutrition.waterMl ?? 0}ml${data?.nutrition.waterGoalMl ? ` / ${data.nutrition.waterGoalMl}ml` : ''}`,'/daily'],['✅',text.habits,`${data?.habits.completed ?? 0} / ${data?.habits.total ?? 0}`,'/habits'],['💊',text.supplements,`${data?.supplements.taken ?? 0} / ${data?.supplements.total ?? 0}`,'/supplements'],['⏰',text.reminders,`${data?.reminders.pending ?? 0} ${text.pending}`,'/reminders']] as const, [data, text]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.ink} accessibilityLabel={text.loading} /></View>;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} />}>
    <AnimatedIn><View style={[styles.nav, rtl ? styles.rtl : undefined]}><Link href="/" asChild><MotionPress style={styles.navButton}><Text style={styles.back}>{rtl ? '→ ' : '← '}{text.home}</Text></MotionPress></Link><Link href="/calendar" asChild><MotionPress style={styles.navButton}><Text style={styles.navText}>📅 {text.calendar}</Text></MotionPress></Link><Link href="/notifications" asChild><MotionPress style={styles.navButton}><Text style={styles.navText}>{data?.notifications.unread ? `🔔 ${data.notifications.unread}` : `🔔 ${text.inbox}`}</Text></MotionPress></Link></View></AnimatedIn>
    <AnimatedIn delay={80}><Text style={[styles.eyebrow, rtl ? styles.rtl : undefined]}>{text.today}</Text><View style={[styles.heroRow, rtl ? styles.rtl : undefined]}><View style={styles.heroCopy}><Text style={[styles.title, rtl ? styles.rtl : undefined]}>{text.command}</Text><Text style={[styles.greeting, rtl ? styles.rtl : undefined]}>{data?.greeting}</Text></View><Link href="/meals" asChild><MotionPress style={styles.mealsButton}><Text style={styles.mealsButtonText}>{locale === 'fa' ? '🍽️ غذاها' : '🍽️ Meals'}</Text></MotionPress></Link></View></AnimatedIn>
    {error ? <AnimatedIn delay={140}><View style={[styles.card, shadows.subtle]}><Text style={[styles.cardTitle, rtl ? styles.rtl : undefined]}>{text.unavailable}</Text><Text style={[styles.body, rtl ? styles.rtl : undefined]}>{error}</Text><MotionPress onPress={() => void load()} style={styles.button}><Text style={styles.buttonText}>{text.retry}</Text></MotionPress></View></AnimatedIn> : null}
    <AnimatedIn delay={160}><View style={[styles.card, shadows.subtle]}><Text style={[styles.cardTitle, rtl ? styles.rtl : undefined]}>{text.priorities}</Text>{data?.priorities.length ? data.priorities.map((item, index) => <AnimatedIn key={`${item}-${index}`} delay={220 + index * 50}><Text style={[styles.priority, rtl ? styles.rtl : undefined]}>{index + 1}. {item}</Text></AnimatedIn>) : <Text style={[styles.body, rtl ? styles.rtl : undefined]}>{text.clear}</Text>}</View></AnimatedIn>
    <AnimatedIn delay={240}><View style={styles.grid}>{metrics.map(([emoji,label,value,href], index) => <AnimatedIn key={label} delay={270 + index * 55} style={styles.metricWrap}><Link href={href as never} asChild><MotionPress style={[styles.metric, rtl ? styles.rtl : undefined]}><Text style={styles.metricEmoji}>{emoji}</Text><Text style={[styles.metricLabel, rtl ? styles.rtl : undefined]}>{label}</Text><Text style={[styles.metricValue, rtl ? styles.rtl : undefined]}>{value}</Text></MotionPress></Link></AnimatedIn>)}</View></AnimatedIn>
    <AnimatedIn delay={560}><View style={[styles.card, shadows.subtle]}><View style={[styles.sectionHeader, rtl ? styles.rtl : undefined]}><View style={styles.flex}><Text style={[styles.cardTitle, rtl ? styles.rtl : undefined]}>{text.schedule}</Text><Text style={[styles.body, rtl ? styles.rtl : undefined]}>{text.scheduleHint}</Text></View><Link href="/calendar" asChild><MotionPress><Text style={styles.linkText}>{text.openCalendar}</Text></MotionPress></Link></View>{data?.calendar.today.length ? data.calendar.today.map((event, index) => <AnimatedIn key={event.id} delay={600 + index * 60}><View style={[styles.scheduleItem, rtl ? styles.rtl : undefined]}><View style={styles.scheduleTime}><Text style={styles.time}>{new Date(event.scheduledAt).toLocaleTimeString([], { hour:'2-digit', minute:'2-digit' })}</Text></View><View style={styles.scheduleCopy}><Text style={[styles.scheduleTitle, rtl ? styles.rtl : undefined]}>{event.title}</Text><Text style={[styles.scheduleType, rtl ? styles.rtl : undefined]}>{event.type}</Text></View></View></AnimatedIn>) : <Text style={[styles.body, rtl ? styles.rtl : undefined]}>{text.emptySchedule}</Text>}</View></AnimatedIn>
    <AnimatedIn delay={700}><View style={[styles.card, shadows.subtle]}><Text style={[styles.cardTitle, rtl ? styles.rtl : undefined]}>{text.next}</Text>{data?.calendar.next ? <Text style={[styles.body, rtl ? styles.rtl : undefined]}>📅 {data.calendar.next.title} · {new Date(data.calendar.next.scheduledAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</Text> : data?.reminders.next ? <Text style={[styles.body, rtl ? styles.rtl : undefined]}>⏰ {data.reminders.next.title} · {new Date(data.reminders.next.scheduledAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</Text> : <Text style={[styles.body, rtl ? styles.rtl : undefined]}>{text.none}</Text>}{data?.workouts.latest ? <Text style={[styles.body, rtl ? styles.rtl : undefined]}>🏋️ {text.latestWorkout}: {data.workouts.latest.name} · {data.workouts.latest.durationMinutes} min</Text> : <Text style={[styles.body, rtl ? styles.rtl : undefined]}>🏃 {text.noWorkout}</Text>}</View></AnimatedIn>
    <AnimatedIn delay={760}><View style={styles.links}>{[['/meals',text.meals],['/calendar',`📅 ${text.calendar} →`],['/notifications',text.notificationInbox],['/habits',`${text.habits} →`],['/supplements',`${text.supplements} →`],['/reminders',`${text.reminders} →`]].map(([href,label]) => <Link key={href} href={href as never} asChild><MotionPress style={styles.link}><Text style={[styles.linkText, rtl ? styles.rtl : undefined]}>{label}</Text></MotionPress></Link>)}</View></AnimatedIn>
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:colors.paper},content:{padding:spacing.xl,gap:spacing.md,paddingBottom:36},nav:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:8},navButton:{paddingVertical:8,paddingHorizontal:8},back:{fontWeight:'800',color:colors.text},navText:{fontWeight:'900',color:colors.text,fontSize:11},eyebrow:{...typography.eyebrow,color:colors.textMuted},heroRow:{flexDirection:'row',alignItems:'flex-end',gap:12},heroCopy:{flex:1},flex:{flex:1},rtl:{direction:'rtl'},title:{...typography.title1,color:colors.text},greeting:{...typography.body,color:colors.textMuted,marginTop:4},mealsButton:{backgroundColor:colors.ink,borderRadius:radius.md,paddingHorizontal:13,paddingVertical:11},mealsButtonText:{color:colors.surface,fontWeight:'900',fontSize:11},card:{backgroundColor:colors.surface,borderRadius:radius.xl,padding:18,gap:8,borderWidth:1,borderColor:colors.border},cardTitle:{fontSize:17,fontWeight:'900',color:colors.text},body:{fontSize:13,lineHeight:20,color:colors.textMuted},priority:{fontSize:14,lineHeight:22,color:colors.text,fontWeight:'700'},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},metricWrap:{width:'31.5%'},metric:{backgroundColor:colors.surface,borderRadius:radius.lg,padding:14,minHeight:112,borderWidth:1,borderColor:colors.border},metricEmoji:{fontSize:22},metricLabel:{fontSize:11,fontWeight:'700',color:colors.textMuted,marginTop:8},metricValue:{fontSize:15,fontWeight:'900',color:colors.text,marginTop:4},sectionHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:10},linkText:{color:colors.text,fontWeight:'900',fontSize:11},scheduleItem:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:7},scheduleTime:{width:72},time:{fontSize:14,fontWeight:'900',color:colors.text},scheduleCopy:{flex:1},scheduleTitle:{fontSize:14,fontWeight:'800',color:colors.text},scheduleType:{fontSize:10,color:colors.textMuted,fontWeight:'800',textTransform:'uppercase',marginTop:2},links:{gap:10},link:{backgroundColor:colors.ink,padding:14,borderRadius:radius.md},button:{alignSelf:'flex-start',backgroundColor:colors.ink,paddingHorizontal:14,paddingVertical:10,borderRadius:radius.md},buttonText:{color:colors.surface,fontWeight:'900'}});
