import { useEffect, useState } from 'react';
import { ActivityIndicator, Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { getFitnessExercise, FitnessDiscipline, FitnessItem } from '../lib/fitness-api';
import { useAppLocale } from '../lib/i18n';

const copy={en:{back:'Back',loading:'Loading exercise…',instructions:'How to perform',cues:'Coach cues',media:'Form images',coverage:'image coverage',source:'Source',partial:'More verified images are still needed for the 4-image standard.',error:'Exercise unavailable.'},fa:{back:'برگشت',loading:'در حال بارگذاری حرکت…',instructions:'روش صحیح اجرا',cues:'نکات مربی',media:'تصاویر اجرای صحیح',coverage:'پوشش تصاویر',source:'منبع',partial:'برای استاندارد ۴ تصویر، هنوز تصویر معتبر بیشتری لازم است.',error:'حرکت در دسترس نیست.'}} as const;

export default function ExerciseScreen(){
 const locale=useAppLocale();const text=copy[locale];const params=useLocalSearchParams<{discipline?:string;id?:string}>();const discipline=(params.discipline==='calisthenics'||params.discipline==='yoga'?'calisthenics': 'gym') as FitnessDiscipline;const [item,setItem]=useState<FitnessItem|null>(null);const [error,setError]=useState<string|null>(null);
 useEffect(()=>{if(!params.id)return;void getFitnessExercise(discipline,String(params.id)).then(setItem).catch(err=>setError(err instanceof Error?err.message:text.error));},[discipline,params.id,text.error]);
 if(!item&&!error)return <View style={styles.center}><ActivityIndicator size="large"/><Text style={styles.loading}>{text.loading}</Text></View>;
 if(error)return <SafeAreaView style={styles.safe}><Text style={styles.error}>{error}</Text><Pressable style={styles.button} onPress={()=>router.back()}><Text style={styles.buttonText}>{text.back}</Text></Pressable></SafeAreaView>;
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={()=>router.back()}><Text style={styles.back}>{locale==='fa'?'→':'←'} {text.back}</Text></Pressable><View style={styles.titleRow}><Text style={styles.title}>{item!.name}</Text><Text style={styles.level}>{item!.difficultyLevel}/10</Text></View><Text style={styles.source}>{text.source}: {item!.source.provider}</Text>
   <Text style={styles.section}>{text.media}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.mediaRow}>{item!.media.map(media=><View key={media.position} style={styles.mediaCard}><Image source={{uri:media.webpUrl}} style={styles.media}/><Text style={styles.mediaLabel}>{media.position}</Text></View>)}</ScrollView><Text style={styles.coverage}>{item!.mediaActual}/{item!.mediaRequired} {text.coverage}</Text>{!item!.mediaComplete?<Text style={styles.warning}>{text.partial}</Text>:null}
   {item!.instructions.length?<><Text style={styles.section}>{text.instructions}</Text>{item!.instructions.map((line,index)=><View style={styles.row} key={`${index}-${line}`}><Text style={styles.number}>{index+1}</Text><Text style={styles.body}>{line}</Text></View>)}</>:null}
   {item!.cues.length?<><Text style={styles.section}>{text.cues}</Text>{item!.cues.map((cue,index)=><View style={styles.bullet} key={`${index}-${cue}`}><Text style={styles.dot}>•</Text><Text style={styles.body}>{cue}</Text></View>)}</>:null}
   <View style={styles.tags}>{item!.focus.map(tag=><Text key={tag} style={styles.tag}>{tag}</Text>)}</View>
 </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F8FA'},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F7F8FA'},loading:{marginTop:10,color:'#6B7280'},content:{padding:20,paddingBottom:40},back:{fontWeight:'900',color:'#111827',marginBottom:15},titleRow:{flexDirection:'row',alignItems:'center',gap:10},title:{flex:1,fontSize:30,fontWeight:'900',color:'#111827'},level:{fontSize:12,fontWeight:'900',color:'#4338CA',backgroundColor:'#EEF2FF',paddingHorizontal:9,paddingVertical:6,borderRadius:10},source:{fontSize:10,color:'#9CA3AF',marginTop:7},section:{fontSize:18,fontWeight:'900',color:'#111827',marginTop:22,marginBottom:10},mediaRow:{gap:10},mediaCard:{width:170,height:170,borderRadius:18,overflow:'hidden',backgroundColor:'#FFF',borderWidth:1,borderColor:'#E5E7EB'},media:{width:'100%',height:'100%'},mediaLabel:{position:'absolute',right:8,top:8,backgroundColor:'#111827AA',color:'#FFF',fontWeight:'900',paddingHorizontal:7,paddingVertical:4,borderRadius:8},coverage:{fontSize:10,color:'#6B7280',marginTop:7},warning:{fontSize:11,lineHeight:17,color:'#92400E',backgroundColor:'#FEF3C7',padding:10,borderRadius:10,marginTop:8},row:{flexDirection:'row',gap:10,marginBottom:11,alignItems:'flex-start'},number:{width:25,height:25,borderRadius:13,backgroundColor:'#111827',color:'#FFF',fontWeight:'900',textAlign:'center',paddingTop:4,fontSize:11},body:{flex:1,fontSize:14,lineHeight:21,color:'#374151'},bullet:{flexDirection:'row',gap:8,marginBottom:8},dot:{color:'#0F766E',fontSize:20,lineHeight:20},tags:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:18},tag:{backgroundColor:'#FFF',paddingHorizontal:9,paddingVertical:6,borderRadius:10,color:'#4B5563',fontSize:10},error:{margin:20,color:'#991B1B',fontWeight:'800'},button:{margin:20,backgroundColor:'#111827',padding:14,borderRadius:14,alignItems:'center'},buttonText:{color:'#FFF',fontWeight:'900'}});
