import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { useAppLocale } from '../lib/i18n';
import { getCurrentFitnessProgram, getFitnessPrograms, FitnessCurrentProgram, FitnessProgram } from '../lib/fitness-content-api';
import { hasAuthSession } from '../lib/api';
import { BRAND } from '../lib/branding';
import { localizedCopy } from '../lib/localized-copy';
import { FitnessLocalizedText } from '../components/fitness-localized-text';

const ui = localizedCopy({
  en: { eyebrow:'PROGRAMS', title:'Choose your path', subtitle:'Structured plans with goals, weeks, sessions and progress built in.', current:'Current plan', next:'Next session', noCurrent:'No active program yet.', catalog:'Program library', start:'Explore', calc:'Calculators', back:'Back', loading:'Loading programs…', empty:'No programs match your filters.' },
  fa: { eyebrow:'برنامه‌ها', title:'مسیرت را انتخاب کن', subtitle:'برنامه‌های ساختاریافته با هدف، هفته، جلسه و پیشرفت.', current:'برنامه فعلی', next:'جلسه بعدی', noCurrent:'هنوز برنامه فعالی نداری.', catalog:'کتابخانه برنامه‌ها', start:'مشاهده', calc:'محاسبات', back:'برگشت', loading:'در حال بارگذاری برنامه‌ها…', empty:'برنامه‌ای با این شرایط پیدا نشد.' },
});

export default function FitnessProgramsScreen() {
  const { locale, rtl } = useAppLocale(); const text=ui[locale];
  const [items,setItems]=useState<FitnessProgram[]>([]); const [current,setCurrent]=useState<FitnessCurrentProgram|null>(null); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false);
  const load=useCallback(async()=>{ try { const [programs, active]=await Promise.all([getFitnessPrograms({limit:30}),getCurrentFitnessProgram()]); setItems(programs.items); setCurrent(active); } finally { setLoading(false); setRefreshing(false); } },[]);
  useEffect(()=>{ void hasAuthSession().then(ok=>{ if(!ok){router.replace('/auth');return;} void load(); }); },[load]);
  if(loading) return <View style={styles.center}><ActivityIndicator size="large" color={BRAND.colors.primaryStrong}/><Text style={styles.centerText}>{text.loading}</Text></View>;
  return <SafeAreaView style={styles.safe}>
    <View style={styles.header}><Pressable onPress={()=>router.back()}><Text style={styles.back}>{rtl?'→':'←'} {text.back}</Text></Pressable><Text style={[styles.eyebrow,rtl&&styles.rtl]}>{text.eyebrow}</Text><Text style={[styles.title,rtl&&styles.rtl]}>{text.title}</Text><Text style={[styles.subtitle,rtl&&styles.rtl]}>{text.subtitle}</Text></View>
    {current ? <View style={styles.current}><View style={styles.currentTop}><Text style={[styles.currentLabel,rtl&&styles.rtl]}>{text.current}</Text><View style={styles.active}><Text style={styles.activeText}>{current.status.toUpperCase()}</Text></View></View><FitnessLocalizedText en={current.name} fa={current.nameFa} locale={locale} style={{...styles.currentTitle, ...(rtl ? styles.rtl : {})}} /><Text style={[styles.currentMeta,rtl&&styles.rtl]}>{current.currentWeek}/{current.durationWeeks} · {current.completedSessions} {text.sessionsDone}</Text>{current.sessionId?<View style={styles.next}><Text style={[styles.nextLabel,rtl&&styles.rtl]}>{text.next}</Text><Text style={[styles.nextTitle,rtl&&styles.rtl]}>{current.sessionTitle}</Text><Text style={[styles.nextMeta,rtl&&styles.rtl]}>{current.sessionFocus} · {current.sessionDurationMinCurrent ?? current.sessionDurationMin} min</Text></View>:null}</View>:<View style={styles.emptyCurrent}><Text style={[styles.emptyTitle,rtl&&styles.rtl]}>{text.noCurrent}</Text></View>}
    <View style={styles.rowHead}><Text style={[styles.sectionTitle,rtl&&styles.rtl]}>{text.catalog}</Text><Pressable onPress={()=>router.push('/fitness-calculators')}><Text style={styles.calc}>{text.calc}</Text></Pressable></View>
    <FlatList data={items} keyExtractor={x=>x.id} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load();}}/>} renderItem={({item})=><Pressable onPress={()=>router.push(`/fitness-program/${encodeURIComponent(item.id)}`)} style={styles.card}><View style={styles.badges}><View style={styles.badge}><Text style={styles.badgeText}>{item.discipline.toUpperCase()}</Text></View><Text style={styles.goal}>{item.goal.replace('_',' ')}</Text></View><FitnessLocalizedText en={item.name} fa={item.nameFa} locale={locale} style={{...styles.cardTitle, ...(rtl ? styles.rtl : {})}} /><FitnessLocalizedText en={item.description} locale={locale} style={{...styles.cardDescription, ...(rtl ? styles.rtl : {})}} /><View style={styles.cardBottom}><Text style={styles.meta}>{item.durationWeeks} wk · {item.sessionsPerWeek}×/wk · {item.sessionDurationMin} min</Text><Text style={styles.explore}>{text.start} →</Text></View></Pressable>} ListEmptyComponent={<View style={styles.center}><Text>{text.empty}</Text></View>}/>
  </SafeAreaView>;
}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BRAND.colors.canvas},header:{padding:20,paddingBottom:8},back:{fontWeight:'800',color:'#374151',marginBottom:12},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.7,color:BRAND.colors.primaryStrong},title:{fontSize:30,lineHeight:36,fontWeight:'900',color:'#111827',marginTop:5},subtitle:{fontSize:14,lineHeight:20,color:'#6B7280',marginTop:7},current:{margin:20,marginTop:10,padding:18,borderRadius:24,backgroundColor:'#111827'},currentTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},currentLabel:{color:'#D1D5DB',fontSize:10,fontWeight:'900',letterSpacing:1.2},active:{paddingHorizontal:8,paddingVertical:5,borderRadius:8,backgroundColor:'#374151'},activeText:{color:'#FFF',fontSize:8,fontWeight:'900'},currentTitle:{marginTop:10,color:'#FFF',fontSize:21,fontWeight:'900'},currentMeta:{marginTop:5,color:'#9CA3AF',fontSize:11},next:{marginTop:14,padding:13,borderRadius:16,backgroundColor:'#1F2937'},nextLabel:{color:'#9CA3AF',fontSize:9,fontWeight:'900',letterSpacing:1},nextTitle:{marginTop:5,color:'#FFF',fontSize:14,fontWeight:'900'},nextMeta:{marginTop:3,color:'#D1D5DB',fontSize:10},emptyCurrent:{margin:20,marginTop:10,padding:18,borderRadius:20,backgroundColor:'#FFF'},emptyTitle:{color:'#6B7280',fontSize:13,fontWeight:'800'},rowHead:{paddingHorizontal:20,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},sectionTitle:{fontSize:16,fontWeight:'900',color:'#111827'},calc:{fontSize:12,fontWeight:'900',color:BRAND.colors.primaryStrong},list:{padding:20,paddingTop:12,gap:12,paddingBottom:36},card:{backgroundColor:'#FFF',padding:17,borderRadius:22,borderWidth:1,borderColor:'#EEF0F3'},badges:{flexDirection:'row',alignItems:'center',gap:8},badge:{paddingHorizontal:8,paddingVertical:5,borderRadius:8,backgroundColor:'#F3F4F6'},badgeText:{fontSize:8,fontWeight:'900',color:'#4B5563'},goal:{fontSize:10,fontWeight:'800',color:BRAND.colors.primaryStrong,textTransform:'capitalize'},cardTitle:{marginTop:11,fontSize:20,fontWeight:'900',color:'#111827'},cardDescription:{marginTop:5,fontSize:12,lineHeight:18,color:'#6B7280'},cardBottom:{marginTop:13,paddingTop:11,borderTopWidth:1,borderTopColor:'#F0F1F3',flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},meta:{fontSize:10,color:'#6B7280',fontWeight:'800'},explore:{fontSize:11,color:'#111827',fontWeight:'900'},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24},centerText:{marginTop:10,color:'#6B7280'},rtl:{textAlign:'right',writingDirection:'rtl'}});
