import { useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { calculateFitness, FitnessCalculatorResult } from '../lib/fitness-content-api';
import { BRAND } from '../lib/branding';
import { useAppLocale } from '../lib/i18n';
import { localizedCopy } from '../lib/localized-copy';

const ui=localizedCopy({
  en:{back:'Back',eyebrow:'FITNESS CALCULATORS',title:'Know your numbers',subtitle:'BMI, BMR, daily calories, water and lean-mass estimates.',age:'Age',height:'Height (cm)',weight:'Weight (kg)',activity:'Activity factor',sex:'Sex',male:'Male',female:'Female',calculate:'Calculate',fatLoss:'Fat loss',gain:'Gain',water:'Water'},
  fa:{back:'برگشت',eyebrow:'محاسبات تناسب اندام',title:'عددهای بدنت را بهتر بشناس',subtitle:'BMI، BMR، کالری روزانه، آب و تخمین توده بدون چربی',age:'سن',height:'قد (سانتی‌متر)',weight:'وزن (کیلو)',activity:'ضریب فعالیت',sex:'جنسیت',male:'مرد',female:'زن',calculate:'محاسبه',fatLoss:'چربی‌سوزی',gain:'افزایش وزن',water:'آب'}
});
export default function FitnessCalculatorsScreen(){
  const {locale,rtl}=useAppLocale(); const text=ui[locale];
  const [sex,setSex]=useState<'male'|'female'>('male'); const [age,setAge]=useState('30'); const [height,setHeight]=useState('180'); const [weight,setWeight]=useState('80'); const [activity,setActivity]=useState('1.55'); const [result,setResult]=useState<FitnessCalculatorResult|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const run=async()=>{setBusy(true);setError(null);try{setResult(await calculateFitness({sex,age:Number(age),heightCm:Number(height),weightKg:Number(weight),activityFactor:Number(activity),waterActivityLevel:'moderate'}));}catch(e){setError(e instanceof Error?e.message:'Calculation failed.')}finally{setBusy(false)}};
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={()=>router.back()}><Text style={styles.back}>{rtl?'→':'←'} {text.back}</Text></Pressable><Text style={[styles.eyebrow,rtl&&styles.rtl]}>{text.eyebrow}</Text><Text style={[styles.title,rtl&&styles.rtl]}>{text.title}</Text><Text style={[styles.subtitle,rtl&&styles.rtl]}>{text.subtitle}</Text>
  <View style={styles.form}>{[['Age',age,setAge],['Height (cm)',height,setHeight],['Weight (kg)',weight,setWeight],['Activity factor',activity,setActivity]].map(([label,value,setter])=><View key={String(label)} style={styles.field}><Text style={[styles.label,rtl&&styles.rtl]}>{label==='Age'?text.age:label==='Height (cm)'?text.height:label==='Weight (kg)'?text.weight:text.activity}</Text><TextInput value={String(value)} onChangeText={setter as any} keyboardType="decimal-pad" style={[styles.input,rtl&&styles.rtl]}/></View>)}<Text style={[styles.label,rtl&&styles.rtl]}>{text.sex}</Text><View style={styles.sexRow}><Pressable onPress={()=>setSex('male')} style={[styles.sex,sex==='male'&&styles.sexActive]}><Text style={[styles.sexText,sex==='male'&&styles.sexActiveText]}>{text.male}</Text></Pressable><Pressable onPress={()=>setSex('female')} style={[styles.sex,sex==='female'&&styles.sexActive]}><Text style={[styles.sexText,sex==='female'&&styles.sexActiveText]}>{text.female}</Text></Pressable></View><Pressable onPress={run} style={styles.primary}>{busy?<ActivityIndicator color="#FFF"/>:<Text style={styles.primaryText}>{text.calculate}</Text>}</Pressable>{error?<Text style={styles.error}>{error}</Text>:null}</View>
  {result?<View style={styles.grid}>{[['BMI',result.bmi],['BMR',`${result.bmr} kcal`],['TDEE',`${result.tdee} kcal`],['Fat loss',`${result.recommendedCaloriesForFatLoss} kcal`],['Gain',`${result.recommendedCaloriesForGain} kcal`],['Water',`${result.waterMl} ml`]].map(([k,v])=><View style={styles.metric} key={String(k)}><Text style={styles.metricValue}>{v}</Text><Text style={styles.metricLabel}>{({BMI:'BMI',BMR:'BMR',TDEE:'TDEE','Fat loss':text.fatLoss,Gain:text.gain,Water:text.water} as any)[k]??k}</Text></View>)}</View>:null}
  </ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BRAND.colors.canvas},content:{padding:20,paddingBottom:40},back:{fontWeight:'800',color:'#374151',marginBottom:14},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.7,color:BRAND.colors.primaryStrong},title:{fontSize:30,lineHeight:36,fontWeight:'900',color:'#111827',marginTop:6},subtitle:{marginTop:7,fontSize:14,lineHeight:20,color:'#6B7280'},form:{marginTop:18,padding:17,borderRadius:22,backgroundColor:'#FFF',borderWidth:1,borderColor:'#EEF0F3'},field:{marginBottom:11},label:{fontSize:11,fontWeight:'900',color:'#4B5563',marginBottom:5},input:{height:47,borderWidth:1,borderColor:'#E5E7EB',borderRadius:13,paddingHorizontal:13,color:'#111827'},sexRow:{flexDirection:'row',gap:8},sex:{flex:1,paddingVertical:11,borderRadius:12,backgroundColor:'#F3F4F6',alignItems:'center'},sexActive:{backgroundColor:'#111827'},sexText:{fontWeight:'900',color:'#4B5563'},sexActiveText:{color:'#FFF'},primary:{marginTop:16,padding:13,borderRadius:14,backgroundColor:BRAND.colors.primaryStrong,alignItems:'center'},primaryText:{color:'#FFF',fontWeight:'900'},error:{marginTop:10,color:'#B91C1C',fontSize:11},grid:{marginTop:14,flexDirection:'row',flexWrap:'wrap',gap:10},metric:{width:'31.5%',minHeight:90,padding:11,borderRadius:17,backgroundColor:'#FFF',borderWidth:1,borderColor:'#EEF0F3',justifyContent:'space-between'},metricValue:{fontSize:16,fontWeight:'900',color:'#111827'},metricLabel:{fontSize:10,color:'#6B7280',fontWeight:'800'},rtl:{textAlign:'right',writingDirection:'rtl'}});
