import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { createWorkout } from '../lib/api';
import { FitnessDiscipline, FitnessSession, startFitnessSession } from '../lib/fitness-api';
import { recordFitnessSession } from '../lib/fitness-progress-api';
import { useAppLocale } from '../lib/i18n';

const copy = {
  en:{back:'Back',loading:'Building your session…',finish:'Finish session',next:'Next',done:'Session complete',set:'Set',reps:'reps',hold:'hold',rest:'Rest',coach:'Coach cue',failed:'Could not build the session.'},
  fa:{back:'برگشت',loading:'در حال ساخت جلسه تمرین…',finish:'پایان جلسه',next:'حرکت بعدی',done:'جلسه تمام شد',set:'ست',reps:'تکرار',hold:'نگه‌داشتن',rest:'استراحت',coach:'نکته مربی',failed:'ساخت جلسه تمرین ناموفق بود.'},
} as const;

export default function FitnessSessionScreen(){
 const locale=useAppLocale(); const text=copy[locale]; const params=useLocalSearchParams<{discipline?:string;level?:string}>(); const discipline=(params.discipline==='calisthenics'?'calisthenics':'gym') as Exclude<FitnessDiscipline,'yoga'>; const level=Math.max(1,Math.min(10,Number(params.level)||5));
 const [session,setSession]=useState<FitnessSession|null>(null); const [index,setIndex]=useState(0); const [remaining,setRemaining]=useState(0); const [busy,setBusy]=useState(true); const [error,setError]=useState<string|null>(null); const [finished,setFinished]=useState(false); const [recording,setRecording]=useState(false);
 useEffect(()=>{void startFitnessSession(discipline,level,25).then(value=>{setSession(value);const first=value.steps[0];setRemaining(first?.holdSec??first?.reps??30);}).catch(err=>setError(err instanceof Error?err.message:text.failed)).finally(()=>setBusy(false));},[discipline,level,text.failed]);
 useEffect(()=>{if(!session||finished)return;const id=setInterval(()=>setRemaining(value=>Math.max(0,value-1)),1000);return()=>clearInterval(id)},[session,finished,index]);
 useEffect(()=>{if(!session||finished)return;const step=session.steps[index];if(step&&remaining===0&&index<session.steps.length-1){setIndex(value=>value+1);const next=session.steps[index+1];setRemaining(next?.holdSec??next?.reps??30)}},[remaining,session,index,finished]);
 const current=session?.steps[index]; const progress=session?Math.round(((index+1)/Math.max(1,session.steps.length))*100):0; const title=current?.exerciseId??`Step ${index+1}`;
 const displayTimer=useMemo(()=>`${Math.floor(remaining/60).toString().padStart(2,'0')}:${(remaining%60).toString().padStart(2,'0')}`,[remaining]);
 const finish=async()=>{if(!session||recording)return;if(finished)return;setRecording(true);try{await Promise.all([createWorkout({name:`${discipline} · Level ${level}`,type:discipline,durationMinutes:session.durationMin,caloriesBurned:0}),recordFitnessSession({discipline,difficulty:level,completed:true,formScore:null})]);setFinished(true);}catch(err){setError(err instanceof Error?err.message:(locale==='fa'?'ثبت جلسه ناموفق بود.':'Could not save the completed session.'));}finally{setRecording(false)}};
 if(busy)return <View style={styles.center}><ActivityIndicator size="large"/><Text style={styles.loading}>{text.loading}</Text></View>;
 if(error)return <SafeAreaView style={styles.safe}><Text style={styles.error}>{error}</Text><Pressable style={styles.button} onPress={()=>router.back()}><Text style={styles.buttonText}>{text.back}</Text></Pressable></SafeAreaView>;
 if(!session)return null;
 return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={()=>router.back()}><Text style={styles.back}>{text.back}</Text></Pressable><Text style={styles.level}>L{level}</Text></View><View style={styles.progress}><View style={[styles.progressFill,{width:`${finished?100:progress}%`}]}/></View>
   <View style={styles.hero}>{finished?<><Text style={styles.bigEmoji}>✓</Text><Text style={styles.done}>{text.done}</Text><Pressable style={styles.button} onPress={()=>router.back()}><Text style={styles.buttonText}>{text.back}</Text></Pressable></>:<><Text style={styles.eyebrow}>{discipline.toUpperCase()}</Text><Text style={styles.title}>{title.replaceAll('_',' ')}</Text><Text style={styles.timer}>{displayTimer}</Text><Text style={styles.stepMeta}>{current?.sets?`${text.set} ${current.sets}`:''}{current?.reps?` · ${current.reps} ${text.reps}`:''}{current?.holdSec?` · ${current.holdSec}s ${text.hold}`:''}</Text><View style={styles.coach}><Text style={styles.coachLabel}>{text.coach}</Text><Text style={styles.coachText}>{current?.coachCues?.[0]??text.next}</Text></View><View style={styles.actions}><Pressable disabled={recording} style={styles.nextButton} onPress={()=>{if(index>=session.steps.length-1){void finish();}else{setIndex(value=>value+1);const next=session.steps[index+1];setRemaining(next?.holdSec??next?.reps??30)}}}><Text style={styles.buttonText}>{recording?'…':index>=session.steps.length-1?text.finish:text.next}</Text></Pressable><Pressable disabled={recording} style={styles.finishButton} onPress={()=>void finish()}><Text style={styles.finishText}>{recording?'…':text.finish}</Text></Pressable></View></>}</View>
 </SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F8FA',padding:20},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F7F8FA'},loading:{marginTop:10,color:'#6B7280'},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},back:{fontWeight:'900',color:'#111827'},level:{fontWeight:'900',color:'#4338CA',backgroundColor:'#EEF2FF',paddingHorizontal:10,paddingVertical:6,borderRadius:10},progress:{height:7,backgroundColor:'#E5E7EB',borderRadius:4,overflow:'hidden',marginTop:14},progressFill:{height:'100%',backgroundColor:'#0F766E'},hero:{flex:1,justifyContent:'center'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:'#6B7280'},title:{fontSize:34,fontWeight:'900',color:'#111827',marginTop:7,textTransform:'capitalize'},timer:{fontSize:58,fontWeight:'900',color:'#111827',marginTop:22},stepMeta:{fontSize:13,color:'#6B7280',marginTop:6},coach:{backgroundColor:'#FFF',borderRadius:20,padding:18,marginTop:26},coachLabel:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:'#0F766E'},coachText:{fontSize:16,fontWeight:'800',color:'#111827',lineHeight:24,marginTop:7},actions:{gap:10,marginTop:20},nextButton:{backgroundColor:'#111827',borderRadius:16,paddingVertical:16,alignItems:'center'},finishButton:{borderWidth:1,borderColor:'#D1D5DB',backgroundColor:'#FFF',borderRadius:16,paddingVertical:15,alignItems:'center'},button:{backgroundColor:'#111827',borderRadius:15,paddingVertical:13,paddingHorizontal:18,alignItems:'center',marginTop:18},buttonText:{color:'#FFF',fontWeight:'900'},finishText:{color:'#111827',fontWeight:'900'},error:{color:'#991B1B',fontWeight:'800',fontSize:15,marginTop:30},bigEmoji:{fontSize:56,fontWeight:'900',color:'#0F766E'},done:{fontSize:28,fontWeight:'900',color:'#111827',marginTop:10}});
