import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Link } from 'expo-router';
import { AuthUser, DashboardOverviewResponse, addWater, createWorkout, getDashboardOverview, getMe, hasAuthSession, login, logout, register } from '../lib/api';
import { colors, radius, spacing, typography, shadows } from '../lib/design-system';

function ProgressBar({ progress }: { progress: number }) { return <View style={styles.track}><View style={[styles.fill, { width: `${Math.max(0, Math.min(progress, 100))}%` }]} /></View>; }
function StatCard({ label, value, helper }: { label: string; value: string; helper?: string }) { return <View style={[styles.statCard, shadows.subtle]}><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text>{helper ? <Text style={styles.statHelper}>{helper}</Text> : null}</View>; }
function NutritionCard({ label, value, goal, remaining, progress, unit }: { label: string; value: number; goal: number; remaining: number; progress: number; unit: string }) { return <View style={[styles.card, shadows.subtle]}><View style={styles.cardHeader}><Text style={styles.cardLabel}>{label}</Text><Text style={styles.cardPercent}>{progress}%</Text></View><Text style={styles.cardValue}>{value.toLocaleString()} <Text style={styles.unit}>{unit}</Text></Text><ProgressBar progress={progress} /><Text style={styles.muted}>{goal.toLocaleString()} {unit} goal · {remaining.toLocaleString()} {unit} left</Text></View>; }

function AuthScreen({ onAuthenticated, initialError }: { onAuthenticated: (user: AuthUser) => void; initialError: string | null }) {
  const [mode, setMode] = useState<'login' | 'register'>('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [firstName, setFirstName] = useState(''); const [lastName, setLastName] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(initialError);
  const submit = async () => { if (!email.trim() || !password) { setError('Email and password are required.'); return; } if (mode === 'register' && password.length < 8) { setError('Password must be at least 8 characters.'); return; } try { setBusy(true); setError(null); const auth = mode === 'login' ? await login(email.trim(), password) : await register({ email: email.trim(), password, firstName: firstName.trim() || undefined, lastName: lastName.trim() || undefined }); onAuthenticated(auth.user); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to authenticate.'); } finally { setBusy(false); } };
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={styles.authContainer} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.authContent} keyboardShouldPersistTaps="handled"><Text style={styles.eyebrow}>MY PERSONAL ASSISTANT</Text><Text style={styles.authTitle}>{mode === 'login' ? 'Welcome back 👋' : 'Let’s get started ✨'}</Text><Text style={styles.authSubtitle}>{mode === 'login' ? 'Sign in to continue your day.' : 'Create your personal assistant account.'}</Text><View style={[styles.authCard, shadows.soft]}>{mode === 'register' ? <View style={styles.row}><TextInput value={firstName} onChangeText={setFirstName} placeholder="First name" placeholderTextColor={colors.textMuted} style={[styles.input, styles.halfInput]} autoCapitalize="words" /><TextInput value={lastName} onChangeText={setLastName} placeholder="Last name" placeholderTextColor={colors.textMuted} style={[styles.input, styles.halfInput]} autoCapitalize="words" /></View> : null}<TextInput value={email} onChangeText={setEmail} placeholder="Email" placeholderTextColor={colors.textMuted} style={styles.input} autoCapitalize="none" autoCorrect={false} keyboardType="email-address" /><TextInput value={password} onChangeText={setPassword} placeholder="Password" placeholderTextColor={colors.textMuted} style={styles.input} secureTextEntry />{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable style={({ pressed }) => [styles.primaryButton, pressed && styles.pressed]} onPress={() => void submit()} disabled={busy}>{busy ? <ActivityIndicator color={colors.surface} /> : <Text style={styles.primaryButtonText}>{mode === 'login' ? 'Sign in' : 'Create account'}</Text>}</Pressable><Pressable style={styles.switchButton} onPress={() => { setMode(mode === 'login' ? 'register' : 'login'); setError(null); }}><Text style={styles.switchText}>{mode === 'login' ? 'Need an account? Create one' : 'Already have an account? Sign in'}</Text></Pressable></View></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}

export default function HomeScreen() {
  const [data, setData] = useState<DashboardOverviewResponse | null>(null); const [user, setUser] = useState<AuthUser | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [actionBusy, setActionBusy] = useState<string | null>(null); const [authError, setAuthError] = useState<string | null>(null); const [dashboardError, setDashboardError] = useState<string | null>(null);
  const loadDashboard = useCallback(async () => { try { setDashboardError(null); setData(await getDashboardOverview()); } catch (err) { setDashboardError(err instanceof Error ? err.message : 'Unable to load dashboard'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { let mounted = true; const bootstrap = async () => { try { if (!(await hasAuthSession())) { if (mounted) setLoading(false); return; } const currentUser = await getMe(); if (!mounted) return; setUser(currentUser); await loadDashboard(); } catch (err) { await logout(); if (mounted) { setAuthError(err instanceof Error ? 'Your session expired. Please sign in again.' : 'Please sign in again.'); setLoading(false); } } }; void bootstrap(); return () => { mounted = false; }; }, [loadDashboard]);
  const handleAuthenticated = useCallback(async (authenticatedUser: AuthUser) => { setAuthError(null); setUser(authenticatedUser); setLoading(true); await loadDashboard(); }, [loadDashboard]);
  const handleLogout = useCallback(async () => { await logout(); setUser(null); setData(null); setDashboardError(null); }, []);
  const runAction = useCallback(async (key: string, action: () => Promise<unknown>) => { try { setActionBusy(key); await action(); await loadDashboard(); } catch (err) { setDashboardError(err instanceof Error ? err.message : 'Action failed'); } finally { setActionBusy(null); } }, [loadDashboard]);
  if (loading && !user) return <View style={styles.center}><ActivityIndicator size="large" color={colors.ink} /></View>; if (!user) return <AuthScreen onAuthenticated={handleAuthenticated} initialError={authError} />;
  const today = data?.today; const weekly = data?.weekly; const workouts = data?.workouts; const primaryGoal = today?.profile?.primaryGoal;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void loadDashboard(); }} />}>
    <View style={styles.headerRow}><View style={styles.headerCopy}><Text style={styles.eyebrow}>MY PERSONAL ASSISTANT</Text><Text style={styles.title}>Good day{user.firstName ? `, ${user.firstName}` : ''} 👋</Text><Text style={styles.subtitle}>{today?.dateKey ?? 'Today'} · your personal space</Text></View><Pressable onPress={() => void handleLogout()} style={styles.logoutButton}><Text style={styles.logoutText}>Log out</Text></Pressable></View>
    {dashboardError ? <View style={styles.warningCard}><Text style={styles.warningTitle}>A little hiccup</Text><Text style={styles.warningText}>{dashboardError}</Text><Pressable onPress={() => void loadDashboard()} style={styles.retryButton}><Text style={styles.retryText}>Try again</Text></Pressable></View> : null}
    <View style={[styles.hero, shadows.soft]}><Text style={styles.heroEyebrow}>YOUR DAY, AT A GLANCE</Text><Text style={styles.heroTitle}>{today?.nutrition.caloriesRemaining.toLocaleString() ?? 0}</Text><Text style={styles.heroUnit}>kcal remaining</Text><Text style={styles.heroMuted}>I’ll help you keep the rest of the day simple.</Text>{primaryGoal ? <Text style={styles.goalText}>✦ {primaryGoal}</Text> : <Text style={styles.goalText}>✦ Add a goal and I’ll make this more personal</Text>}</View>
    <Link href="/insights" asChild><Pressable style={({ pressed }) => [styles.insightLink, pressed && styles.pressed]}><Text style={styles.insightEmoji}>✦</Text><View style={styles.insightCopy}><Text style={styles.insightTitle}>Your assistant has something to share</Text><Text style={styles.insightSubtitle}>See patterns from your week →</Text></View></Pressable></Link>
    <View style={[styles.card, shadows.subtle]}><Text style={styles.sectionTitle}>Little things, right now</Text><Text style={styles.muted}>Quickly log something and I’ll keep your day up to date.</Text><View style={styles.actionGrid}>{[250, 500, 750].map((amount) => <Pressable key={amount} disabled={!!actionBusy} onPress={() => void runAction(`water-${amount}`, () => addWater(amount, today?.dateKey))} style={({ pressed }) => [styles.actionButton, pressed && styles.pressed]}><Text style={styles.actionEmoji}>💧</Text><Text style={styles.actionText}>{actionBusy === `water-${amount}` ? '…' : `+${amount} ml`}</Text></Pressable>)}</View><View style={styles.actionGrid}>{[{ key: 'walk', label: '20 min walk', duration: 20, calories: 100, type: 'cardio' }, { key: 'cardio', label: '30 min cardio', duration: 30, calories: 220, type: 'cardio' }, { key: 'strength', label: '45 min strength', duration: 45, calories: 300, type: 'strength' }].map((preset) => <Pressable key={preset.key} disabled={!!actionBusy} onPress={() => void runAction(`workout-${preset.key}`, () => createWorkout({ name: preset.label, type: preset.type, durationMinutes: preset.duration, caloriesBurned: preset.calories }))} style={({ pressed }) => [styles.actionButton, pressed && styles.pressed]}><Text style={styles.actionEmoji}>◌</Text><Text style={styles.actionText}>{actionBusy === `workout-${preset.key}` ? '…' : preset.label}</Text></Pressable>)}</View></View>
    <View style={styles.grid}><StatCard label="7-day consistency" value={`${weekly?.consistencyPercent ?? 0}%`} helper={`${weekly?.loggedDays ?? 0}/7 days logged`} /><StatCard label="Current streak" value={`${weekly?.currentStreak ?? 0} days`} helper="daily logging" /><StatCard label="Workouts" value={`${workouts?.count ?? 0}`} helper={`${workouts?.totalMinutes ?? 0} min this week`} /><StatCard label="Workout calories" value={`${(workouts?.totalCaloriesBurned ?? 0).toLocaleString()}`} helper="burned this week" /></View>
    <View style={styles.sectionTitleRow}><Text style={styles.sectionTitle}>Today’s progress</Text><Text style={styles.sectionHint}>LIVE</Text></View>
    <NutritionCard label="Calories" value={today?.nutrition.calories ?? 0} goal={today?.nutrition.calorieGoal ?? 0} remaining={today?.nutrition.caloriesRemaining ?? 0} progress={today?.nutrition.caloriesProgress ?? 0} unit="kcal" /><NutritionCard label="Protein" value={today?.nutrition.protein ?? 0} goal={today?.nutrition.proteinGoal ?? 0} remaining={today?.nutrition.proteinRemaining ?? 0} progress={today?.nutrition.proteinProgress ?? 0} unit="g" /><NutritionCard label="Water" value={today?.nutrition.waterMl ?? 0} goal={today?.nutrition.waterGoalMl ?? 0} remaining={today?.nutrition.waterRemainingMl ?? 0} progress={today?.nutrition.waterProgress ?? 0} unit="ml" />
    <View style={styles.sectionTitleRow}><Text style={styles.sectionTitle}>This week</Text><Text style={styles.sectionHint}>{data?.range.startKey} → {data?.range.endKey}</Text></View><View style={[styles.card, shadows.subtle]}><View style={styles.inlineStats}><View><Text style={styles.cardLabel}>Avg calories</Text><Text style={styles.inlineValue}>{weekly?.averageCalories.toLocaleString() ?? 0}</Text></View><View><Text style={styles.cardLabel}>Avg protein</Text><Text style={styles.inlineValue}>{weekly?.averageProtein ?? 0} g</Text></View></View><View style={styles.divider} /><Text style={styles.muted}>{(weekly?.totalWaterMl ?? 0).toLocaleString()} ml water · {(weekly?.totalProtein ?? 0).toLocaleString()} g protein · {(weekly?.totalCalories ?? 0).toLocaleString()} kcal total</Text></View>
    <View style={styles.sectionTitleRow}><Text style={styles.sectionTitle}>Training</Text><Text style={styles.sectionHint}>LAST 7 DAYS</Text></View><View style={[styles.card, shadows.subtle]}>{workouts?.latest ? <><Text style={styles.cardLabel}>Latest workout</Text><Text style={styles.workoutName}>{workouts.latest.name}</Text><Text style={styles.muted}>{workouts.latest.type} · {workouts.latest.durationMinutes} min · {workouts.latest.caloriesBurned} kcal</Text></> : <><Text style={styles.cardLabel}>Ready when you are</Text><Text style={styles.workoutName}>No workout logged yet</Text><Text style={styles.muted}>Start tracking and your assistant will build the history.</Text></>}<View style={styles.trainingRow}><Text style={styles.trainingMetric}>{workouts?.activeDays ?? 0} active days</Text><Text style={styles.trainingMetric}>{workouts?.totalMinutes ?? 0} min</Text><Text style={styles.trainingMetric}>{workouts?.totalCaloriesBurned ?? 0} kcal</Text></View></View>
    <View style={styles.sectionTitleRow}><Text style={styles.sectionTitle}>Recent meals</Text><Text style={styles.sectionHint}>{today?.mealCount ?? 0} TODAY</Text></View><View style={[styles.card, shadows.subtle]}>{today?.meals.length ? today.meals.map((meal) => <View key={meal.id} style={styles.mealRow}><View style={styles.mealCopy}><Text style={styles.mealName}>{meal.name}</Text><Text style={styles.muted}>{meal.type} · {Math.round(meal.protein)} g protein</Text></View><Text style={styles.mealCalories}>{meal.calories} kcal</Text></View>) : <Text style={styles.muted}>No meals logged today yet.</Text>}</View>
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.paper }, content: { padding: spacing.xl, gap: spacing.md, paddingBottom: 40 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paper },
  authContainer: { flex: 1 }, authContent: { flexGrow: 1, justifyContent: 'center', padding: spacing.xl }, authTitle: { ...typography.title1, color: colors.text, marginTop: spacing.sm }, authSubtitle: { ...typography.body, color: colors.textMuted, marginTop: spacing.sm, marginBottom: spacing.xxl }, authCard: { backgroundColor: colors.surface, borderRadius: radius.xl, padding: spacing.xl, gap: spacing.md }, input: { minHeight: 52, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: 15, color: colors.text, backgroundColor: colors.surface }, row: { flexDirection: 'row', gap: spacing.sm }, halfInput: { flex: 1 }, primaryButton: { minHeight: 52, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.ink, marginTop: spacing.xs }, primaryButtonText: { color: colors.surface, fontWeight: '800', fontSize: 15 }, switchButton: { alignItems: 'center', paddingVertical: spacing.sm }, switchText: { color: colors.textMuted, fontWeight: '600', fontSize: 13 },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: spacing.xs }, headerCopy: { flex: 1, paddingRight: spacing.md }, eyebrow: { ...typography.eyebrow, color: colors.textMuted }, title: { ...typography.title1, color: colors.text, marginTop: spacing.xs }, subtitle: { ...typography.caption, color: colors.textMuted, marginTop: 2 }, logoutButton: { paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radius.pill, backgroundColor: colors.surfaceWarm }, logoutText: { color: colors.text, fontWeight: '700', fontSize: 11 },
  hero: { backgroundColor: colors.ink, borderRadius: radius.xl, padding: spacing.xxl, marginVertical: spacing.xs }, heroEyebrow: { ...typography.eyebrow, color: '#AAA99F' }, heroTitle: { color: colors.surface, fontSize: 42, lineHeight: 46, fontWeight: '800', marginTop: spacing.sm }, heroUnit: { color: '#E2E1D9', fontSize: 14, fontWeight: '700', marginTop: 2 }, heroMuted: { color: colors.textOnDarkMuted, ...typography.body, marginTop: spacing.md }, goalText: { color: colors.surface, fontWeight: '700', marginTop: spacing.lg, lineHeight: 20 },
  insightLink: { backgroundColor: colors.surfaceAccent, borderRadius: radius.lg, padding: spacing.lg, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: colors.border }, insightEmoji: { fontSize: 23, marginRight: spacing.md, color: colors.ink }, insightCopy: { flex: 1 }, insightTitle: { color: colors.text, fontWeight: '800', fontSize: 14 }, insightSubtitle: { color: colors.textMuted, fontSize: 12, marginTop: 4 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, statCard: { width: '48%', backgroundColor: colors.surface, borderRadius: radius.md, padding: spacing.lg, borderWidth: 1, borderColor: colors.border }, statLabel: { color: colors.textMuted, fontSize: 11, fontWeight: '700' }, statValue: { color: colors.text, fontSize: 23, fontWeight: '800', marginTop: 6 }, statHelper: { color: colors.textMuted, fontSize: 11, marginTop: 4 },
  card: { backgroundColor: colors.surface, borderRadius: radius.lg, padding: spacing.lg, borderWidth: 1, borderColor: colors.border }, cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, cardLabel: { color: colors.textMuted, fontSize: 13, fontWeight: '700' }, cardPercent: { color: colors.text, fontSize: 12, fontWeight: '800' }, cardValue: { color: colors.text, fontSize: 27, fontWeight: '800', marginTop: 4 }, unit: { fontSize: 13, color: colors.textMuted }, track: { height: 8, borderRadius: 8, backgroundColor: colors.surfaceWarm, overflow: 'hidden', marginTop: spacing.md }, fill: { height: '100%', borderRadius: 8, backgroundColor: colors.ink }, muted: { color: colors.textMuted, ...typography.caption, marginTop: 7 },
  actionGrid: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.md }, actionButton: { flex: 1, minHeight: 58, backgroundColor: colors.surfaceWarm, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.sm }, actionEmoji: { fontSize: 19, color: colors.ink }, actionText: { color: colors.text, fontSize: 11, fontWeight: '800', textAlign: 'center', marginTop: 4 },
  inlineStats: { flexDirection: 'row', justifyContent: 'space-between' }, inlineValue: { color: colors.text, fontSize: 23, fontWeight: '800', marginTop: 4 }, divider: { height: StyleSheet.hairlineWidth, backgroundColor: colors.border, marginVertical: spacing.lg }, sectionTitleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: spacing.sm }, sectionTitle: { color: colors.text, ...typography.title3 }, sectionHint: { color: colors.textMuted, fontSize: 9, fontWeight: '800', letterSpacing: 1 }, workoutName: { color: colors.text, fontSize: 22, fontWeight: '800', marginTop: 5 }, trainingRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.lg, paddingTop: spacing.md, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border }, trainingMetric: { color: colors.text, fontSize: 12, fontWeight: '800' }, mealRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 11, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, mealCopy: { flex: 1, paddingRight: spacing.md }, mealName: { color: colors.text, fontWeight: '700' }, mealCalories: { color: colors.text, fontWeight: '800' }, error: { color: colors.dangerText, textAlign: 'center', fontSize: 13 }, warningCard: { backgroundColor: colors.dangerSurface, borderRadius: radius.md, padding: spacing.lg }, warningTitle: { color: colors.dangerText, fontWeight: '800' }, warningText: { color: colors.dangerText, marginTop: 5, fontSize: 12 }, retryButton: { alignSelf: 'flex-start', marginTop: spacing.sm, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: 10, backgroundColor: colors.ink }, retryText: { color: colors.surface, fontWeight: '700', fontSize: 12 }, pressed: { opacity: 0.76 },
});
