import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { hasAuthSession } from '../lib/api';
import { getInventory, InventoryItem, setInventoryQuantity } from '../lib/inventory-api';
import { PREMIUM } from '../lib/premium-ui';
import { PremiumGlow } from '../components/PremiumGlow';
import { PremiumResultCard } from '../components/PremiumResultCard';
import { MotionPress } from '../lib/motion-components';

export default function InventoryPremiumScreen() {
  const [items,setItems]=useState<InventoryItem[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setError(null);setItems(await getInventory());}catch(e){setError(e instanceof Error?e.message:'Unable to load inventory.');}finally{setLoading(false);setRefreshing(false);}},[]);
  useEffect(()=>{void hasAuthSession().then(ok=>{if(ok)void load();else router.replace('/');});},[load]);
  const urgent=useMemo(()=>items.filter(i=>i.urgency==='critical'||i.urgency==='soon').length,[items]); const critical=useMemo(()=>items.filter(i=>i.urgency==='critical').length,[items]);
  const adjust=async(item:InventoryItem,delta:number)=>{const quantity=Math.max(0,item.quantity+delta);try{setItems(cur=>cur.map(x=>x.id===item.id?{...x,quantity}:x));const updated=await setInventoryQuantity(item.id,quantity);setItems(cur=>cur.map(x=>x.id===item.id?{...x,...updated}:x));}catch(e){setError(e instanceof Error?e.message:'Unable to update stock.');void load();}};
  if(loading)return <View style={styles.loading}><PremiumGlow size={260} opacity={0.12} accent="cyan"/><ActivityIndicator color={PREMIUM.colors.primaryBright}/><Text style={styles.loadingText}>Household brain</Text></View>;
  return <SafeAreaView style={styles.safe}><View style={styles.bg}><PremiumGlow size={350} opacity={0.07} accent="cyan"/></View><ScrollView showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load();}}/>} contentContainerStyle={styles.content}>
    <View style={styles.top}><Pressable onPress={()=>router.back()} style={styles.icon}><Ionicons name="arrow-back" size={18} color={PREMIUM.colors.inkSoft}/></Pressable><View style={styles.titleWrap}><Text style={styles.kicker}>HOUSEHOLD BRAIN</Text><Text style={styles.title}>Inventory</Text></View><Pressable onPress={()=>router.push('/assistant')} style={styles.icon}><Ionicons name="sparkles-outline" size={18} color={PREMIUM.colors.primaryBright}/></Pressable></View>
    <PremiumResultCard eyebrow="AT A GLANCE" title="Your home" accent="cyan" value={`${items.length} tracked · ${urgent} need attention`} detail={critical ? `${critical} item${critical===1?'':'s'} are critical.` : 'Everything looks under control.'} actions={[{label:'Open basket',icon:'cart-outline',onPress:()=>router.push('/shopping')},{label:'Find recipes',icon:'restaurant-outline',onPress:()=>router.push('/recipe-match')}]} />
    {error?<PremiumResultCard eyebrow="SYSTEM" title="Inventory update" detail={error} accent="rose" actions={[{label:'Retry',icon:'refresh',onPress:()=>void load()}]}/>:null}
    {items.length?items.map(item=><View key={item.id} style={[styles.item,item.urgency==='critical'&&styles.criticalCard]}><View style={styles.itemTop}><View style={styles.itemCopy}><Text style={styles.name}>{item.food.name}</Text><Text style={styles.meta}>{item.food.category} · {item.unit}</Text></View><View style={[styles.badge,item.urgency==='critical'&&styles.badgeCritical,item.urgency==='soon'&&styles.badgeSoon]}><Text style={styles.badgeText}>{item.urgency}</Text></View></View><View style={styles.stats}><Stat label="Stock" value={`${Math.round(item.quantity*10)/10} ${item.unit}`} /><Stat label="Days left" value={item.daysRemaining==null?'—':`${Math.max(0,Math.round(item.daysRemaining*10)/10)}d`} /><Stat label="Buy" value={item.recommendedQuantity>0?`+${Math.round(item.recommendedQuantity*10)/10}`:'Enough'} /></View><Text style={styles.reason}>{item.reason.replaceAll('_',' ')}</Text><View style={styles.actions}><MotionPress accessibilityRole="button" accessibilityLabel={`Decrease ${item.food.name}`} onPress={()=>void adjust(item,-1)} style={styles.adjust}><Ionicons name="remove" size={16} color={PREMIUM.colors.inkSoft}/></MotionPress><MotionPress accessibilityRole="button" accessibilityLabel={`Increase ${item.food.name}`} onPress={()=>void adjust(item,1)} style={styles.adjust}><Ionicons name="add" size={16} color={PREMIUM.colors.inkSoft}/></MotionPress></View></View>):<View style={styles.empty}><Ionicons name="cube-outline" size={28} color={PREMIUM.colors.primaryBright}/><Text style={styles.emptyTitle}>Nothing tracked yet</Text><Text style={styles.emptyBody}>Tell MYPA what you have at home and the household brain can start forecasting stock.</Text><MotionPress onPress={()=>router.push('/assistant')} style={styles.emptyAction}><Text style={styles.emptyActionText}>Tell MYPA</Text></MotionPress></View>}
  </ScrollView></SafeAreaView>;
}
function Stat({label,value}:{label:string;value:string}){return <View><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text></View>;}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:PREMIUM.colors.canvas},bg:{...StyleSheet.absoluteFillObject,overflow:'hidden'},content:{padding:18,gap:15,paddingBottom:120},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:PREMIUM.colors.canvas},loadingText:{color:PREMIUM.colors.ink,fontSize:14,fontWeight:'900',marginTop:12},top:{flexDirection:'row',alignItems:'center',gap:10},icon:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:PREMIUM.colors.border,backgroundColor:'rgba(255,255,255,0.035)',alignItems:'center',justifyContent:'center'},titleWrap:{flex:1,alignItems:'center'},kicker:{color:PREMIUM.colors.muted,fontSize:8,fontWeight:'900',letterSpacing:1.4},title:{color:PREMIUM.colors.ink,fontSize:18,fontWeight:'900',marginTop:3},item:{borderRadius:24,borderWidth:1,borderColor:PREMIUM.colors.border,backgroundColor:PREMIUM.colors.surfaceGlass,padding:16},criticalCard:{borderColor:'rgba(255,125,154,0.30)'},itemTop:{flexDirection:'row',gap:10},itemCopy:{flex:1},name:{color:PREMIUM.colors.ink,fontSize:15,fontWeight:'900'},meta:{color:PREMIUM.colors.muted,fontSize:10,marginTop:4},badge:{height:28,borderRadius:14,paddingHorizontal:9,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(98,230,181,0.10)'},badgeSoon:{backgroundColor:'rgba(255,197,107,0.12)'},badgeCritical:{backgroundColor:'rgba(255,125,154,0.12)'},badgeText:{color:PREMIUM.colors.inkSoft,fontSize:8,fontWeight:'900',textTransform:'uppercase'},stats:{flexDirection:'row',gap:28,paddingTop:13,marginTop:13,borderTopWidth:1,borderTopColor:PREMIUM.colors.border},statLabel:{color:PREMIUM.colors.muted,fontSize:9},statValue:{color:PREMIUM.colors.inkSoft,fontSize:12,fontWeight:'900',marginTop:3},reason:{color:PREMIUM.colors.muted,fontSize:10,marginTop:11},actions:{flexDirection:'row',justifyContent:'flex-end',gap:8,marginTop:12},adjust:{width:38,height:38,borderRadius:19,borderWidth:1,borderColor:PREMIUM.colors.border,backgroundColor:'rgba(255,255,255,0.03)',alignItems:'center',justifyContent:'center'},empty:{borderRadius:24,borderWidth:1,borderColor:PREMIUM.colors.border,backgroundColor:PREMIUM.colors.surfaceGlass,padding:30,alignItems:'center'},emptyTitle:{color:PREMIUM.colors.ink,fontSize:17,fontWeight:'900',marginTop:10},emptyBody:{color:PREMIUM.colors.muted,fontSize:12,lineHeight:18,textAlign:'center',marginTop:6,maxWidth:300},emptyAction:{marginTop:16,minHeight:44,paddingHorizontal:18,borderRadius:22,backgroundColor:PREMIUM.colors.primaryBright,alignItems:'center',justifyContent:'center'},emptyActionText:{color:PREMIUM.colors.ink,fontSize:11,fontWeight:'900'}});
