import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { hasAuthSession } from '../lib/api';
import { getInventory, InventoryItem, setInventoryQuantity } from '../lib/inventory-api';
import { useAppLocale } from '../lib/i18n';

const copy = {
  en: { back:'Back', recipes:'Recipes', basket:'Basket', eyebrow:'HOUSEHOLD', title:'Inventory', subtitle:'Know what you have, what is running low, and what the assistant should buy next.', tracked:'Items tracked', attention:'Need attention', critical:'Critical', cook:'Cook with what you have', cookHint:'Match recipes against your real household stock.', smartBasket:'Smart Basket', basketHint:'Turn low-stock forecasts into your next shopping list.', update:'Inventory update', stock:'Stock', days:'Days left', buy:'Buy', enough:'Enough', empty:'Your pantry is empty here', emptyHint:'Start adding foods to inventory and the assistant will forecast when they need replenishing.', updateError:'Unable to update stock.', loadError:'Unable to load inventory.' },
  fa: { back:'برگشت', recipes:'رسپی‌ها', basket:'سبد خرید', eyebrow:'خانه', title:'موجودی خانه', subtitle:'بدان چه چیزهایی داری، چه چیزهایی رو به اتمام‌اند و دستیارت بعدی چه چیزی بخرد.', tracked:'اقلام ثبت‌شده', attention:'نیازمند توجه', critical:'بحرانی', cook:'با چیزهایی که داری آشپزی کن', cookHint:'رسپی‌ها را با موجودی واقعی خانه تطبیق بده.', smartBasket:'سبد هوشمند', basketHint:'پیش‌بینی کمبود را به لیست خرید بعدی تبدیل کن.', update:'به‌روزرسانی موجودی', stock:'موجودی', days:'روز باقی‌مانده', buy:'خرید', enough:'کافی است', empty:'اینجا موجودی انباری نداری', emptyHint:'غذاها را به موجودی اضافه کن تا دستیار زمان تمام‌شدنشان را پیش‌بینی کند.', updateError:'به‌روزرسانی موجودی ناموفق بود.', loadError:'موجودی بارگذاری نشد.' },
};

export default function InventoryScreen() {
  const locale = useAppLocale(); const text = copy[locale]; const rtl = locale === 'fa';
  const [items,setItems]=useState<InventoryItem[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setError(null);setItems(await getInventory());}catch(err){setError(err instanceof Error?err.message:text.loadError)}finally{setLoading(false);setRefreshing(false)}},[text.loadError]);
  useEffect(()=>{void hasAuthSession().then(ok=>{if(ok)void load();else router.replace('/');});},[load]);
  const urgent=useMemo(()=>items.filter(item=>item.urgency==='critical'||item.urgency==='soon'),[items]);
  if(loading)return <View style={styles.center}><ActivityIndicator size="large" accessibilityLabel={locale==='fa'?'در حال بارگذاری':'Loading'} /></View>;
  const adjust=async(item:InventoryItem,delta:number)=>{const quantity=Math.max(0,item.quantity+delta);try{const updated=await setInventoryQuantity(item.id,quantity);setItems(current=>current.map(entry=>entry.id===item.id?{...entry,...updated}:entry));}catch(err){setError(err instanceof Error?err.message:text.updateError)}};
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={[styles.content,rtl&&styles.rtl]} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load();}} />}>
    <View style={[styles.nav,rtl&&styles.rtl]}><Pressable onPress={()=>router.back()}><Text style={styles.navText}>{rtl?'→':'←'} {text.back}</Text></Pressable><View style={styles.navActions}><Pressable onPress={()=>router.push('/recipe-match')}><Text style={styles.navText}>{text.recipes}</Text></Pressable><Pressable onPress={()=>router.push('/shopping')}><Text style={styles.navText}>{text.basket}</Text></Pressable></View></View>
    <Text style={[styles.eyebrow,rtl&&styles.textRtl]}>{text.eyebrow}</Text><Text style={[styles.title,rtl&&styles.textRtl]}>{text.title}</Text><Text style={[styles.subtitle,rtl&&styles.textRtl]}>{text.subtitle}</Text>
    <View style={[styles.summary,rtl&&styles.rtl]}><View><Text style={[styles.summaryLabel,rtl&&styles.textRtl]}>{text.tracked}</Text><Text style={styles.summaryValue}>{items.length}</Text></View><View><Text style={[styles.summaryLabel,rtl&&styles.textRtl]}>{text.attention}</Text><Text style={styles.summaryValue}>{urgent.length}</Text></View><View><Text style={[styles.summaryLabel,rtl&&styles.textRtl]}>{text.critical}</Text><Text style={styles.summaryValue}>{items.filter(item=>item.urgency==='critical').length}</Text></View></View>
    <Pressable onPress={()=>router.push('/recipe-match')} style={[styles.recipe,rtl&&styles.rtl]}><View style={styles.copyBlock}><Text style={[styles.recipeTitle,rtl&&styles.textRtl]}>{text.cook}</Text><Text style={[styles.recipeText,rtl&&styles.textRtl]}>{text.cookHint}</Text></View><Text style={styles.recipeArrow}>{rtl?'←':'→'}</Text></Pressable>
    <Pressable onPress={()=>router.push('/shopping')} style={[styles.basket,rtl&&styles.rtl]}><View style={styles.copyBlock}><Text style={[styles.basketTitle,rtl&&styles.textRtl]}>{text.smartBasket}</Text><Text style={[styles.basketText,rtl&&styles.textRtl]}>{text.basketHint}</Text></View><Text style={styles.basketArrow}>{rtl?'←':'→'}</Text></Pressable>
    {error?<View style={styles.error}><Text style={[styles.errorTitle,rtl&&styles.textRtl]}>{text.update}</Text><Text style={[styles.body,rtl&&styles.textRtl]}>{error}</Text></View>:null}
    {items.length?items.map(item=><View key={item.id} style={styles.card}><View style={[styles.cardTop,rtl&&styles.rtl]}><View style={styles.copyBlock}><Text style={[styles.name,rtl&&styles.textRtl]}>{item.food.name}</Text><Text style={[styles.meta,rtl&&styles.textRtl]}>{item.food.category} · {item.unit}</Text></View><View style={[styles.badge,item.urgency==='critical'&&styles.badgeCritical,item.urgency==='soon'&&styles.badgeSoon]}><Text style={styles.badgeText}>{item.urgency}</Text></View></View><View style={[styles.stockRow,rtl&&styles.rtl]}><View><Text style={[styles.stockLabel,rtl&&styles.textRtl]}>{text.stock}</Text><Text style={styles.stockValue}>{Math.round(item.quantity*10)/10} {item.unit}</Text></View><View><Text style={[styles.stockLabel,rtl&&styles.textRtl]}>{text.days}</Text><Text style={styles.stockValue}>{item.daysRemaining==null?'—':`${Math.max(0,Math.round(item.daysRemaining*10)/10)}d`}</Text></View><View><Text style={[styles.stockLabel,rtl&&styles.textRtl]}>{text.buy}</Text><Text style={styles.stockValue}>{item.recommendedQuantity>0?`+${Math.round(item.recommendedQuantity*10)/10}`:text.enough}</Text></View></View><Text style={[styles.reason,rtl&&styles.textRtl]}>{item.reason.replaceAll('_',' ')}</Text><View style={styles.actions}><Pressable onPress={()=>void adjust(item,-1)} style={styles.adjust}><Text style={styles.adjustText}>−</Text></Pressable><Pressable onPress={()=>void adjust(item,1)} style={styles.adjust}><Text style={styles.adjustText}>+</Text></Pressable></View></View>):<View style={styles.empty}><Text style={[styles.emptyTitle,rtl&&styles.textRtl]}>{text.empty}</Text><Text style={[styles.body,rtl&&styles.textRtl]}>{text.emptyHint}</Text></View>}
  </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F8FA'},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:'#F7F8FA'},content:{padding:20,gap:14,paddingBottom:40},rtl:{direction:'rtl'},textRtl:{textAlign:'right'},nav:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},navActions:{flexDirection:'row',gap:14},navText:{fontWeight:'900',color:'#111827'},eyebrow:{fontSize:10,letterSpacing:1.5,fontWeight:'900',color:'#6B7280'},title:{fontSize:32,fontWeight:'900',color:'#111827'},subtitle:{fontSize:14,lineHeight:21,color:'#6B7280'},summary:{backgroundColor:'#111827',borderRadius:20,padding:18,flexDirection:'row',justifyContent:'space-between'},summaryLabel:{fontSize:10,color:'#9CA3AF'},summaryValue:{fontSize:22,fontWeight:'900',color:'#FFF',marginTop:4},copyBlock:{flex:1},recipe:{backgroundColor:'#E0E7FF',borderRadius:18,padding:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},recipeTitle:{fontSize:15,fontWeight:'900',color:'#111827'},recipeText:{fontSize:11,color:'#4B5563',marginTop:3},recipeArrow:{fontSize:24,fontWeight:'900'},basket:{backgroundColor:'#F3F4F6',borderRadius:18,padding:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},basketTitle:{fontSize:15,fontWeight:'900',color:'#111827'},basketText:{fontSize:11,color:'#4B5563',marginTop:3},basketArrow:{fontSize:24,fontWeight:'900'},card:{backgroundColor:'#FFF',borderRadius:20,padding:17},cardTop:{flexDirection:'row',gap:10},name:{fontSize:17,fontWeight:'900',color:'#111827'},meta:{fontSize:11,color:'#9CA3AF',marginTop:4,textTransform:'capitalize'},badge:{backgroundColor:'#ECFDF5',borderRadius:10,paddingHorizontal:9,paddingVertical:6,height:28},badgeSoon:{backgroundColor:'#FEF3C7'},badgeCritical:{backgroundColor:'#FEE2E2'},badgeText:{fontSize:9,fontWeight:'900',color:'#374151',textTransform:'uppercase'},stockRow:{flexDirection:'row',gap:28,marginTop:14,paddingTop:12,borderTopWidth:1,borderTopColor:'#F3F4F6'},stockLabel:{fontSize:9,color:'#9CA3AF'},stockValue:{fontSize:13,fontWeight:'900',color:'#374151',marginTop:3},reason:{fontSize:11,color:'#6B7280',marginTop:12,textTransform:'capitalize'},actions:{flexDirection:'row',gap:8,justifyContent:'flex-end',marginTop:10},adjust:{width:34,height:34,borderRadius:10,backgroundColor:'#F3F4F6',alignItems:'center',justifyContent:'center'},adjustText:{fontSize:20,fontWeight:'900',color:'#111827'},empty:{backgroundColor:'#FFF',borderRadius:20,padding:28,alignItems:'center'},emptyTitle:{fontSize:17,fontWeight:'900',color:'#111827'},body:{fontSize:13,lineHeight:19,color:'#6B7280',marginTop:5},error:{backgroundColor:'#FFF',borderRadius:16,padding:14},errorTitle:{fontWeight:'900',color:'#991B1B'}});
