import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { createMeal, FoodItem, getFoods, hasAuthSession } from '../lib/api';

const MEAL_TYPES = ['breakfast', 'lunch', 'dinner', 'snack'] as const;
type MealType = typeof MEAL_TYPES[number];
type SelectedFood = FoodItem & { quantity: number };

export default function MealBuilderScreen() {
  const [name, setName] = useState(''); const [type, setType] = useState<MealType>('lunch'); const [query, setQuery] = useState('');
  const [foods, setFoods] = useState<FoodItem[]>([]); const [selected, setSelected] = useState<SelectedFood[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const loadFoods = useCallback(async (value = '') => { try { setError(null); setFoods(await getFoods(value.trim() || undefined)); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load foods.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void hasAuthSession().then((ok) => { if (!ok) router.replace('/'); else void loadFoods(); }); }, [loadFoods]);
  useEffect(() => { const timer = setTimeout(() => { if (query.trim()) void loadFoods(query); }, 250); return () => clearTimeout(timer); }, [query, loadFoods]);
  const totals = useMemo(() => selected.reduce((sum, food) => ({ calories: sum.calories + food.calories * food.quantity, protein: sum.protein + food.protein * food.quantity, carbs: sum.carbs + food.carbs * food.quantity, fat: sum.fat + food.fat * food.quantity }), { calories: 0, protein: 0, carbs: 0, fat: 0 }), [selected]);
  const addFood = (food: FoodItem) => setSelected((current) => current.some((item) => item.id === food.id) ? current.map((item) => item.id === food.id ? { ...item, quantity: item.quantity + 1 } : item) : [...current, { ...food, quantity: 1 }]);
  const changeQuantity = (id: string, delta: number) => setSelected((current) => current.flatMap((item) => item.id !== id ? [item] : item.quantity + delta > 0 ? [{ ...item, quantity: item.quantity + delta }] : []));
  const save = async () => { if (!name.trim() || !selected.length) { setError('Add a meal name and at least one food.'); return; } try { setSaving(true); setError(null); const now = new Date(); await createMeal({ name: name.trim(), type, eatenAt: now.toISOString(), dateKey: now.toISOString().slice(0, 10), items: selected.map((food) => ({ foodId: food.id, quantity: food.quantity })) }); router.replace('/meals'); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to save meal.'); } finally { setSaving(false); } };
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" /></View>;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.nav}><Pressable onPress={() => router.back()}><Text style={styles.navText}>← Meals</Text></Pressable><Text style={styles.eyebrow}>LOG A MEAL</Text></View>
    <Text style={styles.title}>Build your meal</Text><Text style={styles.subtitle}>Pick foods and quantities. Nutrition totals come from your saved food data.</Text>
    <Text style={styles.label}>Meal name</Text><TextInput value={name} onChangeText={setName} placeholder="e.g. Chicken & rice bowl" placeholderTextColor="#9CA3AF" style={styles.input} />
    <Text style={styles.label}>Type</Text><View style={styles.types}>{MEAL_TYPES.map((item) => <Pressable key={item} onPress={() => setType(item)} style={[styles.type, type === item && styles.typeActive]}><Text style={[styles.typeText, type === item && styles.typeTextActive]}>{item}</Text></Pressable>)}</View>
    <Text style={styles.label}>Find a food</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search foods..." placeholderTextColor="#9CA3AF" style={styles.input} />
    <View style={styles.foodList}>{foods.slice(0, 8).map((food) => <Pressable key={food.id} onPress={() => addFood(food)} style={styles.foodRow}><View style={styles.foodCopy}><Text style={styles.foodName}>{food.name}</Text><Text style={styles.foodMeta}>{Math.round(food.calories)} kcal · {Math.round(food.protein)}g protein</Text></View><Text style={styles.add}>+ Add</Text></Pressable>)}</View>
    <View style={styles.card}><Text style={styles.sectionTitle}>Selected foods</Text>{selected.length ? selected.map((food) => <View key={food.id} style={styles.selectedRow}><View style={styles.foodCopy}><Text style={styles.foodName}>{food.name}</Text><Text style={styles.foodMeta}>{Math.round(food.calories * food.quantity)} kcal</Text></View><View style={styles.stepper}><Pressable onPress={() => changeQuantity(food.id, -1)} style={styles.step}><Text style={styles.stepText}>−</Text></Pressable><Text style={styles.quantity}>{food.quantity}</Text><Pressable onPress={() => changeQuantity(food.id, 1)} style={styles.step}><Text style={styles.stepText}>+</Text></Pressable></View></View>) : <Text style={styles.empty}>Your meal is empty. Add a food above.</Text>}</View>
    <View style={styles.totalCard}><Text style={styles.sectionTitleLight}>Meal nutrition</Text><View style={styles.totalGrid}><Total label="Calories" value={`${Math.round(totals.calories)} kcal`} /><Total label="Protein" value={`${Math.round(totals.protein)} g`} /><Total label="Carbs" value={`${Math.round(totals.carbs)} g`} /><Total label="Fat" value={`${Math.round(totals.fat)} g`} /></View></View>
    {error ? <Text style={styles.error}>{error}</Text> : null}<Pressable disabled={saving} onPress={() => void save()} style={[styles.primary, saving && styles.disabled]}><Text style={styles.primaryText}>{saving ? 'Saving…' : 'Save meal'}</Text></Pressable>
  </ScrollView></SafeAreaView>;
}
function Total({ label, value }: { label: string; value: string }) { return <View><Text style={styles.totalLabel}>{label}</Text><Text style={styles.totalValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:'#F7F8FA'},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:'#F7F8FA'},content:{padding:20,gap:12,paddingBottom:40},nav:{flexDirection:'row',justifyContent:'space-between'},navText:{fontWeight:'900',color:'#111827'},eyebrow:{fontSize:10,letterSpacing:1.4,fontWeight:'900',color:'#6B7280'},title:{fontSize:30,fontWeight:'900',color:'#111827'},subtitle:{fontSize:14,lineHeight:21,color:'#6B7280'},label:{fontSize:12,fontWeight:'900',color:'#374151',marginTop:3},input:{backgroundColor:'#FFF',borderRadius:15,paddingHorizontal:15,paddingVertical:13,fontSize:14,color:'#111827'},types:{flexDirection:'row',gap:8},type:{paddingHorizontal:13,paddingVertical:9,borderRadius:12,backgroundColor:'#E5E7EB'},typeActive:{backgroundColor:'#111827'},typeText:{fontSize:11,fontWeight:'800',color:'#4B5563',textTransform:'capitalize'},typeTextActive:{color:'#FFF'},foodList:{backgroundColor:'#FFF',borderRadius:18,overflow:'hidden'},foodRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:14,borderBottomWidth:1,borderBottomColor:'#F3F4F6'},foodCopy:{flex:1},foodName:{fontSize:14,fontWeight:'900',color:'#111827'},foodMeta:{fontSize:10,color:'#9CA3AF',marginTop:3},add:{fontSize:12,fontWeight:'900',color:'#111827'},card:{backgroundColor:'#FFF',borderRadius:18,padding:16},sectionTitle:{fontSize:15,fontWeight:'900',color:'#111827',marginBottom:10},selectedRow:{flexDirection:'row',alignItems:'center',paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#F3F4F6'},stepper:{flexDirection:'row',alignItems:'center',gap:9},step:{width:28,height:28,borderRadius:9,backgroundColor:'#F3F4F6',alignItems:'center',justifyContent:'center'},stepText:{fontSize:17,fontWeight:'900'},quantity:{fontSize:13,fontWeight:'900',minWidth:14,textAlign:'center'},empty:{fontSize:12,color:'#9CA3AF'},totalCard:{backgroundColor:'#111827',borderRadius:20,padding:17},sectionTitleLight:{fontSize:15,fontWeight:'900',color:'#FFF',marginBottom:12},totalGrid:{flexDirection:'row',justifyContent:'space-between'},totalLabel:{fontSize:10,color:'#9CA3AF'},totalValue:{fontSize:14,fontWeight:'900',color:'#FFF',marginTop:4},error:{fontSize:12,lineHeight:18,color:'#991B1B',backgroundColor:'#FEE2E2',padding:12,borderRadius:12},primary:{backgroundColor:'#111827',borderRadius:15,padding:15},disabled:{opacity:.55},primaryText:{color:'#FFF',fontWeight:'900',textAlign:'center'}});
