import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { hasAuthSession } from '../lib/api';
import { getRecipeMatches, RecipeMatch } from '../lib/recipe-api';
import { useAppLocale, t, tx } from '../lib/i18n';

export default function RecipeMatchScreen() {
  const { locale, rtl } = useAppLocale();
  const [recipes, setRecipes] = useState<RecipeMatch[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [adding, setAdding] = useState<string | null>(null); const [added, setAdded] = useState<Record<string, boolean>>({}); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setError(null); setRecipes(await getRecipeMatches()); } catch (e) { setError(e instanceof Error ? e.message : tx(locale, 'Unable to match recipes.', 'امکان تطبیق دستورها نیست.')); } finally { setLoading(false); setRefreshing(false); } }, [locale]);
  useEffect(() => { void hasAuthSession().then((ok) => { if (ok) void load(); else router.replace('/'); }); }, [load]);
  const addMissingToBasket = async (recipe: RecipeMatch) => { if (!recipe.missing.length || added[recipe.recipeId]) return; try { setAdding(recipe.recipeId); setError(null); const { addRecipeMissingToBasket } = await import('../lib/recipe-api'); await addRecipeMissingToBasket(recipe.recipeId, recipe.missing); setAdded((current) => ({ ...current, [recipe.recipeId]: true })); } catch (e) { setError(e instanceof Error ? e.message : tx(locale, 'Unable to add missing ingredients.', 'امکان افزودن مواد کمبود به سبد نیست.')); } finally { setAdding(null); } };
  const openBudget = (recipe: RecipeMatch) => router.push({ pathname: '/budget', params: { recipeId: recipe.recipeId, name: recipe.name } });
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" /></View>;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} />}>
    <View style={[styles.nav, rtl && styles.rtl]}><Pressable onPress={() => router.back()}><Text style={[styles.navText, rtl && styles.rtlText]}>{t(locale, 'back')}</Text></Pressable><Pressable onPress={() => router.push('/shopping')}><Text style={[styles.navText, rtl && styles.rtlText]}>{t(locale, 'smartBasket')}</Text></Pressable></View>
    <Text style={[styles.eyebrow, rtl && styles.rtlText]}>{t(locale, 'recipeIntelligence')}</Text><Text style={[styles.title, rtl && styles.rtlText]}>{t(locale, 'cookStockTitle')}</Text><Text style={[styles.subtitle, rtl && styles.rtlText]}>{t(locale, 'cookStockSubtitle')}</Text>
    {error ? <View style={styles.error}><Text style={[styles.errorTitle, rtl && styles.rtlText]}>{tx(locale, 'Recipe matching unavailable', 'تطبیق دستورها در دسترس نیست')}</Text><Text style={[styles.body, rtl && styles.rtlText]}>{error}</Text><Pressable onPress={() => void load()} style={styles.retry}><Text style={styles.retryText}>{t(locale, 'retry')}</Text></Pressable></View> : null}
    {recipes.length ? recipes.map((recipe) => <View key={recipe.recipeId} style={styles.card}><View style={[styles.top, rtl && styles.rtl]}><View style={styles.copy}><Text style={[styles.name, rtl && styles.rtlText]}>{recipe.name}</Text><Text style={[styles.meta, rtl && styles.rtlText]}>{recipe.calories} kcal · {Math.round(recipe.protein)}g {t(locale, 'protein').toLowerCase()}</Text></View><View style={styles.score}><Text style={styles.scoreValue}>{recipe.score}</Text><Text style={styles.scoreLabel}>{tx(locale, 'score', 'امتیاز')}</Text></View></View><View style={styles.coverage}><View style={[styles.coverageFill, { width: `${recipe.coveragePercent}%` }]} /></View><Text style={[styles.coverageText, rtl && styles.rtlText]}>{recipe.coveragePercent}% {tx(locale, 'ingredients available', 'مواد موجود')} · {recipe.missingCount} {tx(locale, 'missing', 'کمبود')}</Text>{recipe.missing.length ? <><Text style={[styles.section, rtl && styles.rtlText]}>{t(locale, 'addToBasket')}</Text>{recipe.missing.map((item) => <View key={item.foodId} style={[styles.item, rtl && styles.rtl]}><Text style={[styles.itemName, rtl && styles.rtlText]}>{item.name}</Text><Text style={[styles.itemQty, rtl && styles.rtlText]}>{item.quantity} {item.unit}</Text></View>)}<View style={styles.buttonRow}><Pressable disabled={adding === recipe.recipeId || added[recipe.recipeId]} onPress={() => void addMissingToBasket(recipe)} style={[styles.basketButton, (adding === recipe.recipeId || added[recipe.recipeId]) && styles.disabled]}><Text style={styles.basketText}>{adding === recipe.recipeId ? t(locale, 'adding') : added[recipe.recipeId] ? t(locale, 'addedBasket') : tx(locale, 'Add missing ingredients', 'افزودن مواد کمبود')}</Text></Pressable><Pressable onPress={() => openBudget(recipe)} style={styles.budgetButton}><Text style={styles.budgetText}>{tx(locale, 'Budget impact', 'اثر بودجه')}</Text></Pressable></View></> : <><View style={styles.ready}><Text style={styles.readyText}>{t(locale, 'readyToCook')}</Text></View><Pressable onPress={() => openBudget(recipe)} style={styles.budgetButton}><Text style={styles.budgetText}>{tx(locale, 'Check budget', 'بررسی بودجه')}</Text></Pressable></>}<View style={[styles.macros, rtl && styles.rtl]}><Text style={styles.macro}>P {Math.round(recipe.protein)}g</Text><Text style={styles.macro}>C {Math.round(recipe.carbs)}g</Text><Text style={styles.macro}>F {Math.round(recipe.fat)}g</Text></View></View>) : <View style={styles.empty}><Text style={[styles.emptyTitle, rtl && styles.rtlText]}>{t(locale, 'noRecipes')}</Text><Text style={[styles.body, rtl && styles.rtlText]}>{t(locale, 'recipeHelp')}</Text></View>}
    <Pressable onPress={() => router.push('/shopping')} style={styles.primary}><Text style={styles.primaryText}>{t(locale, 'openBasket')}</Text></Pressable>
  </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F8FA'},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:'#F7F8FA'},content:{padding:20,gap:14,paddingBottom:40},nav:{flexDirection:'row',justifyContent:'space-between'},rtl:{flexDirection:'row-reverse'},rtlText:{textAlign:'right',direction:'rtl'},navText:{fontWeight:'900',color:'#111827'},eyebrow:{fontSize:10,letterSpacing:1.5,fontWeight:'900',color:'#6B7280'},title:{fontSize:30,fontWeight:'900',color:'#111827'},subtitle:{fontSize:14,lineHeight:21,color:'#6B7280'},card:{backgroundColor:'#FFF',borderRadius:20,padding:17},top:{flexDirection:'row',gap:12},copy:{flex:1},name:{fontSize:17,fontWeight:'900',color:'#111827'},meta:{fontSize:11,color:'#9CA3AF',marginTop:4},score:{width:48,height:48,borderRadius:14,backgroundColor:'#111827',alignItems:'center',justifyContent:'center'},scoreValue:{fontSize:16,fontWeight:'900',color:'#FFF'},scoreLabel:{fontSize:7,color:'#9CA3AF'},coverage:{height:7,backgroundColor:'#E5E7EB',borderRadius:8,overflow:'hidden',marginTop:15},coverageFill:{height:7,backgroundColor:'#111827',borderRadius:8},coverageText:{fontSize:10,color:'#6B7280',marginTop:6},section:{fontSize:11,fontWeight:'900',color:'#374151',marginTop:13},item:{flexDirection:'row',justifyContent:'space-between',paddingVertical:8,borderBottomWidth:1,borderBottomColor:'#F3F4F6'},itemName:{fontSize:12,color:'#374151'},itemQty:{fontSize:11,fontWeight:'800',color:'#6B7280'},buttonRow:{flexDirection:'row',gap:8,marginTop:12},basketButton:{flex:1,backgroundColor:'#111827',borderRadius:12,padding:12},basketText:{color:'#FFF',fontSize:11,fontWeight:'900',textAlign:'center'},budgetButton:{marginTop:12,flex:1,backgroundColor:'#E5E7EB',borderRadius:12,padding:12},budgetText:{color:'#111827',fontSize:11,fontWeight:'900',textAlign:'center'},disabled:{opacity:0.55},ready:{backgroundColor:'#ECFDF5',borderRadius:11,padding:10,marginTop:12},readyText:{fontSize:11,fontWeight:'800',color:'#065F46',textAlign:'center'},macros:{flexDirection:'row',gap:16,marginTop:12},macro:{fontSize:10,fontWeight:'800',color:'#6B7280'},error:{backgroundColor:'#FFF',borderRadius:16,padding:16},errorTitle:{fontWeight:'900',color:'#991B1B'},body:{fontSize:13,lineHeight:19,color:'#6B7280',marginTop:5},retry:{alignSelf:'flex-start',backgroundColor:'#111827',borderRadius:10,paddingHorizontal:13,paddingVertical:8,marginTop:10},retryText:{color:'#FFF',fontWeight:'900'},empty:{backgroundColor:'#FFF',borderRadius:20,padding:26,alignItems:'center'},emptyTitle:{fontSize:17,fontWeight:'900',color:'#111827'},primary:{backgroundColor:'#111827',borderRadius:15,padding:15},primaryText:{color:'#FFF',fontWeight:'900',textAlign:'center'}});