import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { hasAuthSession } from '../lib/api';
import { getRecipeMatches, RecipeMatch } from '../lib/recipe-api';

export default function RecipeMatchScreen() {
  const [recipes, setRecipes] = useState<RecipeMatch[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [adding, setAdding] = useState<string | null>(null);
  const [added, setAdded] = useState<Record<string, boolean>>({});
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setError(null); setRecipes(await getRecipeMatches()); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to match recipes.'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void hasAuthSession().then((ok) => { if (ok) void load(); else router.replace('/'); }); }, [load]);
  const addMissingToBasket = async (recipe: RecipeMatch) => {
    if (!recipe.missing.length || added[recipe.recipeId]) return;
    try {
      setAdding(recipe.recipeId);
      setError(null);
      const { addRecipeMissingToBasket } = await import('../lib/recipe-api');
      await addRecipeMissingToBasket(recipe.recipeId, recipe.missing);
      setAdded((current) => ({ ...current, [recipe.recipeId]: true }));
    } catch (e) { setError(e instanceof Error ? e.message : 'Unable to add missing ingredients.'); } finally { setAdding(null); }
  };
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" /></View>;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} />}>
    <View style={styles.nav}><Pressable onPress={() => router.back()}><Text style={styles.navText}>← Back</Text></Pressable><Pressable onPress={() => router.push('/shopping')}><Text style={styles.navText}>Smart Basket</Text></Pressable></View>
    <Text style={styles.eyebrow}>RECIPE INTELLIGENCE</Text><Text style={styles.title}>Cook with what you have</Text><Text style={styles.subtitle}>Recipes are ranked by how much of the ingredients you already have at home.</Text>
    {error ? <View style={styles.error}><Text style={styles.errorTitle}>Recipe matching unavailable</Text><Text style={styles.body}>{error}</Text><Pressable onPress={() => void load()} style={styles.retry}><Text style={styles.retryText}>Retry</Text></Pressable></View> : null}
    {recipes.length ? recipes.map((recipe) => <View key={recipe.recipeId} style={styles.card}><View style={styles.top}><View style={styles.copy}><Text style={styles.name}>{recipe.name}</Text><Text style={styles.meta}>{recipe.calories} kcal · {Math.round(recipe.protein)}g protein</Text></View><View style={styles.score}><Text style={styles.scoreValue}>{recipe.score}</Text><Text style={styles.scoreLabel}>score</Text></View></View><View style={styles.coverage}><View style={[styles.coverageFill, { width: `${recipe.coveragePercent}%` }]} /></View><Text style={styles.coverageText}>{recipe.coveragePercent}% ingredients available · {recipe.missingCount} missing</Text>{recipe.missing.length ? <><Text style={styles.section}>Add to basket</Text>{recipe.missing.map((item) => <View key={item.foodId} style={styles.item}><Text style={styles.itemName}>{item.name}</Text><Text style={styles.itemQty}>{item.quantity} {item.unit}</Text></View>)}<Pressable disabled={adding === recipe.recipeId || added[recipe.recipeId]} onPress={() => void addMissingToBasket(recipe)} style={[styles.basketButton, (adding === recipe.recipeId || added[recipe.recipeId]) && styles.disabled]}><Text style={styles.basketText}>{adding === recipe.recipeId ? 'Adding…' : added[recipe.recipeId] ? '✓ Added to Smart Basket' : 'Add missing ingredients'}</Text></Pressable></> : <View style={styles.ready}><Text style={styles.readyText}>✓ Ready to cook — everything is in stock</Text></View>}<View style={styles.macros}><Text style={styles.macro}>P {Math.round(recipe.protein)}g</Text><Text style={styles.macro}>C {Math.round(recipe.carbs)}g</Text><Text style={styles.macro}>F {Math.round(recipe.fat)}g</Text></View></View>) : <View style={styles.empty}><Text style={styles.emptyTitle}>No recipes yet</Text><Text style={styles.body}>Once recipes have ingredients, the assistant can match them against your household inventory.</Text></View>}
    <Pressable onPress={() => router.push('/shopping')} style={styles.primary}><Text style={styles.primaryText}>Open Smart Basket</Text></Pressable>
  </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F8FA'},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:'#F7F8FA'},content:{padding:20,gap:14,paddingBottom:40},nav:{flexDirection:'row',justifyContent:'space-between'},navText:{fontWeight:'900',color:'#111827'},eyebrow:{fontSize:10,letterSpacing:1.5,fontWeight:'900',color:'#6B7280'},title:{fontSize:30,fontWeight:'900',color:'#111827'},subtitle:{fontSize:14,lineHeight:21,color:'#6B7280'},card:{backgroundColor:'#FFF',borderRadius:20,padding:17},top:{flexDirection:'row',gap:12},copy:{flex:1},name:{fontSize:17,fontWeight:'900',color:'#111827'},meta:{fontSize:11,color:'#9CA3AF',marginTop:4},score:{width:48,height:48,borderRadius:14,backgroundColor:'#111827',alignItems:'center',justifyContent:'center'},scoreValue:{fontSize:16,fontWeight:'900',color:'#FFF'},scoreLabel:{fontSize:7,color:'#9CA3AF'},coverage:{height:7,backgroundColor:'#E5E7EB',borderRadius:8,overflow:'hidden',marginTop:15},coverageFill:{height:7,backgroundColor:'#111827',borderRadius:8},coverageText:{fontSize:10,color:'#6B7280',marginTop:6},section:{fontSize:11,fontWeight:'900',color:'#374151',marginTop:13},item:{flexDirection:'row',justifyContent:'space-between',paddingVertical:8,borderBottomWidth:1,borderBottomColor:'#F3F4F6'},itemName:{fontSize:12,color:'#374151'},itemQty:{fontSize:11,fontWeight:'800',color:'#6B7280'},basketButton:{marginTop:12,backgroundColor:'#111827',borderRadius:12,padding:12},basketText:{color:'#FFF',fontSize:11,fontWeight:'900',textAlign:'center'},disabled:{opacity:0.55},ready:{backgroundColor:'#ECFDF5',borderRadius:11,padding:10,marginTop:12},readyText:{fontSize:11,fontWeight:'800',color:'#065F46'},macros:{flexDirection:'row',gap:16,marginTop:12},macro:{fontSize:10,fontWeight:'800',color:'#6B7280'},error:{backgroundColor:'#FFF',borderRadius:16,padding:16},errorTitle:{fontWeight:'900',color:'#991B1B'},body:{fontSize:13,lineHeight:19,color:'#6B7280',marginTop:5},retry:{alignSelf:'flex-start',backgroundColor:'#111827',borderRadius:10,paddingHorizontal:13,paddingVertical:8,marginTop:10},retryText:{color:'#FFF',fontWeight:'900'},empty:{backgroundColor:'#FFF',borderRadius:20,padding:26,alignItems:'center'},emptyTitle:{fontSize:17,fontWeight:'900',color:'#111827'},primary:{backgroundColor:'#111827',borderRadius:15,padding:15},primaryText:{color:'#FFF',fontWeight:'900',textAlign:'center'}});