import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Link } from 'expo-router';
import { Reminder, completeReminder, createReminder, deleteReminder, getReminders } from '../lib/api';
import { colors, radius, spacing, typography, shadows } from '../lib/design-system';
import { AnimatedIn, MotionPress } from '../lib/motion-components';

export default function RemindersScreen() {
  const [items,setItems]=useState<Reminder[]>([]); const [title,setTitle]=useState(''); const [time,setTime]=useState('09:00'); const [type,setType]=useState('general'); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setError(null);setItems(await getReminders());}catch(err){setError(err instanceof Error?err.message:'Unable to load reminders');}},[]);
  useEffect(()=>{void load();},[load]);
  const add=async()=>{if(!title.trim()){setError('Add a title first.');return;}try{setBusy(true);setError(null);await createReminder({title:title.trim(),time:time.trim(),type:type.trim()||'general'});setTitle('');await load();}catch(err){setError(err instanceof Error?err.message:'Unable to create reminder');}finally{setBusy(false);}};
  const complete=async(id:string)=>{try{await completeReminder(id);await load();}catch(err){setError(err instanceof Error?err.message:'Unable to complete reminder');}};
  const remove=async(id:string)=>{try{await deleteReminder(id);await load();}catch(err){setError(err instanceof Error?err.message:'Unable to delete reminder');}};
  return <ScrollView contentContainerStyle={styles.content}><AnimatedIn><View style={styles.header}><View><Text style={styles.eyebrow}>MY PERSONAL ASSISTANT</Text><Text style={styles.title}>Reminders ⏰</Text><Text style={styles.subtitle}>Keep the things that matter from falling through the cracks.</Text></View><Link href="/" asChild><MotionPress style={styles.back}><Text style={styles.backText}>Home</Text></MotionPress></Link></View></AnimatedIn>
    <AnimatedIn delay={100}><View style={[styles.card,shadows.subtle]}><Text style={styles.sectionTitle}>Add a reminder</Text><TextInput value={title} onChangeText={setTitle} placeholder="e.g. Drink water" placeholderTextColor={colors.textMuted} style={styles.input}/><View style={styles.row}><TextInput value={time} onChangeText={setTime} placeholder="09:00" placeholderTextColor={colors.textMuted} style={[styles.input,styles.half]}/><TextInput value={type} onChangeText={setType} placeholder="general" placeholderTextColor={colors.textMuted} style={[styles.input,styles.half]}/></View>{error?<Text style={styles.error}>{error}</Text>:null}<MotionPress onPress={()=>void add()} disabled={busy} style={styles.primary}>{busy?<ActivityIndicator color={colors.surface}/>:<Text style={styles.primaryText}>Create reminder</Text>}</MotionPress></View></AnimatedIn>
    <AnimatedIn delay={180}><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Upcoming</Text><MotionPress onPress={()=>void load()}><Text style={styles.refresh}>Refresh</Text></MotionPress></View></AnimatedIn>
    <AnimatedIn delay={240}><View style={[styles.card,shadows.subtle]}>{items.length===0?<Text style={styles.muted}>Nothing pending. You are all caught up. ✨</Text>:items.map((item,index)=><AnimatedIn key={item.id} delay={270+index*70}><View style={styles.reminderRow}><View style={styles.reminderCopy}><Text style={styles.reminderTitle}>{item.title}</Text><Text style={styles.muted}>{item.type} · {new Date(item.scheduledAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</Text></View><View style={styles.actions}><MotionPress onPress={()=>void complete(item.id)} style={styles.smallButton}><Text style={styles.smallButtonText}>Done</Text></MotionPress><MotionPress onPress={()=>void remove(item.id)} style={styles.deleteButton}><Text style={styles.deleteText}>×</Text></MotionPress></View></View></AnimatedIn>)}</View></AnimatedIn>
  </ScrollView>;
}
const styles=StyleSheet.create({content:{padding:spacing.xl,gap:spacing.md,paddingTop:40,paddingBottom:40,backgroundColor:colors.paper,minHeight:'100%'},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},eyebrow:{...typography.eyebrow,color:colors.textMuted},title:{...typography.title1,color:colors.text,marginTop:5},subtitle:{color:colors.textMuted,marginTop:4,maxWidth:290,lineHeight:19},back:{paddingHorizontal:12,paddingVertical:9,backgroundColor:colors.surfaceWarm,borderRadius:radius.md},backText:{color:colors.text,fontWeight:'800',fontSize:12},card:{backgroundColor:colors.surface,borderRadius:radius.xl,padding:18,gap:11,borderWidth:1,borderColor:colors.border},sectionTitle:{color:colors.text,fontSize:18,fontWeight:'800'},input:{minHeight:50,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:14,color:colors.text,backgroundColor:colors.surface},row:{flexDirection:'row',gap:10},half:{flex:1},primary:{minHeight:50,borderRadius:radius.md,alignItems:'center',justifyContent:'center',backgroundColor:colors.ink,marginTop:3},primaryText:{color:colors.surface,fontWeight:'800'},error:{color:colors.dangerText,fontSize:12},sectionHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:4},refresh:{color:colors.text,fontWeight:'700',fontSize:12},muted:{color:colors.textMuted,fontSize:12,lineHeight:18},reminderRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingVertical:10,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.border},reminderCopy:{flex:1,paddingRight:12},reminderTitle:{color:colors.text,fontWeight:'800',fontSize:15},actions:{flexDirection:'row',gap:7,alignItems:'center'},smallButton:{backgroundColor:colors.ink,paddingHorizontal:10,paddingVertical:8,borderRadius:radius.sm},smallButtonText:{color:colors.surface,fontWeight:'800',fontSize:11},deleteButton:{width:30,height:30,borderRadius:radius.sm,backgroundColor:colors.surfaceWarm,alignItems:'center',justifyContent:'center'},deleteText:{color:colors.textMuted,fontSize:18,lineHeight:18}});