import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { hasAuthSession } from '../lib/api';
import { getSmartShoppingList, SmartShoppingItem } from '../lib/shopping-api';
import { BasketItem, completeBasketItem, getBasket } from '../lib/shopping-basket-api';

export default function ShoppingScreen() {
  const [suggestions,setSuggestions]=useState<SmartShoppingItem[]>([]); const [basket,setBasket]=useState<BasketItem[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setError(null);const [s,b]=await Promise.all([getSmartShoppingList(),getBasket()]);setSuggestions(s);setBasket(b);}catch(e){setError(e instanceof Error?e.message:'Unable to load your basket.');}finally{setLoading(false);setRefreshing(false);}},[]);
  useEffect(()=>{void hasAuthSession().then(ok=>{if(ok)void load();else router.replace('/');});},[load]);
  const critical=useMemo(()=>suggestions.filter(i=>i.urgency==='critical').length,[suggestions]);
  const complete=async(id:string)=>{try{setBusy(id);await completeBasketItem(id);setBasket(items=>items.filter(i=>i.id!==id));}catch(e){setError(e instanceof Error?e.message:'Unable to update basket.');}finally{setBusy(null);}};
  if(loading)return <View style={styles.center}><ActivityIndicator size="large"/></View>;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load();}}/>}>
    <View style={styles.nav}><Pressable onPress={()=>router.back()}><Text style={styles.navText}>← Back</Text></Pressable></View>
    <Text style={styles.eyebrow}>SHOPPING</Text><Text style={styles.title}>Your basket</Text><Text style={styles.subtitle}>Everything you need, without the clutter.</Text>
    <View style={styles.summary}><View><Text style={styles.summaryValue}>{basket.length}</Text><Text style={styles.summaryLabel}>in basket</Text></View><View><Text style={styles.summaryValue}>{critical}</Text><Text style={styles.summaryLabel}>need soon</Text></View></View>
    {error?<View style={styles.card}><Text style={styles.cardTitle}>Something went wrong</Text><Text style={styles.body}>{error}</Text><Pressable onPress={()=>void load()} style={styles.button}><Text style={styles.buttonText}>Try again</Text></Pressable></View>:null}
    {basket.length>0?<View style={styles.section}><Text style={styles.sectionTitle}>To buy</Text>{basket.map(item=><View key={item.id} style={styles.item}><Pressable accessibilityRole="checkbox" accessibilityLabel={`Mark ${item.name} as bought`} disabled={busy===item.id} onPress={()=>void complete(item.id)} style={styles.check}><Text style={styles.checkText}>{busy===item.id?'…':'✓'}</Text></Pressable><View style={styles.itemCopy}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.quantity} {item.unit}{item.source==='recipe'?' · from a recipe':''}</Text></View></View>)}</View>:<View style={styles.empty}><Text style={styles.emptyTitle}>Basket is clear 🎉</Text><Text style={styles.body}>Nothing is waiting for you to buy.</Text></View>}
    {suggestions.length>0?<View style={styles.suggest}><Text style={styles.sectionTitle}>Running low</Text><Text style={styles.body}>These are suggestions only. Add them when you need them.</Text><View style={styles.chips}>{suggestions.slice(0,4).map(item=><View key={item.foodId} style={styles.chip}><Text style={styles.chipText}>{item.name}</Text></View>)}</View></View>:null}
    <Pressable onPress={()=>router.push('/recipe-match')} style={styles.secondary}><Text style={styles.secondaryText}>Find a meal to cook</Text></Pressable>
  </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F8FA'},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:'#F7F8FA'},content:{padding:20,gap:14,paddingBottom:40},nav:{height:26},navText:{fontWeight:'900',color:'#111827'},eyebrow:{fontSize:10,letterSpacing:1.5,fontWeight:'900',color:'#6B7280'},title:{fontSize:32,fontWeight:'900',color:'#111827'},subtitle:{fontSize:14,lineHeight:21,color:'#6B7280'},summary:{backgroundColor:'#111827',borderRadius:20,padding:18,flexDirection:'row',gap:60},summaryValue:{fontSize:25,fontWeight:'900',color:'#FFF'},summaryLabel:{fontSize:10,color:'#9CA3AF',marginTop:2},card:{backgroundColor:'#FFF',borderRadius:18,padding:16},cardTitle:{fontSize:16,fontWeight:'900',color:'#111827'},body:{fontSize:13,lineHeight:19,color:'#6B7280',marginTop:5},button:{alignSelf:'flex-start',backgroundColor:'#111827',borderRadius:11,paddingHorizontal:14,paddingVertical:10,marginTop:10},buttonText:{color:'#FFF',fontWeight:'900'},section:{backgroundColor:'#FFF',borderRadius:20,padding:17},sectionTitle:{fontSize:16,fontWeight:'900',color:'#111827',marginBottom:8},item:{flexDirection:'row',alignItems:'center',paddingVertical:12,borderBottomWidth:1,borderBottomColor:'#F3F4F6'},check:{width:28,height:28,borderRadius:14,borderWidth:2,borderColor:'#D1D5DB',alignItems:'center',justifyContent:'center'},checkText:{fontSize:12,fontWeight:'900',color:'#6B7280'},itemCopy:{marginLeft:12,flex:1},name:{fontSize:14,fontWeight:'900',color:'#111827'},meta:{fontSize:11,color:'#9CA3AF',marginTop:3},suggest:{backgroundColor:'#FFF',borderRadius:20,padding:17},chips:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:10},chip:{backgroundColor:'#F3F4F6',borderRadius:20,paddingHorizontal:10,paddingVertical:7},chipText:{fontSize:10,fontWeight:'800',color:'#4B5563'},secondary:{backgroundColor:'#FFF',borderRadius:14,padding:14},secondaryText:{textAlign:'center',fontWeight:'900',color:'#111827'},empty:{backgroundColor:'#FFF',borderRadius:20,padding:28,alignItems:'center'},emptyTitle:{fontSize:18,fontWeight:'900',color:'#111827'}});