import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { hasAuthSession } from '../lib/api';
import { getSmartShoppingList, SmartShoppingItem } from '../lib/shopping-api';
import { BasketItem, completeBasketItem, getBasket } from '../lib/shopping-basket-api';
import { normalizeProductKey } from '../lib/price-api';
import { useAppLocale } from '../lib/i18n';

const copy = {
  en: { back:'Back', eyebrow:'SHOPPING', title:'Your basket', subtitle:'Everything you need, without the clutter.', inBasket:'in basket', needSoon:'need soon', problem:'Something went wrong', retry:'Try again', toBuy:'To buy', bought:'Mark item as bought', fromRecipe:' · from a recipe', viewPrice:'View price history →', clear:'Basket is clear 🎉', clearHint:'Nothing is waiting for you to buy.', low:'Running low', lowHint:'These are suggestions only. Add them when you need them.', findMeal:'Find a meal to cook', load:'Unable to load your basket.', update:'Unable to update basket.' },
  fa: { back:'برگشت', eyebrow:'خرید', title:'سبد خرید تو', subtitle:'همه چیزهایی که لازم داری، بدون شلوغی اضافه.', inBasket:'در سبد', needSoon:'به‌زودی لازم', problem:'یک مشکلی پیش آمد', retry:'تلاش دوباره', toBuy:'برای خرید', bought:'علامت‌گذاری به‌عنوان خریداری‌شده', fromRecipe:' · از یک رسپی', viewPrice:'مشاهده قیمت و تاریخچه ←', clear:'سبد خالیه 🎉', clearHint:'چیزی برای خرید منتظر تو نیست.', low:'رو به اتمام', lowHint:'این‌ها فقط پیشنهادند؛ هر وقت لازم داشتی اضافه‌شان کن.', findMeal:'یک غذا برای پخت پیدا کن', load:'سبد خرید بارگذاری نشد.', update:'به‌روزرسانی سبد ناموفق بود.' },
};

export default function ShoppingScreen() {
  const locale=useAppLocale(); const text=copy[locale]; const rtl=locale==='fa';
  const [suggestions,setSuggestions]=useState<SmartShoppingItem[]>([]); const [basket,setBasket]=useState<BasketItem[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setError(null);const[s,b]=await Promise.all([getSmartShoppingList(),getBasket()]);setSuggestions(s);setBasket(b);}catch(e){setError(e instanceof Error?e.message:text.load)}finally{setLoading(false);setRefreshing(false)}},[text.load]);
  useEffect(()=>{void hasAuthSession().then(ok=>{if(ok)void load();else router.replace('/');});},[load]);
  const critical=useMemo(()=>suggestions.filter(i=>i.urgency==='critical').length,[suggestions]);
  const complete=async(id:string)=>{try{setBusy(id);await completeBasketItem(id);setBasket(items=>items.filter(i=>i.id!==id));}catch(e){setError(e instanceof Error?e.message:text.update)}finally{setBusy(null);}};
  if(loading)return <View style={styles.center}><ActivityIndicator size="large" accessibilityLabel={locale==='fa'?'در حال بارگذاری':'Loading'}/></View>;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={[styles.content,rtl&&styles.rtl]} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load();}}/>}>
    <View style={styles.nav}><Pressable onPress={()=>router.back()}><Text style={styles.navText}>{rtl?'→':'←'} {text.back}</Text></Pressable></View>
    <Text style={[styles.eyebrow,rtl&&styles.textRtl]}>{text.eyebrow}</Text><Text style={[styles.title,rtl&&styles.textRtl]}>{text.title}</Text><Text style={[styles.subtitle,rtl&&styles.textRtl]}>{text.subtitle}</Text>
    <View style={[styles.summary,rtl&&styles.rtl]}><View><Text style={[styles.summaryValue,rtl&&styles.textRtl]}>{basket.length}</Text><Text style={[styles.summaryLabel,rtl&&styles.textRtl]}>{text.inBasket}</Text></View><View><Text style={[styles.summaryValue,rtl&&styles.textRtl]}>{critical}</Text><Text style={[styles.summaryLabel,rtl&&styles.textRtl]}>{text.needSoon}</Text></View></View>
    {error?<View style={styles.card}><Text style={[styles.cardTitle,rtl&&styles.textRtl]}>{text.problem}</Text><Text style={[styles.body,rtl&&styles.textRtl]}>{error}</Text><Pressable onPress={()=>void load()} style={styles.button}><Text style={styles.buttonText}>{text.retry}</Text></Pressable></View>:null}
    {basket.length>0?<View style={styles.section}><Text style={[styles.sectionTitle,rtl&&styles.textRtl]}>{text.toBuy}</Text>{basket.map(item=><View key={item.id} style={[styles.item,rtl&&styles.rtl]}><Pressable accessibilityRole="checkbox" accessibilityLabel={`${text.bought}: ${item.name}`} disabled={busy===item.id} onPress={()=>void complete(item.id)} style={styles.check}><Text style={styles.checkText}>{busy===item.id?'…':'✓'}</Text></Pressable><View style={styles.itemCopy}><Text style={[styles.name,rtl&&styles.textRtl]}>{item.name}</Text><Text style={[styles.meta,rtl&&styles.textRtl]}>{item.quantity} {item.unit}{item.source==='recipe'?text.fromRecipe:''}</Text><Pressable accessibilityRole="button" onPress={()=>router.push({pathname:'/price-history',params:{productKey:normalizeProductKey(item.name),name:item.name}})}><Text style={[styles.priceLink,rtl&&styles.textRtl]}>{text.viewPrice}</Text></Pressable></View></View>)}</View>:<View style={styles.empty}><Text style={[styles.emptyTitle,rtl&&styles.textRtl]}>{text.clear}</Text><Text style={[styles.body,rtl&&styles.textRtl]}>{text.clearHint}</Text></View>}
    {suggestions.length>0?<View style={styles.suggest}><Text style={[styles.sectionTitle,rtl&&styles.textRtl]}>{text.low}</Text><Text style={[styles.body,rtl&&styles.textRtl]}>{text.lowHint}</Text><View style={styles.chips}>{suggestions.slice(0,4).map(item=><View key={item.foodId} style={styles.chip}><Text style={styles.chipText}>{item.name}</Text></View>)}</View></View>:null}
    <Pressable onPress={()=>router.push('/recipe-match')} style={styles.secondary}><Text style={[styles.secondaryText,rtl&&styles.textRtl]}>{text.findMeal}</Text></Pressable>
  </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F8FA'},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:'#F7F8FA'},content:{padding:20,gap:14,paddingBottom:40},rtl:{direction:'rtl'},textRtl:{textAlign:'right'},nav:{height:26},navText:{fontWeight:'900',color:'#111827'},eyebrow:{fontSize:10,letterSpacing:1.5,fontWeight:'900',color:'#6B7280'},title:{fontSize:32,fontWeight:'900',color:'#111827'},subtitle:{fontSize:14,lineHeight:21,color:'#6B7280'},summary:{backgroundColor:'#111827',borderRadius:20,padding:18,flexDirection:'row',gap:60},summaryValue:{fontSize:25,fontWeight:'900',color:'#FFF'},summaryLabel:{fontSize:10,color:'#9CA3AF',marginTop:2},card:{backgroundColor:'#FFF',borderRadius:18,padding:16},cardTitle:{fontSize:16,fontWeight:'900',color:'#111827'},body:{fontSize:13,lineHeight:19,color:'#6B7280',marginTop:5},button:{alignSelf:'flex-start',backgroundColor:'#111827',borderRadius:11,paddingHorizontal:14,paddingVertical:10,marginTop:10},buttonText:{color:'#FFF',fontWeight:'900'},section:{backgroundColor:'#FFF',borderRadius:20,padding:17},sectionTitle:{fontSize:16,fontWeight:'900',color:'#111827',marginBottom:8},item:{flexDirection:'row',alignItems:'flex-start',paddingVertical:12,borderBottomWidth:1,borderBottomColor:'#F3F4F6'},check:{width:28,height:28,borderRadius:14,borderWidth:2,borderColor:'#D1D5DB',alignItems:'center',justifyContent:'center'},checkText:{fontSize:12,fontWeight:'900',color:'#6B7280'},itemCopy:{marginLeft:12,flex:1},name:{fontSize:14,fontWeight:'900',color:'#111827'},meta:{fontSize:11,color:'#9CA3AF',marginTop:3},priceLink:{fontSize:11,fontWeight:'900',color:'#374151',marginTop:7},suggest:{backgroundColor:'#FFF',borderRadius:20,padding:17},chips:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:10},chip:{backgroundColor:'#F3F4F6',borderRadius:20,paddingHorizontal:10,paddingVertical:7},chipText:{fontSize:10,fontWeight:'800',color:'#4B5563'},secondary:{backgroundColor:'#FFF',borderRadius:14,padding:14},secondaryText:{textAlign:'center',fontWeight:'900',color:'#111827'},empty:{backgroundColor:'#FFF',borderRadius:20,padding:28,alignItems:'center'},emptyTitle:{fontSize:18,fontWeight:'900',color:'#111827'}});
