import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { hasAuthSession } from '../lib/api';
import { getSmartShoppingList, SmartShoppingItem } from '../lib/shopping-api';

export default function ShoppingScreen() {
  const [items, setItems] = useState<SmartShoppingItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => {
    try { setError(null); setItems(await getSmartShoppingList()); }
    catch (err) { setError(err instanceof Error ? err.message : 'Unable to build your shopping list.'); }
    finally { setLoading(false); setRefreshing(false); }
  }, []);
  useEffect(() => { void hasAuthSession().then((ok) => { if (ok) void load(); else router.replace('/'); }); }, [load]);
  const critical = useMemo(() => items.filter((item) => item.urgency === 'critical').length, [items]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" /></View>;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} />}>
    <View style={styles.nav}><Pressable onPress={() => router.back()}><Text style={styles.navText}>← Inventory</Text></Pressable><Pressable onPress={() => router.push('/smart-meals')}><Text style={styles.navText}>Smart Meals</Text></Pressable></View>
    <Text style={styles.eyebrow}>HOUSEHOLD · PERSONAL BRAIN</Text><Text style={styles.title}>Smart Basket</Text><Text style={styles.subtitle}>A shopping list generated from what is actually running low at home.</Text>
    <View style={styles.summary}><View><Text style={styles.summaryLabel}>Buy next</Text><Text style={styles.summaryValue}>{items.length}</Text></View><View><Text style={styles.summaryLabel}>Critical</Text><Text style={styles.summaryValue}>{critical}</Text></View><View><Text style={styles.summaryLabel}>Essentials</Text><Text style={styles.summaryValue}>{items.filter((item) => item.essential).length}</Text></View></View>
    {error ? <View style={styles.card}><Text style={styles.cardTitle}>Shopping list unavailable</Text><Text style={styles.body}>{error}</Text><Pressable onPress={() => void load()} style={styles.button}><Text style={styles.buttonText}>Retry</Text></Pressable></View> : null}
    {items.length ? items.map((item) => <View key={item.foodId} style={styles.card}><View style={styles.top}><View style={styles.copy}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.category}{item.essential ? ' · Essential' : ''}</Text></View><View style={[styles.badge, item.urgency === 'critical' && styles.critical, item.urgency === 'soon' && styles.soon]}><Text style={styles.badgeText}>{item.urgency}</Text></View></View><View style={styles.buyRow}><View><Text style={styles.label}>Have</Text><Text style={styles.value}>{Math.round(item.quantity * 10) / 10} {item.unit}</Text></View><View><Text style={styles.label}>Recommended</Text><Text style={styles.value}>+{Math.round(item.recommendedQuantity * 10) / 10} {item.unit}</Text></View></View><Text style={styles.reason}>{item.reason.replaceAll('_', ' ')}</Text></View>) : <View style={styles.empty}><Text style={styles.emptyTitle}>Basket is clear 🎉</Text><Text style={styles.body}>Nothing in your current inventory needs replenishing.</Text></View>}
    <View style={styles.actions}><Pressable onPress={() => router.push('/inventory')} style={styles.button}><Text style={styles.buttonText}>Manage Inventory</Text></Pressable><Pressable onPress={() => router.push('/meals')} style={styles.secondary}><Text style={styles.secondaryText}>Review Meals</Text></Pressable></View>
    <View style={styles.note}><Text style={styles.noteTitle}>Why these items?</Text><Text style={styles.body}>The assistant combines current stock, daily consumption, safety stock, essential status and reorder forecasts. It does not add an item just because it is popular.</Text></View>
  </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F8FA'},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:'#F7F8FA'},content:{padding:20,gap:14,paddingBottom:40},nav:{flexDirection:'row',justifyContent:'space-between'},navText:{fontWeight:'900',color:'#111827'},eyebrow:{fontSize:10,letterSpacing:1.5,fontWeight:'900',color:'#6B7280'},title:{fontSize:32,fontWeight:'900',color:'#111827'},subtitle:{fontSize:14,lineHeight:21,color:'#6B7280'},summary:{backgroundColor:'#111827',borderRadius:20,padding:18,flexDirection:'row',justifyContent:'space-between'},summaryLabel:{fontSize:10,color:'#9CA3AF'},summaryValue:{fontSize:22,fontWeight:'900',color:'#FFF',marginTop:4},card:{backgroundColor:'#FFF',borderRadius:20,padding:17},top:{flexDirection:'row',gap:10},copy:{flex:1},name:{fontSize:17,fontWeight:'900',color:'#111827'},meta:{fontSize:11,color:'#9CA3AF',marginTop:4},badge:{backgroundColor:'#ECFDF5',borderRadius:10,paddingHorizontal:9,paddingVertical:6,height:28},soon:{backgroundColor:'#FEF3C7'},critical:{backgroundColor:'#FEE2E2'},badgeText:{fontSize:9,fontWeight:'900',color:'#374151',textTransform:'uppercase'},buyRow:{flexDirection:'row',gap:40,marginTop:14,paddingTop:12,borderTopWidth:1,borderTopColor:'#F3F4F6'},label:{fontSize:9,color:'#9CA3AF'},value:{fontSize:14,fontWeight:'900',color:'#374151',marginTop:3},reason:{fontSize:11,color:'#6B7280',marginTop:12,textTransform:'capitalize'},body:{fontSize:13,lineHeight:19,color:'#6B7280',marginTop:5},cardTitle:{fontSize:16,fontWeight:'900',color:'#111827'},button:{backgroundColor:'#111827',borderRadius:12,paddingHorizontal:14,paddingVertical:11},buttonText:{color:'#FFF',fontWeight:'900'},secondary:{backgroundColor:'#FFF',borderRadius:12,paddingHorizontal:14,paddingVertical:11},secondaryText:{color:'#111827',fontWeight:'900'},actions:{flexDirection:'row',gap:8},empty:{backgroundColor:'#FFF',borderRadius:20,padding:28,alignItems:'center'},emptyTitle:{fontSize:18,fontWeight:'900',color:'#111827'},note:{backgroundColor:'#EEF2FF',borderRadius:16,padding:16},noteTitle:{fontWeight:'900',color:'#111827'}});
