import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { hasAuthSession } from '../lib/api';
import { getSmartShoppingList, SmartShoppingItem } from '../lib/shopping-api';
import { BasketItem, completeBasketItem, getBasket } from '../lib/shopping-basket-api';
import { normalizeProductKey } from '../lib/price-api';
import { PREMIUM } from '../lib/premium-ui';
import { PremiumGlow } from '../components/PremiumGlow';
import { PremiumResultCard } from '../components/PremiumResultCard';
import { MotionPress } from '../lib/motion-components';

export default function ShoppingPremiumScreen() {
  const [suggestions,setSuggestions]=useState<SmartShoppingItem[]>([]); const [basket,setBasket]=useState<BasketItem[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setError(null);const [s,b]=await Promise.all([getSmartShoppingList(),getBasket()]);setSuggestions(s);setBasket(b);}catch(e){setError(e instanceof Error?e.message:'Unable to load your basket.');}finally{setLoading(false);setRefreshing(false);}},[]);
  useEffect(()=>{void hasAuthSession().then(ok=>{if(ok)void load();else router.replace('/');});},[load]);
  const critical=useMemo(()=>suggestions.filter(i=>i.urgency==='critical').length,[suggestions]);
  const complete=async(id:string)=>{try{setBusy(id);await completeBasketItem(id);setBasket(items=>items.filter(i=>i.id!==id));}catch(e){setError(e instanceof Error?e.message:'Unable to update basket.');}finally{setBusy(null);}};
  if(loading)return <View style={styles.loading}><PremiumGlow size={260} opacity={0.12} accent="mint"/><ActivityIndicator color={PREMIUM.colors.primaryBright}/><Text style={styles.loadingText}>Shopping brain</Text></View>;
  return <SafeAreaView style={styles.safe}><View style={styles.bg}><PremiumGlow size={340} opacity={0.08} accent="mint"/></View><ScrollView showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load();}}/>} contentContainerStyle={styles.content}>
    <View style={styles.top}><Pressable onPress={()=>router.back()} style={styles.icon}><Ionicons name="arrow-back" size={18} color={PREMIUM.colors.inkSoft}/></Pressable><View style={styles.titleWrap}><Text style={styles.kicker}>SHOPPING BRAIN</Text><Text style={styles.title}>Basket</Text></View><Pressable onPress={()=>router.push('/assistant')} style={styles.icon}><Ionicons name="sparkles-outline" size={18} color={PREMIUM.colors.primaryBright}/></Pressable></View>
    <PremiumResultCard eyebrow="READY" title="Your next shop" accent="mint" value={`${basket.length} items · ${critical} urgent`} detail="MYPA keeps the list focused on what you actually need." actions={[{label:'Cook with what you have',icon:'restaurant-outline',onPress:()=>router.push('/recipe-match')},{label:'Ask MYPA',icon:'mic-outline',onPress:()=>router.push('/assistant')}]} />
    {error?<PremiumResultCard eyebrow="SYSTEM" title="Shopping unavailable" detail={error} accent="rose" actions={[{label:'Retry',icon:'refresh',onPress:()=>void load()}]}/>:null}
    <View style={styles.section}><Text style={styles.sectionKicker}>TO BUY</Text>{basket.length?basket.map(item=><View key={item.id} style={styles.item}><Pressable accessibilityRole="checkbox" accessibilityLabel={`Mark ${item.name} as bought`} disabled={busy===item.id} onPress={()=>void complete(item.id)} style={[styles.check,busy===item.id&&styles.checkBusy]}><Ionicons name={busy===item.id?'ellipsis-horizontal':'checkmark'} size={16} color={PREMIUM.colors.inkSoft}/></Pressable><View style={styles.itemCopy}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.quantity} {item.unit}{item.source==='recipe'?' · from recipe':''}</Text><Pressable accessibilityRole="button" onPress={()=>router.push({pathname:'/price-history',params:{productKey:normalizeProductKey(item.name),name:item.name}})}><Text style={styles.price}>Price history →</Text></Pressable></View></View>):<View style={styles.empty}><Ionicons name="checkmark-circle-outline" size={30} color={PREMIUM.colors.mint}/><Text style={styles.emptyTitle}>Basket is clear</Text><Text style={styles.emptyBody}>Nothing is waiting for you right now.</Text></View>}</View>
    {suggestions.length?<PremiumResultCard eyebrow="LOW STOCK" title="Things MYPA noticed" accent="amber" detail="Suggestions are intentionally separate from your confirmed basket."><View style={styles.chips}>{suggestions.slice(0,6).map(item=><View key={item.foodId} style={styles.chip}><Text style={styles.chipText}>{item.name}</Text></View>)}</View></PremiumResultCard>:null}
    <MotionPress onPress={()=>router.push('/inventory')} style={styles.inventory}><Text style={styles.inventoryText}>Open household inventory</Text><Ionicons name="arrow-forward" size={17} color={PREMIUM.colors.inkSoft}/></MotionPress>
  </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:PREMIUM.colors.canvas},bg:{...StyleSheet.absoluteFillObject,overflow:'hidden'},content:{padding:18,gap:15,paddingBottom:120},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:PREMIUM.colors.canvas},loadingText:{color:PREMIUM.colors.ink,fontSize:14,fontWeight:'900',marginTop:12},top:{flexDirection:'row',alignItems:'center',gap:10},icon:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:PREMIUM.colors.border,backgroundColor:'rgba(255,255,255,0.035)',alignItems:'center',justifyContent:'center'},titleWrap:{flex:1,alignItems:'center'},kicker:{color:PREMIUM.colors.muted,fontSize:8,fontWeight:'900',letterSpacing:1.4},title:{color:PREMIUM.colors.ink,fontSize:18,fontWeight:'900',marginTop:3},section:{borderRadius:24,borderWidth:1,borderColor:PREMIUM.colors.border,backgroundColor:PREMIUM.colors.surfaceGlass,padding:16},sectionKicker:{color:PREMIUM.colors.muted,fontSize:8,fontWeight:'900',letterSpacing:1.4,marginBottom:8},item:{flexDirection:'row',alignItems:'flex-start',gap:12,paddingVertical:12,borderBottomWidth:1,borderBottomColor:PREMIUM.colors.border},check:{width:30,height:30,borderRadius:15,borderWidth:1,borderColor:PREMIUM.colors.border,backgroundColor:'rgba(98,230,181,0.08)',alignItems:'center',justifyContent:'center'},checkBusy:{opacity:0.55},itemCopy:{flex:1},name:{color:PREMIUM.colors.ink,fontSize:14,fontWeight:'900'},meta:{color:PREMIUM.colors.muted,fontSize:10,marginTop:4},price:{color:PREMIUM.colors.primaryBright,fontSize:10,fontWeight:'800',marginTop:7},chips:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:12},chip:{borderRadius:999,paddingHorizontal:10,paddingVertical:7,borderWidth:1,borderColor:PREMIUM.colors.border,backgroundColor:'rgba(255,255,255,0.03)'},chipText:{color:PREMIUM.colors.inkSoft,fontSize:10,fontWeight:'800'},empty:{alignItems:'center',paddingVertical:18},emptyTitle:{color:PREMIUM.colors.ink,fontSize:17,fontWeight:'900',marginTop:8},emptyBody:{color:PREMIUM.colors.muted,fontSize:11,marginTop:4},inventory:{minHeight:50,borderRadius:22,borderWidth:1,borderColor:PREMIUM.colors.border,backgroundColor:'rgba(255,255,255,0.025)',paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},inventoryText:{color:PREMIUM.colors.inkSoft,fontSize:12,fontWeight:'900'}});
