import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { buildSmartMealSuggestions, SmartMealSuggestion } from '../lib/meal-intelligence';
import { getFoods, getNutritionSummary, hasAuthSession, NutritionSummary } from '../lib/api';
import { getInventory, InventoryItem } from '../lib/inventory-api';
import { useAppLocale } from '../lib/i18n';

const copy={
  en:{back:'Meals',inventory:'Inventory',eyebrow:'PERSONAL BRAIN · NUTRITION',title:'What should you eat next?',subtitle:'Suggestions now use your real household stock, not just the food catalog.',remaining:'Remaining today',available:'foods available at home',attention:'items need attention',attentionHint:'Open Inventory to see what should be replenished.',unavailable:'Suggestions unavailable',retry:'Retry',empty:'No complete meal from your stock yet',emptyHint:'Add more foods to Inventory. The assistant will only recommend foods that are actually available at home.',openInventory:'Open Inventory',how:'How the assistant decides',howHint:'It combines your remaining calories and protein with the foods currently in your household inventory. Low-stock forecasting stays separate so recommendations never pretend you have something you are about to run out of.',calories:'Calories',protein:'Protein',carbs:'Carbs',fat:'Fat'},
  fa:{back:'غذاها',inventory:'موجودی',eyebrow:'مغز شخصی · تغذیه',title:'بعدش چی بخوریم؟',subtitle:'پیشنهادها حالا از موجودی واقعی خانه‌ات استفاده می‌کنند، نه فقط فهرست غذا.',remaining:'باقی‌مانده امروز',available:'غذا در خانه موجود است',attention:'مورد نیازمند توجه',attentionHint:'موجودی را باز کن تا ببینی چه چیزهایی باید تهیه شوند.',unavailable:'پیشنهادها در دسترس نیستند',retry:'تلاش دوباره',empty:'هنوز وعده کاملی از موجودی تو نداریم',emptyHint:'غذاهای بیشتری به موجودی اضافه کن. دستیار فقط چیزهایی را پیشنهاد می‌دهد که واقعاً در خانه موجودند.',openInventory:'باز کردن موجودی',how:'دستیار چطور تصمیم می‌گیرد؟',howHint:'کالری و پروتئین باقی‌مانده را با غذاهای موجود در خانه ترکیب می‌کند. پیش‌بینی کمبود جداست تا چیزی که نزدیک تمام‌شدن است به‌عنوان موجود فرض نشود.',calories:'کالری',protein:'پروتئین',carbs:'کربوهیدرات',fat:'چربی'}
} as const;

export default function SmartMealsScreen(){
  const locale=useAppLocale(); const text=copy[locale]; const rtl=locale==='fa';
  const[summary,setSummary]=useState<NutritionSummary|null>(null); const[suggestions,setSuggestions]=useState<SmartMealSuggestion[]>([]); const[inventory,setInventory]=useState<InventoryItem[]>([]); const[loading,setLoading]=useState(true); const[refreshing,setRefreshing]=useState(false); const[error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setError(null);const[nutrition,foods,stock]=await Promise.all([getNutritionSummary(),getFoods(),getInventory()]);const availableIds=new Set(stock.filter(item=>item.quantity>0).map(item=>item.foodId));setSummary(nutrition);setInventory(stock);setSuggestions(buildSmartMealSuggestions(foods.filter(food=>availableIds.has(food.id)),nutrition));}catch(err){setError(err instanceof Error?err.message:(locale==='fa'?'ساخت پیشنهاد غذا ناموفق بود.':'Unable to build meal suggestions.'))}finally{setLoading(false);setRefreshing(false)}},[locale]);
  useEffect(()=>{void hasAuthSession().then(ok=>{if(ok)void load();else router.replace('/');});},[load]);
  if(loading)return <View style={styles.center}><ActivityIndicator size="large" accessibilityLabel={locale==='fa'?'در حال بارگذاری':'Loading'}/></View>;
  const lowStock=inventory.filter(item=>item.urgency==='critical'||item.urgency==='soon');
  return <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load();}}/>}>
    <View style={[styles.nav,rtl&&styles.rtl]}><Pressable onPress={()=>router.back()}><Text style={styles.navText}>{rtl?'→':'←'} {text.back}</Text></Pressable><Pressable onPress={()=>router.push('/inventory')}><Text style={styles.navText}>{text.inventory}</Text></Pressable></View>
    <Text style={[styles.eyebrow,rtl&&styles.textRtl]}>{text.eyebrow}</Text><Text style={[styles.title,rtl&&styles.textRtl]}>{text.title}</Text><Text style={[styles.subtitle,rtl&&styles.textRtl]}>{text.subtitle}</Text>
    {summary?<View style={styles.targetCard}><Text style={[styles.targetTitle,rtl&&styles.textRtl]}>{text.remaining}</Text><View style={styles.targetRow}><Target label={text.calories} value={summary.remaining.calories} unit="kcal"/><Target label={text.protein} value={summary.remaining.protein} unit="g"/></View><Text style={[styles.stockHint,rtl&&styles.textRtl]}>{inventory.filter(item=>item.quantity>0).length} {text.available}</Text></View>:null}
    {lowStock.length?<Pressable onPress={()=>router.push('/inventory')} style={[styles.alert,rtl&&styles.rtl]}><View style={styles.copyBlock}><Text style={[styles.alertTitle,rtl&&styles.textRtl]}>{lowStock.length} {text.attention}</Text><Text style={[styles.body,rtl&&styles.textRtl]}>{text.attentionHint}</Text></View><Text style={styles.alertArrow}>{rtl?'←':'→'}</Text></Pressable>:null}
    {error?<View style={styles.card}><Text style={[styles.cardTitle,rtl&&styles.textRtl]}>{text.unavailable}</Text><Text style={[styles.body,rtl&&styles.textRtl]}>{error}</Text><Pressable onPress={()=>void load()} style={styles.button}><Text style={styles.buttonText}>{text.retry}</Text></Pressable></View>:null}
    {suggestions.length?suggestions.map((suggestion,index)=><SuggestionCard key={suggestion.id} suggestion={suggestion} rank={index+1} text={text} rtl={rtl}/>):<View style={styles.card}><Text style={[styles.cardTitle,rtl&&styles.textRtl]}>{text.empty}</Text><Text style={[styles.body,rtl&&styles.textRtl]}>{text.emptyHint}</Text><Pressable onPress={()=>router.push('/inventory')} style={styles.button}><Text style={styles.buttonText}>{text.openInventory}</Text></Pressable></View>}
    <View style={styles.note}><Text style={[styles.noteTitle,rtl&&styles.textRtl]}>{text.how}</Text><Text style={[styles.body,rtl&&styles.textRtl]}>{text.howHint}</Text></View>
  </ScrollView>;
}
function Target({label,value,unit}:{label:string;value:number|null;unit:string}){return <View style={styles.target}><Text style={styles.targetLabel}>{label}</Text><Text style={styles.targetValue}>{value==null?'—':Math.max(0,Math.round(value))}{value==null?'':` ${unit}`}</Text></View>}
function SuggestionCard({suggestion,rank,text,rtl}:{suggestion:SmartMealSuggestion;rank:number;text:typeof copy.en;rtl:boolean}){return <View style={styles.card}><View style={[styles.cardTop,rtl&&styles.rtl]}><View style={styles.rank}><Text style={styles.rankText}>#{rank}</Text></View><View style={styles.copyBlock}><Text style={[styles.cardTitle,rtl&&styles.textRtl]}>{suggestion.title}</Text><Text style={[styles.body,rtl&&styles.textRtl]}>{suggestion.description}</Text></View><Text style={styles.score}>{Math.round(suggestion.score)}%</Text></View><View style={styles.macroRow}><Macro label={text.calories} value={`${Math.round(suggestion.calories)} kcal`}/><Macro label={text.protein} value={`${Math.round(suggestion.protein)}g`}/><Macro label={text.carbs} value={`${Math.round(suggestion.carbs)}g`}/><Macro label={text.fat} value={`${Math.round(suggestion.fat)}g`}/></View><Text style={[styles.foods,rtl&&styles.textRtl]}>{suggestion.foods.map(food=>food.name).join(' · ')}</Text><Text style={[styles.reason,rtl&&styles.textRtl]}>💡 {suggestion.reason}</Text></View>}
function Macro({label,value}:{label:string;value:string}){return <View><Text style={styles.macroLabel}>{label}</Text><Text style={styles.macroValue}>{value}</Text></View>}
const styles=StyleSheet.create({center:{flex:1,justifyContent:'center',alignItems:'center'},content:{padding:20,gap:14,paddingBottom:40,backgroundColor:'#F7F8FA',minHeight:'100%'},rtl:{direction:'rtl'},textRtl:{textAlign:'right'},nav:{flexDirection:'row',justifyContent:'space-between'},navText:{fontWeight:'900',color:'#111827'},eyebrow:{fontSize:10,letterSpacing:1.5,fontWeight:'900',color:'#6B7280'},title:{fontSize:30,fontWeight:'900',color:'#111827'},subtitle:{fontSize:14,lineHeight:21,color:'#6B7280'},targetCard:{backgroundColor:'#111827',borderRadius:20,padding:18},targetTitle:{color:'#FFF',fontSize:16,fontWeight:'900'},targetRow:{flexDirection:'row',gap:10,marginTop:12},target:{flex:1,backgroundColor:'#FFFFFF12',borderRadius:14,padding:12},targetLabel:{color:'#9CA3AF',fontSize:11},targetValue:{color:'#FFF',fontSize:20,fontWeight:'900',marginTop:4},stockHint:{color:'#9CA3AF',fontSize:10,marginTop:12},alert:{backgroundColor:'#FEF3C7',borderRadius:16,padding:15,flexDirection:'row',alignItems:'center'},alertArrow:{fontSize:24,fontWeight:'900',color:'#92400E'},copyBlock:{flex:1},card:{backgroundColor:'#FFF',borderRadius:20,padding:17},alertTitle:{fontSize:13,fontWeight:'900',color:'#92400E'},body:{fontSize:13,lineHeight:19,color:'#6B7280',marginTop:4},cardTop:{flexDirection:'row',gap:10,alignItems:'flex-start'},rank:{width:34,height:34,borderRadius:17,backgroundColor:'#111827',alignItems:'center',justifyContent:'center'},rankText:{color:'#FFF',fontWeight:'900',fontSize:11},cardTitle:{fontSize:16,fontWeight:'900',color:'#111827'},score:{fontSize:14,fontWeight:'900',color:'#111827'},macroRow:{flexDirection:'row',gap:15,marginTop:14,paddingTop:12,borderTopWidth:1,borderTopColor:'#F3F4F6'},macroLabel:{fontSize:9,color:'#9CA3AF'},macroValue:{fontSize:12,fontWeight:'900',color:'#374151',marginTop:2},foods:{fontSize:12,lineHeight:18,color:'#4B5563',marginTop:12},reason:{fontSize:11,lineHeight:17,color:'#6B7280',marginTop:10},button:{alignSelf:'flex-start',backgroundColor:'#111827',paddingHorizontal:14,paddingVertical:10,borderRadius:12,marginTop:12},buttonText:{color:'#FFF',fontWeight:'900'},note:{padding:16,borderRadius:16,backgroundColor:'#EEF2FF'},noteTitle:{fontSize:13,fontWeight:'900',color:'#111827'}});
