import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { buildSmartMealSuggestions, SmartMealSuggestion } from '../lib/meal-intelligence';
import { getFoods, getNutritionSummary, hasAuthSession, NutritionSummary } from '../lib/api';
import { getInventory, InventoryItem } from '../lib/inventory-api';
import { router } from 'expo-router';
import { AppLocale, getStoredLocale, isRTL } from '../lib/i18n';

const copy={en:{back:'← Meals',inventory:'Inventory',eyebrow:'PERSONAL BRAIN · NUTRITION',title:'What should you eat next?',subtitle:'Suggestions use your real household stock, not just the food catalog.',remaining:'Remaining today',homeFoods:'foods available at home',attention:'items need attention',attentionBody:'Open Inventory to see what should be replenished.',unavailable:'Suggestions unavailable',retry:'Retry',openInventory:'Open Inventory',empty:'No complete meal from your stock yet',emptyBody:'Add more foods to Inventory. The assistant will only recommend foods that are actually available at home.',how:'How the assistant decides',howBody:'It combines your remaining calories and protein with foods currently in your household inventory. Low-stock forecasting stays separate so recommendations never pretend you have something you are about to run out of.',calories:'Calories',protein:'Protein',carbs:'Carbs',fat:'Fat'},fa:{back:'وعده‌ها ←',inventory:'موجودی',eyebrow:'مغز شخصی · تغذیه',title:'بعدی چی بخورم؟',subtitle:'پیشنهادها از موجودی واقعی خانه استفاده می‌کنند، نه فقط کاتالوگ غذا.',remaining:'باقی‌مانده امروز',homeFoods:'غذا در خانه موجود است',attention:'مورد نیازمند توجه',attentionBody:'موجودی را باز کن تا چیزهایی که باید دوباره تهیه شوند ببینی.',unavailable:'پیشنهادها در دسترس نیستند',retry:'تلاش دوباره',openInventory:'باز کردن موجودی',empty:'هنوز یک وعده کامل از موجودی تو پیدا نشد',emptyBody:'غذای بیشتری به موجودی اضافه کن؛ دستیار فقط چیزهایی را پیشنهاد می‌دهد که واقعاً در خانه موجودند.',how:'دستیار چطور تصمیم می‌گیرد',howBody:'کالری و پروتئین باقی‌مانده امروز را با غذاهای موجود در خانه ترکیب می‌کند. پیش‌بینی کمبود جداست تا وانمود نکند غذایی را داری که در آستانه تمام شدن است.',calories:'کالری',protein:'پروتئین',carbs:'کربوهیدرات',fat:'چربی'}} as const;

export default function SmartMealsScreen(){
 const [locale,setLocale]=useState<AppLocale>('en');const [summary,setSummary]=useState<NutritionSummary|null>(null);const [suggestions,setSuggestions]=useState<SmartMealSuggestion[]>([]);const [inventory,setInventory]=useState<InventoryItem[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{try{setError(null);const [nutrition,foods,stock]=await Promise.all([getNutritionSummary(),getFoods(),getInventory()]);const availableIds=new Set(stock.filter(item=>item.quantity>0).map(item=>item.foodId));setSummary(nutrition);setInventory(stock);setSuggestions(buildSmartMealSuggestions(foods.filter(food=>availableIds.has(food.id)),nutrition))}catch(err){setError(err instanceof Error?err.message:'Unable to build meal suggestions.')}finally{setLoading(false);setRefreshing(false)}},[]);
 useEffect(()=>{void getStoredLocale().then(v=>setLocale(v??'en'));void hasAuthSession().then(ok=>{if(ok)void load();else router.replace('/')})},[load]);
 const text=copy[locale],rtl=isRTL(locale);if(loading)return <View style={styles.center}><ActivityIndicator size="large"/></View>;const lowStock=inventory.filter(item=>item.urgency==='critical'||item.urgency==='soon');
 return <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load()}}/>}><View style={[styles.nav,rtl&&styles.rtl]}><Pressable onPress={()=>router.back()}><Text style={styles.navText}>{text.back}</Text></Pressable><Pressable onPress={()=>router.push('/inventory')}><Text style={styles.navText}>{text.inventory}</Text></Pressable></View>
 <Text style={[styles.eyebrow,rtl&&styles.rtlText]}>{text.eyebrow}</Text><Text style={[styles.title,rtl&&styles.rtlText]}>{text.title}</Text><Text style={[styles.subtitle,rtl&&styles.rtlText]}>{text.subtitle}</Text>
 {summary?<View style={styles.targetCard}><Text style={[styles.targetTitle,rtl&&styles.rtlText]}>{text.remaining}</Text><View style={[styles.targetRow,rtl&&styles.rtl]}><Target label={text.calories} value={summary.remaining.calories} unit="kcal" rtl={rtl}/><Target label={text.protein} value={summary.remaining.protein} unit="g" rtl={rtl}/></View><Text style={[styles.stockHint,rtl&&styles.rtlText]}>{inventory.filter(item=>item.quantity>0).length} {text.homeFoods}</Text></View>:null}
 {lowStock.length?<Pressable onPress={()=>router.push('/inventory')} style={styles.alert}><Text style={[styles.alertTitle,rtl&&styles.rtlText]}>{lowStock.length} {text.attention}</Text><Text style={[styles.body,rtl&&styles.rtlText]}>{text.attentionBody}</Text></Pressable>:null}
 {error?<View style={styles.card}><Text style={[styles.cardTitle,rtl&&styles.rtlText]}>{text.unavailable}</Text><Text style={[styles.body,rtl&&styles.rtlText]}>{error}</Text><Pressable onPress={()=>void load()} style={styles.button}><Text style={styles.buttonText}>{text.retry}</Text></Pressable></View>:null}
 {suggestions.length?suggestions.map((suggestion,index)=><SuggestionCard key={suggestion.id} suggestion={suggestion} rank={index+1} rtl={rtl} text={text}/>):<View style={styles.card}><Text style={[styles.cardTitle,rtl&&styles.rtlText]}>{text.empty}</Text><Text style={[styles.body,rtl&&styles.rtlText]}>{text.emptyBody}</Text><Pressable onPress={()=>router.push('/inventory')} style={styles.button}><Text style={styles.buttonText}>{text.openInventory}</Text></Pressable></View>}
 <View style={styles.note}><Text style={[styles.noteTitle,rtl&&styles.rtlText]}>{text.how}</Text><Text style={[styles.body,rtl&&styles.rtlText]}>{text.howBody}</Text></View></ScrollView>;
}
function Target({label,value,unit,rtl}:{label:string;value:number|null;unit:string;rtl:boolean}){return <View style={styles.target}><Text style={[styles.targetLabel,rtl&&styles.rtlText]}>{label}</Text><Text style={[styles.targetValue,rtl&&styles.rtlText]}>{value==null?'—':Math.max(0,Math.round(value))}{value==null?'':` ${unit}`}</Text></View>}
function SuggestionCard({suggestion,rank,rtl,text}:{suggestion:SmartMealSuggestion;rank:number;rtl:boolean;text:typeof copy.en}){return <View style={styles.card}><View style={[styles.cardTop,rtl&&styles.rtl]}><View style={styles.rank}><Text style={styles.rankText}>#{rank}</Text></View><View style={styles.copy}><Text style={[styles.cardTitle,rtl&&styles.rtlText]}>{suggestion.title}</Text><Text style={[styles.body,rtl&&styles.rtlText]}>{suggestion.description}</Text></View><Text style={styles.score}>{Math.round(suggestion.score)}%</Text></View><View style={[styles.macroRow,rtl&&styles.rtl]}><Macro label={text.calories} value={`${Math.round(suggestion.calories)} kcal`} rtl={rtl}/><Macro label={text.protein} value={`${Math.round(suggestion.protein)}g`} rtl={rtl}/><Macro label={text.carbs} value={`${Math.round(suggestion.carbs)}g`} rtl={rtl}/><Macro label={text.fat} value={`${Math.round(suggestion.fat)}g`} rtl={rtl}/></View><Text style={[styles.foods,rtl&&styles.rtlText]}>{suggestion.foods.map(food=>food.name).join(' · ')}</Text><Text style={[styles.reason,rtl&&styles.rtlText]}>💡 {suggestion.reason}</Text></View>}
function Macro({label,value,rtl}:{label:string;value:string;rtl:boolean}){return <View><Text style={[styles.macroLabel,rtl&&styles.rtlText]}>{label}</Text><Text style={[styles.macroValue,rtl&&styles.rtlText]}>{value}</Text></View>}
const styles=StyleSheet.create({center:{flex:1,justifyContent:'center',alignItems:'center'},content:{padding:20,gap:14,paddingBottom:40,backgroundColor:'#F7F8FA',minHeight:'100%'},nav:{flexDirection:'row',justifyContent:'space-between'},rtl:{flexDirection:'row-reverse'},rtlText:{textAlign:'right',direction:'rtl'},navText:{fontWeight:'900',color:'#111827'},eyebrow:{fontSize:10,letterSpacing:1.5,fontWeight:'900',color:'#6B7280'},title:{fontSize:30,fontWeight:'900',color:'#111827'},subtitle:{fontSize:14,lineHeight:21,color:'#6B7280'},targetCard:{backgroundColor:'#111827',borderRadius:20,padding:18},targetTitle:{color:'#FFF',fontSize:16,fontWeight:'900'},targetRow:{flexDirection:'row',gap:10,marginTop:12},target:{flex:1,backgroundColor:'#FFFFFF12',borderRadius:14,padding:12},targetLabel:{color:'#9CA3AF',fontSize:11},targetValue:{color:'#FFF',fontSize:20,fontWeight:'900',marginTop:4},stockHint:{color:'#9CA3AF',fontSize:10,marginTop:12},alert:{backgroundColor:'#FEF3C7',borderRadius:16,padding:15},alertTitle:{fontSize:13,fontWeight:'900',color:'#92400E'},card:{backgroundColor:'#FFF',borderRadius:20,padding:17},cardTop:{flexDirection:'row',gap:10,alignItems:'flex-start'},rank:{width:34,height:34,borderRadius:17,backgroundColor:'#111827',alignItems:'center',justifyContent:'center'},rankText:{color:'#FFF',fontWeight:'900',fontSize:11},copy:{flex:1},cardTitle:{fontSize:16,fontWeight:'900',color:'#111827'},body:{fontSize:13,lineHeight:19,color:'#6B7280',marginTop:4},score:{fontSize:14,fontWeight:'900',color:'#111827'},macroRow:{flexDirection:'row',gap:15,marginTop:14,paddingTop:12,borderTopWidth:1,borderTopColor:'#F3F4F6'},macroLabel:{fontSize:9,color:'#9CA3AF'},macroValue:{fontSize:12,fontWeight:'900',color:'#374151',marginTop:2},foods:{fontSize:12,lineHeight:18,color:'#4B5563',marginTop:12},reason:{fontSize:11,lineHeight:17,color:'#6B7280',marginTop:10},button:{alignSelf:'flex-start',backgroundColor:'#111827',paddingHorizontal:14,paddingVertical:10,borderRadius:12,marginTop:12},buttonText:{color:'#FFF',fontWeight:'900'},note:{padding:16,borderRadius:16,backgroundColor:'#EEF2FF'},noteTitle:{fontSize:13,fontWeight:'900',color:'#111827'}});