import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { buildSmartMealSuggestions, SmartMealSuggestion } from '../lib/meal-intelligence';
import { getFoods, getNutritionSummary, hasAuthSession, NutritionSummary } from '../lib/api';

export default function SmartMealsScreen() {
  const [summary, setSummary] = useState<NutritionSummary | null>(null);
  const [suggestions, setSuggestions] = useState<SmartMealSuggestion[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setError(null); const [nutrition, foods] = await Promise.all([getNutritionSummary(), getFoods()]); setSummary(nutrition); setSuggestions(buildSmartMealSuggestions(foods, nutrition)); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to build meal suggestions.'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void hasAuthSession().then((ok) => { if (ok) void load(); else router.replace('/'); }); }, [load]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" /></View>;
  return <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} />}>
    <View style={styles.nav}><Pressable onPress={() => router.back()}><Text style={styles.navText}>← Meals</Text></Pressable><Pressable onPress={() => router.push('/meal-builder')}><Text style={styles.navText}>Log meal</Text></Pressable></View>
    <Text style={styles.eyebrow}>PERSONAL BRAIN · NUTRITION</Text><Text style={styles.title}>What should you eat next?</Text><Text style={styles.subtitle}>Suggestions are scored against what you still have left in today's calorie and protein targets.</Text>
    {summary ? <View style={styles.targetCard}><Text style={styles.targetTitle}>Remaining today</Text><View style={styles.targetRow}><Target label="Calories" value={summary.remaining.calories} unit="kcal" /><Target label="Protein" value={summary.remaining.protein} unit="g" /></View></View> : null}
    {error ? <View style={styles.card}><Text style={styles.cardTitle}>Suggestions unavailable</Text><Text style={styles.body}>{error}</Text><Pressable onPress={() => void load()} style={styles.button}><Text style={styles.buttonText}>Retry</Text></Pressable></View> : null}
    {suggestions.length ? suggestions.map((suggestion, index) => <SuggestionCard key={suggestion.id} suggestion={suggestion} rank={index + 1} />) : <View style={styles.card}><Text style={styles.cardTitle}>Not enough food data yet</Text><Text style={styles.body}>Add more foods to your catalog and the assistant will have more combinations to work with.</Text><Pressable onPress={() => router.push('/meal-builder')} style={styles.button}><Text style={styles.buttonText}>Open Meal Builder</Text></Pressable></View>}
    <View style={styles.note}><Text style={styles.noteTitle}>How the assistant decides</Text><Text style={styles.body}>It favors combinations that fit your remaining calories and protein instead of blindly recommending the most popular meal.</Text></View>
  </ScrollView>;
}
function Target({ label, value, unit }: { label: string; value: number | null; unit: string }) { return <View style={styles.target}><Text style={styles.targetLabel}>{label}</Text><Text style={styles.targetValue}>{value == null ? '—' : Math.max(0, Math.round(value))}{value == null ? '' : ` ${unit}`}</Text></View>; }
function SuggestionCard({ suggestion, rank }: { suggestion: SmartMealSuggestion; rank: number }) { return <View style={styles.card}><View style={styles.cardTop}><View style={styles.rank}><Text style={styles.rankText}>#{rank}</Text></View><View style={styles.copy}><Text style={styles.cardTitle}>{suggestion.title}</Text><Text style={styles.body}>{suggestion.description}</Text></View><Text style={styles.score}>{Math.round(suggestion.score)}%</Text></View><View style={styles.macroRow}><Macro label="Calories" value={`${Math.round(suggestion.calories)} kcal`} /><Macro label="Protein" value={`${Math.round(suggestion.protein)}g`} /><Macro label="Carbs" value={`${Math.round(suggestion.carbs)}g`} /><Macro label="Fat" value={`${Math.round(suggestion.fat)}g`} /></View><Text style={styles.foods}>{suggestion.foods.map((food) => food.name).join(' · ')}</Text><Text style={styles.reason}>💡 {suggestion.reason}</Text></View>; }
function Macro({ label, value }: { label: string; value: string }) { return <View><Text style={styles.macroLabel}>{label}</Text><Text style={styles.macroValue}>{value}</Text></View>; }
const styles=StyleSheet.create({center:{flex:1,justifyContent:'center',alignItems:'center'},content:{padding:20,gap:14,paddingBottom:40,backgroundColor:'#F7F8FA',minHeight:'100%'},nav:{flexDirection:'row',justifyContent:'space-between'},navText:{fontWeight:'900',color:'#111827'},eyebrow:{fontSize:10,letterSpacing:1.5,fontWeight:'900',color:'#6B7280'},title:{fontSize:30,fontWeight:'900',color:'#111827'},subtitle:{fontSize:14,lineHeight:21,color:'#6B7280'},targetCard:{backgroundColor:'#111827',borderRadius:20,padding:18},targetTitle:{color:'#FFF',fontSize:16,fontWeight:'900'},targetRow:{flexDirection:'row',gap:10,marginTop:12},target:{flex:1,backgroundColor:'#FFFFFF12',borderRadius:14,padding:12},targetLabel:{color:'#9CA3AF',fontSize:11},targetValue:{color:'#FFF',fontSize:20,fontWeight:'900',marginTop:4},card:{backgroundColor:'#FFF',borderRadius:20,padding:17},cardTop:{flexDirection:'row',gap:10,alignItems:'flex-start'},rank:{width:34,height:34,borderRadius:17,backgroundColor:'#111827',alignItems:'center',justifyContent:'center'},rankText:{color:'#FFF',fontWeight:'900',fontSize:11},copy:{flex:1},cardTitle:{fontSize:16,fontWeight:'900',color:'#111827'},body:{fontSize:13,lineHeight:19,color:'#6B7280',marginTop:4},score:{fontSize:14,fontWeight:'900',color:'#111827'},macroRow:{flexDirection:'row',gap:15,marginTop:14,paddingTop:12,borderTopWidth:1,borderTopColor:'#F3F4F6'},macroLabel:{fontSize:9,color:'#9CA3AF'},macroValue:{fontSize:12,fontWeight:'900',color:'#374151',marginTop:2},foods:{fontSize:12,lineHeight:18,color:'#4B5563',marginTop:12},reason:{fontSize:11,lineHeight:17,color:'#6B7280',marginTop:10},button:{alignSelf:'flex-start',backgroundColor:'#111827',paddingHorizontal:14,paddingVertical:10,borderRadius:12,marginTop:12},buttonText:{color:'#FFF',fontWeight:'900'},note:{padding:16,borderRadius:16,backgroundColor:'#EEF2FF'},noteTitle:{fontSize:13,fontWeight:'900',color:'#111827'}});