import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Link } from 'expo-router';
import { Supplement, SupplementStatus, createSupplement, deleteSupplement, getSupplementStatus, hasAuthSession, takeSupplement } from '../lib/api';
import { AppLocale, getStoredLocale, isRTL } from '../lib/i18n';

const copy={en:{home:'← Home',eyebrow:'HEALTH ROUTINE',title:'Supplements',taken:'taken today',complete:'complete',add:'Add a supplement',name:'Name (e.g. Vitamin D)',dosage:'Dosage (optional)',addBtn:'Add supplement',noDosage:'No dosage',take:'Take',takenBtn:'Taken ✓',delete:'Delete',empty:'Your routine is empty',emptyBody:'Add the supplements you want your assistant to track.'},fa:{home:'خانه ←',eyebrow:'روتین سلامتی',title:'مکمل‌ها',taken:'امروز مصرف شده',complete:'تکمیل',add:'افزودن مکمل',name:'نام (مثلاً ویتامین D)',dosage:'مقدار مصرف (اختیاری)',addBtn:'افزودن مکمل',noDosage:'مقداری ثبت نشده',take:'مصرف',takenBtn:'مصرف شد ✓',delete:'حذف',empty:'روتین تو خالی است',emptyBody:'مکمل‌هایی را که می‌خواهی دستیار پیگیری کند اضافه کن.'}} as const;

export default function SupplementsScreen(){
 const [locale,setLocale]=useState<AppLocale>('en');const [status,setStatus]=useState<SupplementStatus|null>(null);const [name,setName]=useState('');const [dosage,setDosage]=useState('');const [time,setTime]=useState('09:00');const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{try{setError(null);setStatus(await getSupplementStatus())}catch(e){setError(e instanceof Error?e.message:'Unable to load supplements')}finally{setLoading(false);setRefreshing(false)}},[]);
 useEffect(()=>{void getStoredLocale().then(v=>setLocale(v??'en'));void hasAuthSession().then(ok=>{if(ok)void load();else setLoading(false)})},[load]);
 async function addSupplement(){if(!name.trim())return;try{await createSupplement({name:name.trim(),dosage:dosage.trim()||undefined,scheduledTime:time});setName('');setDosage('');setTime('09:00');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to add supplement')}}
 async function take(item:Supplement){try{await takeSupplement(item.id);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update supplement')}}
 async function remove(item:Supplement){try{await deleteSupplement(item.id);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete supplement')}}
 const text=copy[locale],rtl=isRTL(locale);if(loading)return <View style={styles.center}><ActivityIndicator size="large"/></View>;
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load()}}/>}>
   <View style={[styles.nav,rtl&&styles.rtl]}><Link href="/" asChild><Pressable><Text style={styles.back}>{text.home}</Text></Pressable></Link></View>
   <Text style={[styles.eyebrow,rtl&&styles.rtlText]}>{text.eyebrow}</Text><Text style={[styles.title,rtl&&styles.rtlText]}>{text.title}</Text><Text style={[styles.subtitle,rtl&&styles.rtlText]}>{status?.taken??0} {text.taken} · {status?.completionPercent??0}% {text.complete}</Text>
   <View style={styles.card}><Text style={[styles.cardTitle,rtl&&styles.rtlText]}>{text.add}</Text><TextInput value={name} onChangeText={setName} placeholder={text.name} placeholderTextColor="#9CA3AF" style={[styles.input,rtl&&styles.rtlText]}/><TextInput value={dosage} onChangeText={setDosage} placeholder={text.dosage} placeholderTextColor="#9CA3AF" style={[styles.input,rtl&&styles.rtlText]}/><TextInput value={time} onChangeText={setTime} placeholder="09:00" placeholderTextColor="#9CA3AF" style={[styles.input,rtl&&styles.rtlText]}/><Pressable style={styles.primary} onPress={()=>void addSupplement()}><Text style={styles.primaryText}>{text.addBtn}</Text></Pressable></View>
   {error?<View style={styles.error}><Text style={styles.errorText}>{error}</Text></View>:null}
   {status?.supplements.map(item=>{const taken=Boolean(item.logs?.length);return <View key={item.id} style={styles.card}><View style={[styles.row,rtl&&styles.rtl]}><View style={styles.copy}><Text style={[styles.cardTitle,rtl&&styles.rtlText]}>{item.name}</Text><Text style={[styles.muted,rtl&&styles.rtlText]}>{item.dosage??text.noDosage} · {item.scheduledTime} · {item.frequency}</Text></View><Pressable style={taken?styles.done:styles.take} onPress={()=>void take(item)} disabled={taken}><Text style={taken?styles.doneText:styles.takeText}>{taken?text.takenBtn:text.take}</Text></Pressable></View><Pressable onPress={()=>void remove(item)}><Text style={[styles.delete,rtl&&styles.rtlText]}>{text.delete}</Text></Pressable></View>})}
   {status?.supplements.length===0?<View style={styles.card}><Text style={[styles.cardTitle,rtl&&styles.rtlText]}>{text.empty}</Text><Text style={[styles.muted,rtl&&styles.rtlText]}>{text.emptyBody}</Text></View>:null}
 </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F8FA'},content:{padding:20,gap:14,paddingBottom:36},center:{flex:1,justifyContent:'center',alignItems:'center'},nav:{height:26},rtl:{flexDirection:'row-reverse'},rtlText:{textAlign:'right',direction:'rtl'},back:{fontWeight:'800',color:'#374151',paddingVertical:8},eyebrow:{fontSize:11,fontWeight:'800',letterSpacing:1.5,color:'#6B7280',marginTop:6},title:{fontSize:32,fontWeight:'900',color:'#111827'},subtitle:{fontSize:14,color:'#6B7280',marginBottom:4},card:{backgroundColor:'#FFF',borderRadius:20,padding:18,gap:10},cardTitle:{fontSize:17,fontWeight:'800',color:'#111827'},muted:{fontSize:12,color:'#6B7280',lineHeight:18},input:{borderWidth:1,borderColor:'#E5E7EB',borderRadius:12,padding:12,color:'#111827'},primary:{backgroundColor:'#111827',borderRadius:12,padding:13,alignItems:'center'},primaryText:{color:'#FFF',fontWeight:'800'},row:{flexDirection:'row',alignItems:'center',gap:12},copy:{flex:1},take:{backgroundColor:'#111827',paddingHorizontal:13,paddingVertical:10,borderRadius:11},takeText:{color:'#FFF',fontWeight:'800'},done:{backgroundColor:'#E5E7EB',paddingHorizontal:13,paddingVertical:10,borderRadius:11},doneText:{color:'#374151',fontWeight:'800'},delete:{fontSize:11,color:'#9CA3AF',fontWeight:'700'},error:{backgroundColor:'#FEF2F2',borderRadius:14,padding:12},errorText:{color:'#991B1B',fontSize:12,fontWeight:'700'}});