import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Supplement, SupplementStatus, createSupplement, deleteSupplement, getSupplementStatus, hasAuthSession, takeSupplement } from '../lib/api';
import { PREMIUM } from '../lib/premium-ui';
import { PremiumGlow } from '../components/PremiumGlow';
import { PremiumResultCard } from '../components/PremiumResultCard';
import { MotionPress } from '../lib/motion-components';

export default function SupplementsPremiumScreen() {
  const [status, setStatus] = useState<SupplementStatus | null>(null);
  const [name, setName] = useState(''); const [dosage, setDosage] = useState(''); const [time, setTime] = useState('09:00');
  const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setError(null); setStatus(await getSupplementStatus()); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load supplements.'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void hasAuthSession().then((ok) => { if (ok) void load(); else router.replace('/'); }); }, [load]);
  const add = async () => { if (!name.trim()) return; try { setBusy('add'); await createSupplement({ name: name.trim(), dosage: dosage.trim() || undefined, scheduledTime: time }); setName(''); setDosage(''); setTime('09:00'); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to add supplement.'); } finally { setBusy(null); } };
  const take = async (item: Supplement) => { try { setBusy(item.id); await takeSupplement(item.id); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to update supplement.'); } finally { setBusy(null); } };
  const remove = async (item: Supplement) => { try { setBusy(item.id); await deleteSupplement(item.id); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to delete supplement.'); } finally { setBusy(null); } };
  if (loading) return <View style={styles.loading}><PremiumGlow size={250} opacity={0.12} accent="mint"/><ActivityIndicator size="large" color={PREMIUM.colors.primaryBright}/><Text style={styles.loadingText}>Health routine</Text></View>;
  return <SafeAreaView style={styles.safe}><View pointerEvents="none" style={styles.glow}><PremiumGlow size={320} opacity={0.08} accent="mint"/></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} />}>
    <View style={styles.top}><Pressable onPress={() => router.back()} style={styles.icon}><Ionicons name="arrow-back" size={18} color={PREMIUM.colors.inkSoft}/></Pressable><View style={styles.centerTitle}><Text style={styles.kicker}>HEALTH ROUTINE</Text><Text style={styles.title}>Supplements</Text></View><Pressable onPress={() => router.push('/assistant')} style={styles.icon}><Ionicons name="sparkles-outline" size={18} color={PREMIUM.colors.primaryBright}/></Pressable></View>
    <PremiumResultCard eyebrow="TODAY" title="Your routine" accent="mint" value={`${status?.taken ?? 0}/${status?.total ?? 0} taken`} detail={`${status?.completionPercent ?? 0}% complete`} />
    {error ? <PremiumResultCard eyebrow="SYSTEM" title="Something needs attention" accent="rose" detail={error} actions={[{ label: 'Retry', icon: 'refresh', onPress: () => void load() }]} /> : null}
    <View style={styles.form}><Text style={styles.section}>Add to your routine</Text><TextInput value={name} onChangeText={setName} placeholder="Name · Vitamin D, magnesium…" placeholderTextColor={PREMIUM.colors.muted} style={styles.input}/><View style={styles.row}><TextInput value={dosage} onChangeText={setDosage} placeholder="Dosage" placeholderTextColor={PREMIUM.colors.muted} style={[styles.input, styles.half]}/><TextInput value={time} onChangeText={setTime} placeholder="09:00" placeholderTextColor={PREMIUM.colors.muted} style={[styles.input, styles.half]}/></View><MotionPress disabled={busy==='add'} onPress={() => void add()} style={styles.primary}><Text style={styles.primaryText}>{busy==='add' ? 'Adding…' : 'Add supplement'}</Text></MotionPress></View>
    <Text style={styles.section}>Your routine</Text>
    {status?.supplements?.map((item) => { const taken = Boolean(item.logs?.length); return <View key={item.id} style={styles.card}><View style={styles.cardTop}><View style={styles.cardCopy}><View style={styles.nameRow}><View style={[styles.dot, { backgroundColor: taken ? PREMIUM.colors.mint : PREMIUM.colors.primaryBright }]} /><Text style={styles.name}>{item.name}</Text></View><Text style={styles.meta}>{item.dosage ?? 'No dosage'} · {item.scheduledTime} · {item.frequency}</Text></View><MotionPress disabled={taken || busy===item.id} onPress={() => void take(item)} style={[styles.take, taken && styles.taken]}><Ionicons name={taken ? 'checkmark' : 'add'} size={15} color={taken ? PREMIUM.colors.mint : PREMIUM.colors.ink}/><Text style={[styles.takeText, taken && styles.takenText]}>{taken ? 'Taken' : 'Take'}</Text></MotionPress></View><MotionPress disabled={busy===item.id} onPress={() => void remove(item)}><Text style={styles.delete}>Remove from routine</Text></MotionPress></View>; })}
    {status?.supplements?.length===0 ? <View style={styles.empty}><View style={styles.emptyIcon}><Ionicons name="medkit-outline" size={22} color={PREMIUM.colors.primaryBright}/></View><Text style={styles.emptyTitle}>Your routine is empty</Text><Text style={styles.emptyText}>Add the supplements you want MYPA to remember and track.</Text></View> : null}
  </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:PREMIUM.colors.canvas},glow:{...StyleSheet.absoluteFillObject,overflow:'hidden'},loading:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:PREMIUM.colors.canvas},loadingText:{color:PREMIUM.colors.ink,fontWeight:'900',marginTop:12},content:{padding:18,gap:14,paddingBottom:120},top:{flexDirection:'row',alignItems:'center',gap:10},icon:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:PREMIUM.colors.border,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(255,255,255,.035)'},centerTitle:{flex:1,alignItems:'center'},kicker:{color:PREMIUM.colors.muted,fontSize:8,fontWeight:'900',letterSpacing:1.5},title:{color:PREMIUM.colors.ink,fontSize:18,fontWeight:'900',marginTop:3},section:{color:PREMIUM.colors.ink,fontSize:13,fontWeight:'900',letterSpacing:.3},form:{borderRadius:24,borderWidth:1,borderColor:PREMIUM.colors.border,backgroundColor:PREMIUM.colors.surfaceGlass,padding:16,gap:10},input:{minHeight:48,borderRadius:16,borderWidth:1,borderColor:PREMIUM.colors.border,backgroundColor:'rgba(255,255,255,.025)',color:PREMIUM.colors.ink,paddingHorizontal:14,fontSize:12},row:{flexDirection:'row',gap:8},half:{flex:1},primary:{minHeight:48,borderRadius:18,backgroundColor:PREMIUM.colors.primaryBright,alignItems:'center',justifyContent:'center'},primaryText:{color:PREMIUM.colors.ink,fontSize:12,fontWeight:'900'},card:{borderRadius:22,borderWidth:1,borderColor:PREMIUM.colors.border,backgroundColor:PREMIUM.colors.surfaceGlass,padding:16,gap:12},cardTop:{flexDirection:'row',alignItems:'center',gap:10},cardCopy:{flex:1},nameRow:{flexDirection:'row',alignItems:'center',gap:8},dot:{width:8,height:8,borderRadius:4},name:{color:PREMIUM.colors.ink,fontSize:14,fontWeight:'900'},meta:{color:PREMIUM.colors.muted,fontSize:10,marginTop:5},take:{minHeight:42,paddingHorizontal:12,borderRadius:21,backgroundColor:PREMIUM.colors.primaryBright,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:5},takeText:{color:PREMIUM.colors.ink,fontWeight:'900',fontSize:11},taken:{backgroundColor:'rgba(79,229,168,.11)',borderWidth:1,borderColor:'rgba(79,229,168,.3)'},takenText:{color:PREMIUM.colors.mint},delete:{color:PREMIUM.colors.muted,fontSize:10,fontWeight:'800'},empty:{alignItems:'center',borderRadius:24,borderWidth:1,borderColor:PREMIUM.colors.border,backgroundColor:PREMIUM.colors.surfaceGlass,padding:28},emptyIcon:{width:46,height:46,borderRadius:23,backgroundColor:'rgba(79,229,168,.12)',alignItems:'center',justifyContent:'center'},emptyTitle:{color:PREMIUM.colors.ink,fontSize:18,fontWeight:'900',marginTop:12},emptyText:{color:PREMIUM.colors.muted,fontSize:12,lineHeight:18,textAlign:'center',marginTop:6,maxWidth:290}});
