import { Injectable } from '@nestjs/common';
import { YogaFocus, YogaLevel, YogaPose } from '../models/yoga.model';

@Injectable()
export class YogaLibraryService {
  private readonly poses: YogaPose[] = [
    {
      id: 'mountain',
      name: 'Mountain Pose',
      aliases: ['Tadasana'],
      kind: 'standing',
      levels: ['beginner', 'foundation', 'intermediate'],
      focuses: ['balance', 'strength', 'breathing'],
      defaultHoldSec: 30,
      minHoldSec: 15,
      maxHoldSec: 60,
      difficulty: 1,
      safetyLevel: 'low',
      breathing: 'slow nasal breathing',
      cues: [
        {
          id: 'mountain-entry',
          phase: 'enter',
          text: 'Stand tall, soften your shoulders, and feel both feet grounded.',
          priority: 1,
        },
        {
          id: 'mountain-hold',
          phase: 'hold',
          text: 'Breathe slowly and keep your gaze relaxed.',
          priority: 1,
        },
        {
          id: 'mountain-exit',
          phase: 'exit',
          text: 'Stay tall as you transition.',
          priority: 1,
        },
      ],
      contraindications: [],
      transitionsTo: ['upward_salute', 'forward_fold'],
    },
    {
      id: 'upward_salute',
      name: 'Upward Salute',
      aliases: ['Urdhva Hastasana'],
      kind: 'standing',
      levels: ['beginner', 'foundation', 'intermediate'],
      focuses: ['mobility', 'breathing'],
      defaultHoldSec: 20,
      minHoldSec: 10,
      maxHoldSec: 45,
      difficulty: 1.2,
      safetyLevel: 'low',
      breathing: 'inhale to lengthen',
      cues: [
        {
          id: 'salute-entry',
          phase: 'enter',
          text: 'Inhale and slowly sweep your arms overhead.',
          priority: 1,
        },
        {
          id: 'salute-hold',
          phase: 'hold',
          text: 'Keep your ribs soft and reach without straining.',
          priority: 1,
        },
        {
          id: 'salute-exit',
          phase: 'exit',
          text: 'Exhale and lower your arms with control.',
          priority: 1,
        },
      ],
      contraindications: [],
      transitionsTo: ['forward_fold', 'mountain'],
    },
    {
      id: 'forward_fold',
      name: 'Standing Forward Fold',
      aliases: ['Uttanasana'],
      kind: 'standing',
      levels: ['beginner', 'foundation', 'intermediate', 'advanced'],
      focuses: ['flexibility', 'recovery'],
      defaultHoldSec: 35,
      minHoldSec: 15,
      maxHoldSec: 75,
      difficulty: 1.8,
      safetyLevel: 'moderate',
      breathing: 'slow exhale into the fold',
      cues: [
        {
          id: 'fold-entry',
          phase: 'enter',
          text: 'Bend your knees as much as you need and fold slowly.',
          priority: 1,
        },
        {
          id: 'fold-hold',
          phase: 'hold',
          text: 'Let your neck relax and breathe into the back of your body.',
          priority: 1,
        },
        {
          id: 'fold-exit',
          phase: 'exit',
          text: 'Press through your feet and rise slowly.',
          priority: 1,
        },
      ],
      contraindications: ['acute low-back pain'],
      transitionsTo: ['half_lift', 'mountain'],
    },
    {
      id: 'downward_dog',
      name: 'Downward-Facing Dog',
      aliases: ['Adho Mukha Svanasana', 'Down Dog'],
      kind: 'transition',
      levels: ['foundation', 'intermediate', 'advanced', 'expert'],
      focuses: ['mobility', 'flexibility', 'strength'],
      defaultHoldSec: 40,
      minHoldSec: 20,
      maxHoldSec: 90,
      difficulty: 2.5,
      safetyLevel: 'moderate',
      breathing: 'steady nasal breathing',
      cues: [
        {
          id: 'down-entry',
          phase: 'enter',
          text: 'Press the floor away and lengthen your spine.',
          priority: 1,
        },
        {
          id: 'down-hold',
          phase: 'hold',
          text: 'Keep a soft bend in your knees if your hamstrings feel tight.',
          priority: 1,
        },
        {
          id: 'down-exit',
          phase: 'exit',
          text: 'Move forward slowly and keep your shoulders controlled.',
          priority: 1,
        },
      ],
      contraindications: ['acute wrist pain', 'acute shoulder pain'],
      transitionsTo: ['plank', 'low_lunge', 'childs_pose'],
    },
    {
      id: 'plank',
      name: 'Plank Pose',
      aliases: [],
      kind: 'transition',
      levels: ['foundation', 'intermediate', 'advanced', 'expert'],
      focuses: ['strength'],
      defaultHoldSec: 25,
      minHoldSec: 10,
      maxHoldSec: 60,
      difficulty: 3.2,
      safetyLevel: 'moderate',
      breathing: 'short steady breaths',
      cues: [
        {
          id: 'plank-entry',
          phase: 'enter',
          text: 'Stack shoulders over wrists and make one long line.',
          priority: 1,
        },
        {
          id: 'plank-hold',
          phase: 'hold',
          text: 'Brace gently through your center and keep breathing.',
          priority: 1,
        },
        {
          id: 'plank-exit',
          phase: 'exit',
          text: 'Lower your knees first if you need to.',
          priority: 1,
        },
      ],
      contraindications: ['acute wrist pain', 'severe shoulder pain'],
      transitionsTo: ['low_lunge', 'childs_pose'],
    },
    {
      id: 'low_lunge',
      name: 'Low Lunge',
      aliases: ['Anjaneyasana'],
      kind: 'standing',
      levels: ['foundation', 'intermediate', 'advanced'],
      focuses: ['mobility', 'flexibility', 'balance'],
      defaultHoldSec: 35,
      minHoldSec: 15,
      maxHoldSec: 75,
      difficulty: 2.4,
      safetyLevel: 'moderate',
      breathing: 'slow expansive breathing',
      cues: [
        {
          id: 'lunge-entry',
          phase: 'enter',
          text: 'Step one foot forward and lower the back knee gently.',
          priority: 1,
        },
        {
          id: 'lunge-hold',
          phase: 'hold',
          text: 'Keep your front knee tracking toward your toes.',
          priority: 1,
        },
        {
          id: 'lunge-exit',
          phase: 'exit',
          text: 'Shift your weight back slowly before changing sides.',
          priority: 1,
        },
      ],
      contraindications: ['acute knee pain'],
      transitionsTo: ['warrior_two', 'downward_dog'],
    },
    {
      id: 'warrior_two',
      name: 'Warrior II',
      aliases: ['Virabhadrasana II'],
      kind: 'standing',
      levels: ['foundation', 'intermediate', 'advanced', 'expert'],
      focuses: ['strength', 'balance', 'mobility'],
      defaultHoldSec: 40,
      minHoldSec: 20,
      maxHoldSec: 90,
      difficulty: 3,
      safetyLevel: 'moderate',
      breathing: 'steady rhythmic breathing',
      cues: [
        {
          id: 'warrior-entry',
          phase: 'enter',
          text: 'Open your arms wide and bend the front knee slowly.',
          priority: 1,
        },
        {
          id: 'warrior-hold',
          phase: 'hold',
          text: 'Keep the front knee tracking over the middle toes.',
          priority: 1,
        },
        {
          id: 'warrior-exit',
          phase: 'exit',
          text: 'Straighten the front leg before switching sides.',
          priority: 1,
        },
      ],
      contraindications: ['acute knee pain', 'uncontrolled dizziness'],
      transitionsTo: ['reverse_warrior', 'side_angle'],
    },
    {
      id: 'childs_pose',
      name: "Child's Pose",
      aliases: ['Balasana'],
      kind: 'relaxation',
      levels: ['beginner', 'foundation', 'intermediate', 'advanced'],
      focuses: ['recovery', 'relaxation', 'stress_relief'],
      defaultHoldSec: 45,
      minHoldSec: 20,
      maxHoldSec: 120,
      difficulty: 0.8,
      safetyLevel: 'low',
      breathing: 'slow long exhales',
      cues: [
        {
          id: 'child-entry',
          phase: 'enter',
          text: 'Let your hips move toward your heels and soften your jaw.',
          priority: 1,
        },
        {
          id: 'child-hold',
          phase: 'hold',
          text: 'Breathe slowly and allow your whole body to settle.',
          priority: 1,
        },
        {
          id: 'child-exit',
          phase: 'exit',
          text: 'Come up gradually and pause before standing.',
          priority: 1,
        },
      ],
      contraindications: [],
      transitionsTo: ['seated_breath', 'downward_dog'],
    },
    {
      id: 'seated_breath',
      name: 'Seated Breath',
      aliases: [],
      kind: 'breathing',
      levels: ['beginner', 'foundation', 'intermediate', 'advanced', 'expert'],
      focuses: ['breathing', 'relaxation', 'stress_relief'],
      defaultHoldSec: 90,
      minHoldSec: 45,
      maxHoldSec: 300,
      difficulty: 0.5,
      safetyLevel: 'low',
      breathing: 'inhale 4, exhale 6',
      cues: [
        {
          id: 'breath-entry',
          phase: 'enter',
          text: 'Sit comfortably and lengthen through the crown of your head.',
          priority: 1,
        },
        {
          id: 'breath-hold',
          phase: 'hold',
          text: 'Inhale gently for four and exhale slowly for six.',
          priority: 1,
        },
        {
          id: 'breath-exit',
          phase: 'exit',
          text: 'Return to natural breathing before moving.',
          priority: 1,
        },
      ],
      contraindications: [],
      transitionsTo: ['mountain'],
    },
    {
      id: 'corpse',
      name: 'Final Relaxation',
      aliases: ['Savasana'],
      kind: 'relaxation',
      levels: ['beginner', 'foundation', 'intermediate', 'advanced', 'expert'],
      focuses: ['recovery', 'relaxation', 'stress_relief'],
      defaultHoldSec: 180,
      minHoldSec: 60,
      maxHoldSec: 600,
      difficulty: 0.3,
      safetyLevel: 'low',
      breathing: 'natural breathing',
      cues: [
        {
          id: 'corpse-entry',
          phase: 'enter',
          text: 'Lie down comfortably and let your arms and legs relax.',
          priority: 1,
        },
        {
          id: 'corpse-hold',
          phase: 'hold',
          text: 'There is nothing to fix now. Let your breath move naturally.',
          priority: 1,
        },
        {
          id: 'corpse-exit',
          phase: 'exit',
          text: 'Roll to one side and sit up slowly when you are ready.',
          priority: 1,
        },
      ],
      contraindications: [],
      transitionsTo: [],
    },
  ];

  list(level?: YogaLevel, focus?: YogaFocus): YogaPose[] {
    return this.poses.filter(
      (pose) =>
        (!level || pose.levels.includes(level)) &&
        (!focus || pose.focuses.includes(focus)),
    );
  }

  get(id: string): YogaPose | null {
    return this.poses.find((pose) => pose.id === id) ?? null;
  }

  count(): number {
    return this.poses.length;
  }
}
