packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/engines': true
  argon2: true
  prisma: true
  sharp: true
  unrs-resolver: true

overrides:
  '@types/react': 19.0.10
  '@types/react-dom': 19.0.3
