-- Intentionally empty compatibility migration.
--
-- This migration originally duplicated the LifeTask/LifeTaskDependency/LifeTaskEvent
-- creation from the preceding 20260812130000_add_life_execution migration.
-- Keeping the migration id but making it a no-op preserves migration history while
-- allowing fresh databases and previously failed databases to converge safely.
