-- Intentionally empty compatibility migration.
--
-- The resource reference columns are now created with ConversationTurn in the
-- later 20260812193000_add_conversation_turns migration. Keeping this migration
-- id as a no-op preserves migration history and avoids a forward dependency on
-- a table that did not exist yet when this migration originally ran.
