import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { useAppLocale } from '../../lib/i18n';
import { completeFitnessProgramSession, getFitnessProgram, FitnessProgramDetail, startFitnessProgram } from '../../lib/fitness-content-api';
import { BRAND } from '../../lib/branding';
import { localizedCopy } from '../../lib/localized-copy';
import { FitnessLocalizedText } from '../../components/fitness-localized-text';

export default function FitnessProgramDetailScreen() {
  const { locale, rtl }=useAppLocale(); const p=useLocalSearchParams<{id:string}>(); const id=Array.isArray(p.id)?p.id[0]:p.id;
  const [program,setProgram]=useState<FitnessProgramDetail|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const text=localizedCopy({en:{back:'Back',loading:'Loading…',start:'Start program',started:'Program active',week:'Week',session:'Session',complete:'Complete ✓',done:'This program is complete',weeks:'Weeks',perWeek:'/Week',min:'Min',programWeeks:'Program weeks',retry:'Try again',active:'Active',paused:'Paused',completed:'Completed',cancelled:'Cancelled',minutes:'min',secondsRest:'s rest',error:'Unable to load this program.',unavailable:'Program unavailable'},fa:{back:'برگشت',loading:'در حال بارگذاری…',start:'شروع برنامه',started:'برنامه فعال است',active:'فعال',paused:'متوقف',completed:'کامل‌شده',cancelled:'لغوشده',week:'هفته',session:'جلسه',complete:'انجام شد ✓',done:'این برنامه کامل شده است',weeks:'هفته',perWeek:'/هفته',min:'دقیقه',minutes:'دقیقه',secondsRest:'ثانیه استراحت',programWeeks:'هفته‌های برنامه',retry:'تلاش دوباره',error:'بارگذاری این برنامه انجام نشد.',unavailable:'برنامه در دسترس نیست'}})[locale];
  const load=async()=>{if(!id)return;setLoading(true);try{setError(null);setProgram(await getFitnessProgram(id));}catch(err){setError(err instanceof Error?err.message:text.error);}finally{setLoading(false);}};
  useEffect(()=>{void load();},[id]);
  if(loading)return <View style={styles.center}><ActivityIndicator size="large" color={BRAND.colors.primaryStrong}/><Text style={styles.loading}>{text.loading}</Text></View>;
  if(error||!program)return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={styles.errorTitle}>{text.unavailable}</Text><Text style={styles.errorBody}>{error??text.unavailable}</Text><Pressable onPress={()=>void load()} style={styles.primary}><Text style={styles.primaryText}>{text.retry}</Text></Pressable></View></SafeAreaView>;
  const assignment=program.assignment; const statusLabel=assignment?.status==='active'?text.active:assignment?.status==='paused'?text.paused:assignment?.status==='completed'?text.completed:assignment?.status==='cancelled'?text.cancelled:(assignment?.status??''); const current=assignment?program.sessions.find(s=>s.weekNumber===assignment.currentWeek&&s.dayNumber===assignment.currentDay):null;
  const start=async()=>{setBusy(true);try{setError(null);setProgram(await startFitnessProgram(program.id));}catch(err){setError(err instanceof Error?err.message:text.error);}finally{setBusy(false);}};
  const complete=async()=>{if(!assignment||!current)return;setBusy(true);try{setError(null);setProgram(await completeFitnessProgramSession(program.id,current.weekNumber,current.dayNumber));}catch(err){setError(err instanceof Error?err.message:text.error);}finally{setBusy(false);}};
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}>
    <Pressable onPress={()=>router.back()}><Text style={styles.back}>{rtl?'→':'←'} {text.back}</Text></Pressable>
    <View style={styles.hero}><View style={styles.badge}><FitnessLocalizedText en={program.discipline} locale={locale} style={styles.badgeText} /></View><FitnessLocalizedText en={program.name} fa={program.nameFa} locale={locale} style={{...styles.title, ...(rtl ? styles.rtl : {})}} /><FitnessLocalizedText en={program.description} locale={locale} style={{...styles.description, ...(rtl ? styles.rtl : {})}} /><View style={styles.stats}><Stat label={text.weeks} value={String(program.durationWeeks)}/><Stat label={text.perWeek} value={String(program.sessionsPerWeek)}/><Stat label={text.min} value={`${program.sessionDurationMin} ${text.minutes}`}/></View></View>
    {!assignment?<Pressable disabled={busy} onPress={start} style={styles.primary}><Text style={styles.primaryText}>{busy?'…':text.start}</Text></Pressable>:<View style={styles.current}><Text style={[styles.currentLabel,rtl&&styles.rtl]}>{statusLabel || text.started}</Text><Text style={[styles.currentTitle,rtl&&styles.rtl]}>{text.week} {assignment.currentWeek} · {text.session} {assignment.currentDay}</Text>{current?<><FitnessLocalizedText en={`${current.title} · ${current.focus}`} locale={locale} style={{...styles.currentFocus, ...(rtl ? styles.rtl : {})}} /><View style={styles.exerciseList}>{current.sessionPayload.prescription?.map((e,i)=><View key={`${e.exerciseKey}-${i}`} style={[styles.exercise,rtl&&styles.rowReverse]}><View style={styles.exerciseCopy}><FitnessLocalizedText en={e.exerciseKey.replaceAll('-',' ')} locale={locale} style={{...styles.exerciseName, ...(rtl ? styles.rtl : {})}} /><Text style={[styles.exerciseMeta,rtl&&styles.rtl]}>{e.sets} × {e.reps} · {e.restSec}{text.secondsRest}</Text></View><Text style={styles.index}>{i+1}</Text></View>)}</View><Pressable disabled={busy} onPress={complete} style={styles.primary}><Text style={styles.primaryText}>{busy?'…':text.complete}</Text></Pressable></>:<Text style={styles.done}>{text.done}</Text>}</View>}
    <Text style={[styles.sectionTitle,rtl&&styles.rtl]}>{text.programWeeks}</Text>
    {Array.from({length:program.durationWeeks},(_,week)=>{const sessions=program.sessions.filter(s=>s.weekNumber===week+1);return <View key={week+1} style={styles.week}><Text style={[styles.weekTitle,rtl&&styles.rtl]}>{text.week} {week+1}</Text>{sessions.map(s=><View key={s.id} style={[styles.sessionRow,rtl&&styles.rowReverse]}><Text style={styles.sessionDay}>{s.dayNumber}</Text><View style={styles.exerciseCopy}><FitnessLocalizedText en={s.title} locale={locale} style={{...styles.sessionTitle, ...(rtl ? styles.rtl : {})}} /><FitnessLocalizedText en={s.focus} locale={locale} style={{...styles.sessionFocus, ...(rtl ? styles.rtl : {})}} /></View><Text style={styles.sessionMin}>{s.durationMin}{text.minutes}</Text></View>)}</View>})}
  </ScrollView></SafeAreaView>;
}
function Stat({label,value}:{label:string;value:string}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BRAND.colors.canvas},content:{padding:20,paddingBottom:40},back:{fontWeight:'800',color:'#374151',marginBottom:14},hero:{padding:19,borderRadius:24,backgroundColor:'#111827'},badge:{alignSelf:'flex-start',paddingHorizontal:8,paddingVertical:5,borderRadius:8,backgroundColor:'#374151'},badgeText:{color:'#FFF',fontSize:8,fontWeight:'900'},title:{marginTop:10,fontSize:27,lineHeight:33,fontWeight:'900',color:'#FFF'},description:{marginTop:8,fontSize:13,lineHeight:19,color:'#D1D5DB'},stats:{marginTop:16,flexDirection:'row',gap:10},stat:{flex:1,padding:11,borderRadius:14,backgroundColor:'#1F2937',alignItems:'center'},statValue:{fontSize:18,fontWeight:'900',color:'#FFF'},statLabel:{marginTop:3,fontSize:9,color:'#9CA3AF'},primary:{marginTop:14,padding:14,borderRadius:16,backgroundColor:BRAND.colors.primaryStrong,alignItems:'center'},primaryText:{color:'#FFF',fontSize:14,fontWeight:'900'},current:{marginTop:14,padding:17,borderRadius:22,backgroundColor:'#FFF',borderWidth:1,borderColor:'#EEF0F3'},currentLabel:{fontSize:10,fontWeight:'900',color:BRAND.colors.primaryStrong},currentTitle:{marginTop:6,fontSize:18,fontWeight:'900',color:'#111827'},currentFocus:{marginTop:4,fontSize:11,color:'#6B7280'},exerciseList:{marginTop:11,gap:8},exercise:{padding:12,borderRadius:14,backgroundColor:'#F9FAFB',flexDirection:'row',alignItems:'center',gap:10},exerciseCopy:{flex:1},exerciseName:{fontSize:13,fontWeight:'900',color:'#111827',textTransform:'capitalize'},exerciseMeta:{marginTop:3,fontSize:10,color:'#6B7280'},index:{width:26,height:26,borderRadius:13,backgroundColor:'#111827',color:'#FFF',textAlign:'center',textAlignVertical:'center',fontWeight:'900',overflow:'hidden'},done:{marginTop:12,color:'#6B7280',fontWeight:'800'},sectionTitle:{marginTop:22,fontSize:16,fontWeight:'900',color:'#111827',marginBottom:9},week:{padding:14,borderRadius:18,backgroundColor:'#FFF',borderWidth:1,borderColor:'#EEF0F3',marginBottom:9},weekTitle:{fontSize:13,fontWeight:'900',color:'#111827',marginBottom:7},sessionRow:{paddingVertical:9,flexDirection:'row',alignItems:'center',gap:9},sessionDay:{width:28,height:28,borderRadius:14,backgroundColor:'#F3F4F6',textAlign:'center',textAlignVertical:'center',fontWeight:'900',color:'#374151',overflow:'hidden'},sessionTitle:{fontSize:12,fontWeight:'900',color:'#111827'},sessionFocus:{marginTop:2,fontSize:10,color:'#6B7280'},sessionMin:{fontSize:10,fontWeight:'900',color:'#6B7280'},rtl:{textAlign:'right',writingDirection:'rtl'},rowReverse:{flexDirection:'row-reverse'},center:{flex:1,alignItems:'center',justifyContent:'center'},loading:{marginTop:10,color:'#6B7280'},errorTitle:{fontSize:18,fontWeight:'900',color:'#111827',textAlign:'center'},errorBody:{marginTop:8,color:'#6B7280',fontSize:12,textAlign:'center'}});
