INSERT INTO "Exercise" (
  "id","slug","name","nameFa","aliases","discipline","movementPattern","primaryMuscles","secondaryMuscles",
  "equipment","difficulty","goals","instructions","coachCues","commonMistakes","cautions","contentStatus",
  "sourceProvider","sourceLicense","sourceAttribution","createdAt","updatedAt"
) VALUES
('ex-0001','bodyweight-squat','Bodyweight Squat','اسکوات وزن بدن','["air squat","squat"]','calisthenics','squat','["quadriceps","glutes"]','["hamstrings","core"]','["bodyweight"]','beginner','["strength","fat_loss","general_fitness"]','Stand with feet about shoulder-width apart, sit the hips back and down, then drive through the floor to stand.',jsonb_build_array('Keep knees tracking over toes and keep the torso controlled.'),jsonb_build_array('Knees collapsing inward; heels lifting; excessive forward lean.'),jsonb_build_array('Stop if you have sharp pain or loss of balance.'),'published','MYPA Curated','MYPA-owned exercise content','Core curated exercise catalog',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('ex-0002','push-up','Push-up','شنا','["push up"]','calisthenics','horizontal_push','["chest","triceps"]','["shoulders","core"]','["bodyweight"]','beginner','["strength","body_sculpt","general_fitness"]','Brace the body in a straight line, lower the chest with control, then press the floor away.',jsonb_build_array('Keep ribs down and elbows slightly angled back.'),jsonb_build_array('Hips sagging; elbows flaring; partial range.'),jsonb_build_array('Use an incline regression when full push-ups are not yet controlled.'),'published','MYPA Curated','MYPA-owned exercise content','Core curated exercise catalog',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('ex-0003','reverse-lunge','Reverse Lunge','لانج مع قدم به عقب','["reverse lunge","lunge"]','calisthenics','lunge','["glutes","quadriceps"]','["hamstrings","core"]','["bodyweight"]','beginner','["strength","fat_loss","general_fitness"]','Step one foot back, lower under control, then push through the front foot to return.',jsonb_build_array('Stay tall and keep the front knee tracking with the toes.'),jsonb_build_array('Front heel lifting; knee collapsing inward; unstable stance.'),jsonb_build_array('Reduce range or hold support if balance is limited.'),'published','MYPA Curated','MYPA-owned exercise content','Core curated exercise catalog',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('ex-0004','glute-bridge','Glute Bridge','پل باسن','["glute bridge","hip bridge"]','calisthenics','hip_extension','["glutes"]','["hamstrings","core"]','["bodyweight"]','beginner','["strength","body_sculpt"]','Lie on your back with knees bent, brace the core and lift the hips until the body forms a comfortable line.',jsonb_build_array('Pause briefly at the top without overextending the lower back.'),jsonb_build_array('Pushing through the toes; rib flare; over-arching.'),jsonb_build_array('Use a shorter range if the lower back becomes uncomfortable.'),'published','MYPA Curated','MYPA-owned exercise content','Core curated exercise catalog',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('ex-0005','plank','Forearm Plank','پلانک ساعد','["plank"]','calisthenics','anti_extension','["core"]','["shoulders","glutes"]','["bodyweight"]','beginner','["conditioning","general_fitness"]','Brace the abdomen and hold a straight, controlled line from shoulders to hips.',jsonb_build_array('Breathe steadily while keeping the hips level.'),jsonb_build_array('Hips too high or low; breath holding.'),jsonb_build_array('Stop when position can no longer be maintained.'),'published','MYPA Curated','MYPA-owned exercise content','Core curated exercise catalog',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('ex-0006','pull-up','Pull-up','بارفیکس','["pull up","chin-up"]','calisthenics','vertical_pull','["lats","biceps"]','["upper_back","core"]','["pull_up_bar"]','intermediate','["strength","skill"]','Hang with control, brace the trunk and pull the chest toward the bar before lowering smoothly.',jsonb_build_array('Start the pull by engaging the shoulder blades.'),jsonb_build_array('Kipping without control; shrugging; incomplete range.'),jsonb_build_array('Use a band or assisted variation when needed.'),'published','MYPA Curated','MYPA-owned exercise content','Core curated exercise catalog',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('ex-0007','bench-press','Barbell Bench Press','پرس سینه هالتر','["bench press"]','gym','horizontal_push','["chest","triceps"]','["shoulders"]','["barbell","bench"]','intermediate','["strength","hypertrophy"]','Lower the bar toward the mid-chest with controlled elbows, then press it back up.',jsonb_build_array('Keep shoulder blades set and feet stable.'),jsonb_build_array('Bouncing the bar; flared elbows; unstable setup.'),jsonb_build_array('Use a safe rack/spotter setup appropriate to your environment.'),'published','MYPA Curated','MYPA-owned exercise content','Core curated exercise catalog',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('ex-0008','barbell-squat','Barbell Squat','اسکوات هالتر','["back squat","barbell squat"]','gym','squat','["quadriceps","glutes"]','["hamstrings","core"]','["barbell","rack"]','intermediate','["strength","hypertrophy"]','Set the bar securely, brace the trunk, squat to a controlled depth and drive back to standing.',jsonb_build_array('Brace before descent and keep the bar path controlled.'),jsonb_build_array('Knees collapsing inward; loss of brace; heel rise.'),jsonb_build_array('Use a lighter load and stable rack setup while learning technique.'),'published','MYPA Curated','MYPA-owned exercise content','Core curated exercise catalog',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('ex-0009','dumbbell-row','One-arm Dumbbell Row','پارویی دمبل تک‌دست','["dumbbell row","one arm row"]','gym','horizontal_pull','["lats","upper_back"]','["biceps","rear_delts"]','["dumbbell"]','beginner','["strength","hypertrophy"]','Support the body, keep the spine neutral and pull the dumbbell toward the hip.',jsonb_build_array('Lead with the elbow and avoid twisting the torso.'),jsonb_build_array('Shrugging; torso rotation; jerking the weight.'),jsonb_build_array('Choose a load that allows stable control.'),'published','MYPA Curated','MYPA-owned exercise content','Core curated exercise catalog',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('ex-0010','shoulder-press','Dumbbell Shoulder Press','پرس سرشانه دمبل','["dumbbell shoulder press","overhead press"]','gym','vertical_push','["shoulders"]','["triceps","upper_chest"]','["dumbbells"]','beginner','["strength","hypertrophy"]','Press the dumbbells overhead from a stable seated or standing position, then lower with control.',jsonb_build_array('Keep wrists stacked and ribs controlled.'),jsonb_build_array('Overarching the back; lowering too fast.'),jsonb_build_array('Use a lighter load if shoulder comfort or control is limited.'),'published','MYPA Curated','MYPA-owned exercise content','Core curated exercise catalog',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('ex-0011','lat-pulldown','Lat Pulldown','لت پول‌داون','["lat pulldown"]','gym','vertical_pull','["lats"]','["biceps","upper_back"]','["cable_machine"]','beginner','["strength","hypertrophy"]','Pull the bar toward the upper chest while keeping the torso steady, then return under control.',jsonb_build_array('Drive the elbows down and back rather than pulling with the hands alone.'),jsonb_build_array('Leaning too far back; shrugging; momentum.'),jsonb_build_array('Adjust load so the full movement stays controlled.'),'published','MYPA Curated','MYPA-owned exercise content','Core curated exercise catalog',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('ex-0012','romanian-deadlift','Romanian Deadlift','ددلیفت رومانیایی','["RDL","romanian deadlift"]','gym','hip_hinge','["hamstrings","glutes"]','["back"]','["barbell","dumbbells"]','intermediate','["strength","hypertrophy"]','Hinge at the hips with a neutral spine, keep the load close, then drive the hips forward to stand.',jsonb_build_array('Move from the hips and keep the trunk braced.'),jsonb_build_array('Rounding the back; bending the knees excessively; drifting the load.'),jsonb_build_array('Use a range that preserves a controlled neutral position.'),'published','MYPA Curated','MYPA-owned exercise content','Core curated exercise catalog',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('ex-0013','cat-cow','Cat-Cow','گربه-شتر','["cat cow"]','yoga','spinal_mobility','["spine"]','["shoulders","hips"]','["yoga_mat"]','beginner','["mobility","recovery"]','Move slowly between a comfortable rounded and extended spinal position while coordinating breathing.',jsonb_build_array('Use a smooth range rather than forcing end positions.'),jsonb_build_array('Moving too quickly; forcing the neck.'),jsonb_build_array('Keep the range comfortable and pain-free.'),'published','MYPA Curated','MYPA-owned exercise content','Core curated exercise catalog',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('ex-0014','hip-flexor-stretch','Half-kneeling Hip Flexor Stretch','کشش فلکسور ران','["hip flexor stretch"]','yoga','hip_mobility','["hip_flexors"]','["glutes","core"]','["yoga_mat"]','beginner','["mobility","recovery"]','Kneel with one foot forward, gently shift the hips forward while keeping the pelvis controlled.',jsonb_build_array('Squeeze the rear glute and stay tall.'),jsonb_build_array('Arching the lower back; pushing too far.'),jsonb_build_array('Back off the range if there is pinching or sharp discomfort.'),'published','MYPA Curated','MYPA-owned exercise content','Core curated exercise catalog',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('ex-0015','spine-twist','Supine Spine Twist','چرخش ستون فقرات درازکش','["spine twist"]','yoga','spinal_rotation','["obliques"]','["glutes","back"]','["yoga_mat"]','beginner','["mobility","recovery"]','Lie comfortably and rotate the knees toward one side while keeping the movement slow and controlled.',jsonb_build_array('Breathe normally and avoid forcing the range.'),jsonb_build_array('Forcing rotation; lifting the shoulder aggressively.'),jsonb_build_array('Stay within a comfortable range.'),'published','MYPA Curated','MYPA-owned exercise content','Core curated exercise catalog',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO NOTHING;

INSERT INTO "ExerciseRelationship" ("id","fromExerciseId","toExerciseId","kind","priority","notes","createdAt")
VALUES
('rel-0001','ex-0003','ex-0001','alternative',10,'Both are lower-body beginner options.','2026-09-18T00:00:00Z'),
('rel-0002','ex-0002','ex-0007','alternative',20,'Machine/barbell pressing alternative for different training contexts.','2026-09-18T00:00:00Z'),
('rel-0003','ex-0005','ex-0013','regression',10,'Mobility/reset option between core-focused sessions.','2026-09-18T00:00:00Z'),
('rel-0004','ex-0006','ex-0009','regression',10,'Dumbbell row can build pulling strength before pull-up work.','2026-09-18T00:00:00Z')
ON CONFLICT ("fromExerciseId","toExerciseId","kind") DO NOTHING;
